import 'package:axiom/features/lesson_player/domain/lesson.dart';
import 'package:axiom/features/lesson_player/domain/reducer.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

/// Holds [LessonState] and the facts recorded beside it.
class LessonPlayer extends AutoDisposeFamilyNotifier<LessonState, Lesson> {
  final List<ScreenFact> facts = [];
  final Map<int, DateTime> shownAt = {};
  final Map<int, String> resultIds = {};
  final Set<int> recorded = {};
  static const _uuid = Uuid();

  @override
  LessonState build(Lesson lesson) {
    _mark(0);
    return initialLessonState();
  }

  void change(Object? answer) {
    state = reduce(state, AnswerChanged(answer), arg);
  }

  void check() {
    final before = state;
    if (before is! LessonPresenting) return;
    final index = before.screenIndex;
    final started = shownAt[index] ?? DateTime.now();
    state = reduce(state, const CheckPressed(), arg);
    final after = state;
    if (after is! LessonFeedback || !recorded.add(index)) return;
    final elapsed = DateTime.now().difference(started).inMilliseconds;
    facts.add(
      ScreenFact(
        screenId: arg.screens[index].id,
        correct: after.correct,
        latencyMs: elapsed < 0 ? 0 : elapsed,
        errorCode: after.errorCode,
        hadMiss: after.hadMiss[index] ?? false,
        clientResultId: resultIds[index] ?? _uuid.v4(),
      ),
    );
  }

  void continueLesson(void Function(LessonResult result) onFinished) {
    state = reduce(state, const ContinuePressed(), arg);
    final next = state;
    if (next is LessonPresenting) _mark(next.screenIndex);
    if (next is LessonComplete) {
      onFinished(LessonResult(List<ScreenFact>.unmodifiable(facts)));
    }
  }

  void _mark(int index) {
    shownAt.putIfAbsent(index, DateTime.now);
    resultIds.putIfAbsent(index, _uuid.v4);
  }
}

/// One player per lesson id.
// The family provider's type is generated by the constructor.
// ignore: specify_nonobvious_property_types
final lessonPlayerProvider = NotifierProvider.autoDispose
    .family<LessonPlayer, LessonState, Lesson>(LessonPlayer.new);
