import { choice, drag, hill, lesson, skill, slider, type SkillDraft } from "./helpers";

const uphill = { start: [2, 2] as [number, number], tip: [7, 6] as [number, number] };
const downhill = { start: [2, 6] as [number, number], tip: [7, 2] as [number, number] };
const flat = { start: [2, 4] as [number, number], tip: [7, 4] as [number, number] };

export const changeSkills: SkillDraft[] = [
  skill(
    "rise-run",
    "Rise and run",
    "You can read rise, run, and slope.",
    "Pip can read a slope.",
    "change",
    [
      lesson("Read the rise", "A training step measures how steep the loss is.", [
        choice(
          "rise",
          "The gray arrow runs right and climbs. The rise is the...",
          [
            ["a", "Vertical part"],
            ["b", "Horizontal part"],
          ],
          "a",
          "The horizontal part is the run. The climb is the rise.",
          "Rise is the vertical part.",
          { arrows: [{ start: [2, 2], tip: [7, 6], guide: true }] },
        ),
        slider(
          "climb",
          "The arrow climbs from y = 2 to y = 6. Set the rise.",
          0,
          10,
          4,
          "The climb is larger. Move higher.",
          "The climb is smaller. Move lower.",
          "The rise is the change in y.",
        ),
        slider(
          "run",
          "The arrow runs from x = 1 to x = 7. Set the run.",
          0,
          10,
          6,
          "The run is longer. Move higher.",
          "The run is shorter. Move lower.",
          "The run is the change in x.",
        ),
        choice(
          "name",
          "Rise divided by run is the...",
          [
            ["a", "Slope"],
            ["b", "Run alone"],
          ],
          "a",
          "The run alone ignores the climb. Slope uses both.",
          "Slope is rise over run.",
        ),
        hill(
          "draw",
          "Walk Pip run 3 and rise 2 from the dot.",
          [2, 2],
          2 / 3,
          3,
          2,
          "The step climbs as it runs right.",
          "The run is 3 and the rise is 2.",
          "Pip walked that stair.",
        ),
      ]),
      lesson("Find the slope", "The slope is the rate a small step changes the loss.", [
        choice(
          "easy",
          "Rise 2, run 1. The slope is...",
          [
            ["a", "2"],
            ["b", "1"],
            ["c", "3"],
          ],
          "a",
          "3 adds them. 1 is only the run. Divide the rise by the run.",
          "Two up for each step right.",
        ),
        slider(
          "six",
          "Rise 6, run 2. Set the slope.",
          0,
          10,
          3,
          "6 spread over 2 is higher. Move up.",
          "6 spread over 2 is lower. Move down.",
          "The slope is rise divided by run.",
        ),
        slider(
          "even",
          "Rise 3, run 3. Set the slope.",
          0,
          10,
          1,
          "Equal rise and run is a slope of 1. Move up.",
          "Equal rise and run is not steeper than 1. Move down.",
          "One up for each step right.",
        ),
        choice(
          "longer",
          "A larger run with the same rise makes the slope...",
          [
            ["a", "Smaller"],
            ["b", "Larger"],
          ],
          "a",
          "The same climb spread over more run is flatter.",
          "More run, smaller slope.",
        ),
        hill(
          "along",
          "The slope is 2. From the dot, go 2 right along the hill.",
          [2, 2],
          2,
          2,
          4,
          "The hill climbs as Pip runs right.",
          "Each step right climbs 2. Two steps climb 4.",
          "Pip followed the slope.",
        ),
      ]),
      lesson("The longer run", "A long shallow step can change the loss less than a short steep one.", [
        choice(
          "which",
          "Both rise 4. Arrow A runs 2. Arrow B runs 6. Which is steeper?",
          [
            ["a", "A"],
            ["b", "B"],
          ],
          "a",
          "B is longer, but the same rise over a longer run is flatter.",
          "The shorter run is the steeper slope.",
        ),
        slider(
          "steep",
          "Rise 8, run 2. Set the slope.",
          0,
          10,
          4,
          "8 over 2 is higher. Move up.",
          "8 over 2 is lower. Move down.",
          "That short run is steep.",
        ),
        slider(
          "shallow",
          "Rise 8, run 4. Set the slope.",
          0,
          10,
          2,
          "8 over 4 is higher. Move up.",
          "8 over 4 is lower. Move down.",
          "The longer run is flatter.",
        ),
        choice(
          "why",
          "The longer arrow is flatter when...",
          [
            ["a", "It uses a longer run for the same rise"],
            ["b", "It points up"],
          ],
          "a",
          "Pointing up only sets the sign. The run sets how flat it is.",
          "Same rise, longer run, smaller slope.",
        ),
        drag(
          "draw",
          "Match the steeper arrow: rise 3, run 1, from (2, 2).",
          [2, 2],
          [3, 5],
          "The steep arrow climbs sharply.",
          "The run is 1 and the rise is 3.",
          "Short run, large rise.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "slope-sign",
    "Sign of a slope",
    "You can tell a rise from a fall.",
    "Pip can read the sign of a slope.",
    "change",
    [
      lesson("Uphill", "The sign says whether a step climbs or falls.", [
        choice(
          "up",
          "This arrow climbs as it runs right. The slope is...",
          [
            ["a", "Positive"],
            ["b", "Negative"],
          ],
          "a",
          "A climb to the right is a positive slope.",
          "Uphill to the right is positive.",
          { arrows: [{ ...uphill, guide: true }] },
        ),
        choice(
          "down",
          "This arrow falls as it runs right. The slope is...",
          [
            ["a", "Negative"],
            ["b", "Positive"],
          ],
          "a",
          "A fall to the right is a negative slope.",
          "Downhill to the right is negative.",
          { arrows: [{ ...downhill, guide: true }] },
        ),
        choice(
          "flat",
          "This arrow stays level. The slope is...",
          [
            ["a", "Zero"],
            ["b", "Positive"],
          ],
          "a",
          "No climb and no fall means a zero slope.",
          "Level means slope zero.",
          { arrows: [{ ...flat, guide: true }] },
        ),
        hill(
          "mark",
          "Walk Pip uphill along the plank.",
          [2, 2],
          0.8,
          5,
          4,
          "Uphill goes up and to the right.",
          "Match the climb of the hill.",
          "The ball rolls up.",
        ),
        choice(
          "means",
          "A positive slope means the arrow...",
          [
            ["a", "Rises as it runs right"],
            ["b", "Falls as it runs right"],
          ],
          "a",
          "A fall to the right would be negative.",
          "Positive means a rise to the right.",
        ),
      ]),
      lesson("Read the sign", "Read the sign from the picture, not from the length.", [
        choice(
          "sign",
          "What sign is this slope?",
          [
            ["a", "Negative"],
            ["b", "Zero"],
            ["c", "Positive"],
          ],
          "a",
          "The arrow falls as it runs right. Length does not flip the sign.",
          "A fall to the right is negative.",
          { arrows: [{ ...downhill, guide: true }] },
        ),
        slider(
          "fall",
          "The arrow falls 4 while it runs 2 right. Set the slope.",
          -5,
          5,
          -2,
          "A fall of 4 over 2 is lower. Move down.",
          "That is past the fall. Move toward zero.",
          "Fall over run is a negative slope.",
        ),
        slider(
          "rise",
          "The arrow rises 6 over a run of 3. Set the slope.",
          -5,
          5,
          2,
          "6 over 3 is higher. Move up.",
          "6 over 3 is lower. Move down.",
          "Rise over run is positive.",
        ),
        choice(
          "level",
          "A flat arrow has slope...",
          [
            ["a", "Zero"],
            ["b", "Positive, because it is long"],
          ],
          "a",
          "Length is not the sign. A level arrow has slope zero.",
          "No rise, slope zero.",
        ),
        hill(
          "down",
          "Tip the step downhill: run 3, fall 2.",
          [2, 6],
          -2 / 3,
          3,
          -2,
          "Downhill to the right falls as it runs.",
          "The run is 3 and the fall is 2.",
          "The ball rolls down.",
        ),
      ]),
      lesson("Long and downhill", "A long step downhill is still a negative slope.", [
        choice(
          "long",
          "A long arrow points down and right. Its slope is...",
          [
            ["a", "Negative"],
            ["b", "Positive, because it is long"],
            ["c", "Zero"],
          ],
          "a",
          "Length is large. The sign still follows the fall.",
          "Long and downhill is still negative.",
          { arrows: [{ start: [1, 8], tip: [8, 2], guide: true }] },
        ),
        slider(
          "drop",
          "Fall 8 over run 4. Set the slope.",
          -5,
          5,
          -2,
          "8 over 4, downhill, is lower. Move down.",
          "That is past the slope. Move toward zero.",
          "The long fall still has a modest negative slope.",
        ),
        choice(
          "fact",
          "Which fact sets the sign?",
          [
            ["a", "Whether the arrow rises or falls"],
            ["b", "How long the arrow is"],
          ],
          "a",
          "Length changes the size. Rise or fall changes the sign.",
          "The sign follows the climb or the fall.",
        ),
        slider(
          "steep-down",
          "Fall 3 over run 1. Set the slope.",
          -5,
          5,
          -3,
          "A fall of 3 over 1 is lower. Move down.",
          "That is past the fall. Move toward zero.",
          "Short run, large fall, negative slope.",
        ),
        drag(
          "draw",
          "Draw the long downhill move: 4 right and 3 down from (2, 7).",
          [2, 7],
          [6, 4],
          "The long move still falls as it runs right.",
          "The run is 4 and the fall is 3.",
          "Long, and still downhill.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "steeper",
    "Steeper",
    "You can tell which slope is steeper.",
    "Pip can pick the steeper slope.",
    "change",
    [
      lesson("See the steep one", "Steeper means more rise for the same run.", [
        choice(
          "pair",
          "A rises 4 over run 1. B rises 1 over run 4. Which is steeper?",
          [
            ["a", "A"],
            ["b", "B"],
          ],
          "a",
          "B is the longer, flatter arrow. A climbs more per step.",
          "More rise on a shorter run is steeper.",
        ),
        hill(
          "mark",
          "Set Pip on the steeper plank.",
          [2, 2],
          4,
          1,
          4,
          "The steep plank climbs sharply.",
          "The run is 1 and the rise is 4.",
          "The ball picks the steep plank.",
        ),
        slider(
          "slope",
          "Rise 6, run 3. Set the slope.",
          0,
          10,
          2,
          "6 over 3 is higher. Move up.",
          "6 over 3 is lower. Move down.",
          "The slope is 2.",
        ),
        choice(
          "means",
          "Steeper means...",
          [
            ["a", "More rise for the same run"],
            ["b", "A longer arrow"],
          ],
          "a",
          "A longer arrow can be flatter. Steep is rise compared with run.",
          "Compare rise with run.",
        ),
        choice(
          "flat",
          "A flat arrow and a rising arrow. The rising one is...",
          [
            ["a", "Steeper"],
            ["b", "Flatter"],
          ],
          "a",
          "Flat has slope zero. Any rise is steeper than that.",
          "A rise is steeper than level.",
        ),
      ]),
      lesson("Longer but flatter", "The longer arrow can be the flatter one.", [
        choice(
          "trap",
          "A is rise 3, run 1. B is rise 3, run 6. Which is steeper?",
          [
            ["a", "A"],
            ["b", "B, because it is longer"],
          ],
          "a",
          "B travels farther, but the same rise over a longer run is flatter.",
          "The short steep arrow wins.",
        ),
        slider(
          "steep",
          "The steep arrow: rise 8, run 2. Set its slope.",
          0,
          10,
          4,
          "8 over 2 is higher. Move up.",
          "8 over 2 is lower. Move down.",
          "The short arrow is steep.",
        ),
        slider(
          "long",
          "The long arrow: rise 8, run 4. Set its slope.",
          0,
          10,
          2,
          "8 over 4 is higher. Move up.",
          "8 over 4 is lower. Move down.",
          "The long arrow is flatter.",
        ),
        choice(
          "winner",
          "You compared slopes, not lengths. The winner is...",
          [
            ["a", "The larger slope"],
            ["b", "The longer drawing"],
          ],
          "a",
          "The longer drawing can hide a smaller slope.",
          "The larger slope is steeper.",
        ),
        drag(
          "draw",
          "Draw the steeper move, not the longer one: rise 4, run 1, from (2, 2).",
          [2, 2],
          [3, 6],
          "The steep move climbs sharply, not along a long shallow line.",
          "The run is 1 and the rise is 4.",
          "Short and steep.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "rate",
    "Rate",
    "You can find distance per step.",
    "Pip can compare rates.",
    "change",
    [
      lesson("Per step", "Learning rate is how far a step moves for each unit of slope.", [
        choice(
          "split",
          "A trip covers 6 in 2 equal steps. Each step covers...",
          [
            ["a", "3"],
            ["b", "6"],
            ["c", "2"],
          ],
          "a",
          "6 is the whole trip. 2 is the number of steps. Divide.",
          "Each step covers 3.",
        ),
        slider(
          "twelve",
          "12 units in 3 equal steps. Set the rate per step.",
          0,
          10,
          4,
          "12 split into 3 is higher. Move up.",
          "12 split into 3 is lower. Move down.",
          "The rate is distance divided by steps.",
        ),
        slider(
          "eight",
          "8 units in 2 equal steps. Set the rate.",
          0,
          10,
          4,
          "8 split into 2 is higher. Move up.",
          "8 split into 2 is lower. Move down.",
          "Each step covers the same ground.",
        ),
        choice(
          "means",
          "Rate is...",
          [
            ["a", "Distance divided by steps"],
            ["b", "Distance plus steps"],
          ],
          "a",
          "Adding the step count to the distance is not a rate.",
          "Rate is distance per step.",
        ),
        hill(
          "two",
          "Each hop runs 2 right. Walk two hops from the dot.",
          [1, 3],
          0,
          4,
          0,
          "The hops stay level.",
          "Two hops of 2 land 4 to the right.",
          "That is the faster spacing.",
        ),
      ]),
      lesson("Fewer steps", "The same drop in fewer steps is a faster rate.", [
        choice(
          "faster",
          "A covers 8 in 4 steps. B covers 8 in 2 steps. Which is faster?",
          [
            ["a", "B"],
            ["b", "A, because it takes more steps"],
          ],
          "a",
          "More steps for the same distance is the slower rate.",
          "Fewer steps, same distance, faster rate.",
        ),
        slider(
          "quick",
          "Same distance 10, in 2 steps. Set the rate.",
          0,
          10,
          5,
          "10 split into 2 is higher. Move up.",
          "10 split into 2 is lower. Move down.",
          "This trip is the fast one.",
        ),
        slider(
          "slow",
          "Same distance 12, in 4 steps. Set the rate.",
          0,
          10,
          3,
          "12 split into 4 is higher. Move up.",
          "12 split into 4 is lower. Move down.",
          "More steps make a slower rate.",
        ),
        choice(
          "means",
          "Faster means...",
          [
            ["a", "More distance per step"],
            ["b", "More steps for the same distance"],
          ],
          "a",
          "More steps for the same distance slows the rate.",
          "Faster is more ground per step.",
        ),
        choice(
          "steep",
          "A short steep step and a long shallow trip cover the same ground. The steep step has...",
          [
            ["a", "The higher rate"],
            ["b", "The lower rate, because the trip is shorter"],
          ],
          "a",
          "A shorter trip with the same ground is the higher rate.",
          "Steep here means the higher rate.",
        ),
      ]),
    ],
  ),
  skill(
    "tiny-step",
    "Tiny step",
    "You can read the slope where you stand.",
    "Pip can read a local slope.",
    "change",
    [
      lesson("Straight hill", "On a straight slope, one small step matches the whole hill.", [
        choice(
          "match",
          "A hill rises 4 over run 4. A small step rises 1 over run 1. The slopes...",
          [
            ["a", "Match"],
            ["b", "Differ"],
          ],
          "a",
          "Both are 1. On a straight hill the small step copies the hill.",
          "The tiny step matches the hill.",
        ),
        slider(
          "whole",
          "The whole hill: rise 6, run 3. Set the slope.",
          0,
          10,
          2,
          "6 over 3 is higher. Move up.",
          "6 over 3 is lower. Move down.",
          "The hill's slope is 2.",
        ),
        choice(
          "small",
          "A small step on that hill rises 2 over run 1. Its slope is...",
          [
            ["a", "2"],
            ["b", "6"],
          ],
          "a",
          "6 was the whole rise. The small step is 2 over 1.",
          "The small step copies the slope.",
        ),
        choice(
          "copies",
          "On a straight hill, the tiny step...",
          [
            ["a", "Copies the hill's slope"],
            ["b", "Has slope zero"],
          ],
          "a",
          "A straight hill has the same slope everywhere on it.",
          "The tiny step agrees with the hill.",
        ),
        hill(
          "draw",
          "Take the baby step: run 2, rise 2.",
          [3, 3],
          1,
          2,
          2,
          "The baby step climbs with the hill.",
          "The run is 2 and the rise is 2.",
          "The baby step matches the hill.",
        ),
      ]),
      lesson("At this spot", "A derivative is the slope of a tiny step, not of the whole trip.", [
        choice(
          "which",
          "The path climbs, then falls. The slope at the start is the slope of...",
          [
            ["a", "The first small piece"],
            ["b", "The whole path, start to end"],
          ],
          "a",
          "The whole path mixes the climb and the fall. You stand on the first piece.",
          "Use the slope under your feet.",
        ),
        choice(
          "sign",
          "The first piece rises. The path ends lower. The slope at the start is...",
          [
            ["a", "Positive"],
            ["b", "Negative"],
          ],
          "a",
          "The ending is lower, but you are still on the rising piece.",
          "The local slope is positive.",
          {
            arrows: [
              { start: [2, 2], tip: [4, 6], guide: true },
              { start: [4, 6], tip: [8, 3] },
            ],
          },
        ),
        slider(
          "local",
          "First piece: rise 6, run 2. Set the local slope.",
          -5,
          5,
          3,
          "6 over 2 is higher. Move up.",
          "6 over 2 is lower. Move down.",
          "The local slope is the first piece.",
        ),
        slider(
          "average",
          "The whole trip starts and ends at the same height. Set the average slope.",
          -5,
          5,
          0,
          "No net climb is not a negative slope. The average is zero.",
          "No net climb. Move down to zero.",
          "The average can be zero while the start still climbs.",
        ),
        choice(
          "disagree",
          "The local slope and the average slope...",
          [
            ["a", "Can disagree"],
            ["b", "Must match"],
          ],
          "a",
          "The start can climb while the whole trip ends where it began.",
          "Local and average can disagree.",
        ),
      ]),
      lesson("Hill then valley", "Training looks at the slope where you stand.", [
        choice(
          "trust",
          "You stand on the rising side. The valley is ahead. Your next step uses...",
          [
            ["a", "The rising slope under you"],
            ["b", "The slope from the hilltop to the valley floor"],
          ],
          "a",
          "The valley is ahead. The step uses the slope where you stand.",
          "Use the local slope.",
        ),
        slider(
          "local",
          "Under you: rise 6, run 2. Set the local slope.",
          -5,
          5,
          3,
          "6 over 2 is higher. Move up.",
          "6 over 2 is lower. Move down.",
          "The ground under you still climbs.",
        ),
        slider(
          "net",
          "The path rises 2, then falls 6, over a total run of 4. Set the average slope.",
          -5,
          5,
          -1,
          "The net change is a fall. Move down.",
          "The fall is spread over the whole run. Move toward zero.",
          "The average falls. The start still climbed.",
        ),
        choice(
          "which",
          "Which slope should the step trust?",
          [
            ["a", "The local slope"],
            ["b", "The average slope"],
          ],
          "a",
          "The average includes ground you have not reached.",
          "Trust the slope where you stand.",
        ),
        drag(
          "draw",
          "Draw the local uphill step: run 1, rise 2, from (2, 3).",
          [2, 3],
          [3, 5],
          "The local step still climbs, even if a valley is ahead.",
          "The run is 1 and the rise is 2.",
          "That is the slope under you.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "hilltop",
    "Hilltop",
    "You can find where the slope goes flat.",
    "Pip can find a flat top.",
    "change",
    [
      lesson("Flat on top", "A flat top is where a training step shrinks toward nothing.", [
        choice(
          "top",
          "At the top, the next tiny step is...",
          [
            ["a", "Flat"],
            ["b", "Still climbing"],
          ],
          "a",
          "Still climbing means you have not reached the top.",
          "The step at the top is flat.",
        ),
        slider(
          "zero",
          "The step at the top does not rise or fall. Set the slope.",
          -5,
          5,
          0,
          "A flat step is not negative. The slope is zero.",
          "A flat step is not positive. Move down.",
          "Slope zero, for this one step.",
        ),
        choice(
          "right",
          "Left of the top, the slope is positive. Right of the top, the slope is...",
          [
            ["a", "Negative"],
            ["b", "Still positive"],
          ],
          "a",
          "Past the top, the path falls. The slope changes sign.",
          "Right of the top, the slope is negative.",
        ),
        hill(
          "flat",
          "At the top, walk a flat step. The ball should sit.",
          [3, 6],
          0,
          4,
          0,
          "The step at the top stays level.",
          "The run continues and the rise is zero.",
          "The ball sits on the top.",
        ),
        choice(
          "train",
          "A training step at a flat top...",
          [
            ["a", "Shrinks toward nothing"],
            ["b", "Keeps a large climb"],
          ],
          "a",
          "There is no climb left to follow. The step shrinks.",
          "A flat top quiets the step.",
        ),
      ]),
      lesson("Not the top", "A zero slope is the top only when the sides point opposite ways.", [
        choice(
          "shelf",
          "A path climbs, goes flat for one step, then climbs again. That flat step is...",
          [
            ["a", "Not the top"],
            ["b", "The top, because the slope is zero"],
          ],
          "a",
          "The climb continues after the flat step. The top is still ahead.",
          "A shelf in a climb is not the top.",
        ),
        choice(
          "true",
          "The true top is where...",
          [
            ["a", "The slope changes from up to down"],
            ["b", "The slope is zero for any reason"],
          ],
          "a",
          "Zero in the middle of a climb is a shelf, not a top.",
          "Up, then down, marks the top.",
        ),
        slider(
          "left",
          "Just left of the top: rise 6, run 2. Set the slope.",
          -5,
          5,
          3,
          "6 over 2 is higher. Move up.",
          "6 over 2 is lower. Move down.",
          "Left of the top, the slope is positive.",
        ),
        slider(
          "right",
          "Just right of the top: fall 6, run 2. Set the slope.",
          -5,
          5,
          -3,
          "A fall of 6 over 2 is lower. Move down.",
          "That is past the fall. Move toward zero.",
          "Right of the top, the slope is negative.",
        ),
        choice(
          "keep",
          "You found a flat step in the middle of a climb. You should...",
          [
            ["a", "Keep going, the top is still ahead"],
            ["b", "Stop, every flat step is the top"],
          ],
          "a",
          "The next piece still climbs. This flat step is not the top.",
          "A shelf is not a reason to stop.",
        ),
      ]),
    ],
  ),
  skill(
    "accumulation",
    "Accumulation",
    "You can add slices into a total.",
    "Pip can add a running total.",
    "change",
    [
      lesson("Slices add", "Accumulated slices are a running total.", [
        choice(
          "two",
          "Two slices each of height 3. The total is...",
          [
            ["a", "6"],
            ["b", "3"],
            ["c", "9"],
          ],
          "a",
          "3 keeps one slice. 9 adds an extra slice.",
          "The slices add.",
        ),
        slider(
          "three",
          "Slices of 2, 2, and 3. Set the total.",
          0,
          10,
          7,
          "Add every slice. Move higher.",
          "That total is past the slices. Move lower.",
          "The running total adds the slices.",
        ),
        slider(
          "pair",
          "Slices of 4 and 5. Set the total.",
          0,
          10,
          9,
          "4 plus 5 is higher. Move up.",
          "4 plus 5 is lower. Move down.",
          "Two slices add.",
        ),
        choice(
          "means",
          "Accumulation means...",
          [
            ["a", "Adding the slices"],
            ["b", "Keeping only the tallest slice"],
          ],
          "a",
          "The tallest slice leaves the others out. A total adds them.",
          "Add the slices.",
        ),
        drag(
          "rise",
          "The total rise is 4. Draw it straight up from (4, 1).",
          [4, 1],
          [4, 5],
          "The total is a vertical rise.",
          "The rise is 4.",
          "The slices stack into one rise.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Same total", "Different shapes can hide the same accumulated total.", [
        choice(
          "match",
          "A tall slice of 4, and two slices of 2. The totals...",
          [
            ["a", "Match"],
            ["b", "Differ, because the shapes differ"],
          ],
          "a",
          "The shapes differ. 4 and 2 + 2 are the same total.",
          "Same total, different shape.",
        ),
        slider(
          "wide",
          "Wide stack: slices of 1, 2, and 3. Set the total.",
          0,
          10,
          6,
          "Add all three slices. Move higher.",
          "That is past the three slices. Move lower.",
          "The wide stack totals 6.",
        ),
        slider(
          "tall",
          "Tall stack: a piece of 5 plus a piece of 1. Set the total.",
          0,
          10,
          6,
          "5 plus 1 is higher. Move up.",
          "5 plus 1 is lower. Move down.",
          "The tall stack matches the wide one.",
        ),
        choice(
          "shape",
          "Same total, different shape. The accumulation...",
          [
            ["a", "Can match"],
            ["b", "Must follow the shape"],
          ],
          "a",
          "Shape is not the total. Different slices can add to the same number.",
          "Totals can match while shapes differ.",
        ),
        choice(
          "which",
          "Which stack totals 6?",
          [
            ["a", "A slice of 2 and a slice of 4"],
            ["b", "A slice of 2 and a slice of 2"],
            ["c", "A slice of 5 alone"],
          ],
          "a",
          "2 and 2 make 4. 5 alone is short of 6.",
          "2 plus 4 is the matching total.",
        ),
      ]),
    ],
  ),
  skill(
    "downhill-step",
    "Downhill step",
    "You can step against the slope.",
    "Pip can step downhill.",
    "change",
    [
      lesson(
        "Step against the slope",
        "A training step walks against the slope, toward lower loss.",
        [
          choice(
            "way",
            "The slope points uphill. A step that lowers the height points...",
            [
              ["a", "The other way"],
              ["b", "The same way as the slope"],
            ],
            "a",
            "Walking with the slope climbs. The lowering step goes against it.",
            "Downhill is against the slope.",
          ),
          hill(
            "back",
            "Walk against the slope so the pebble drops.",
            [6, 6],
            1,
            -3,
            -3,
            "Downhill goes back along the climb.",
            "The step back matches the hill.",
            "The pebble dropped.",
          ),
          choice(
            "with",
            "Walking with the slope makes the height...",
            [
              ["a", "Rise"],
              ["b", "Fall"],
            ],
            "a",
            "With the slope is uphill. Against it is the fall.",
            "With the slope, you climb.",
          ),
          slider(
            "drop",
            "The slope is 3. You step 2 against it. Set the drop in height.",
            0,
            10,
            6,
            "Slope times the step is a larger drop. Move up.",
            "The drop is smaller than that. Move down.",
            "The drop is slope times the step.",
          ),
          choice(
            "steep",
            "Two slopes: 1 and 4. The steeper one calls for...",
            [
              ["a", "The larger downhill step"],
              ["b", "The same step as the gentle slope"],
            ],
            "a",
            "The gentle slope can take a smaller step. The steep one wants more.",
            "A steeper slope wants a larger step against it.",
          ),
          choice(
            "which",
            "Which arrow decreases height?",
            [
              ["a", "The one against the gray uphill arrow"],
              ["b", "The one with the gray uphill arrow"],
            ],
            "a",
            "The arrow with the gray one climbs. Against it, the height falls.",
            "Against the slope, the height falls.",
            {
              arrows: [
                { start: [2, 2], tip: [6, 6], guide: true },
                { start: [6, 6], tip: [3, 3] },
              ],
            },
          ),
          drag(
            "hide",
            "Slope rises 2 over run 2. From (6, 6), step back by that same run.",
            [6, 6],
            [4, 4],
            "Stepping back follows the slope downward.",
            "The run back is 2 and the drop is 2.",
            "You walked against the slope.",
            undefined,
            undefined,
            false,
          ),
          choice(
            "taught",
            "You taught Pip to train. The step...",
            [
              ["a", "Walks against the slope"],
              ["b", "Walks with the slope to climb"],
            ],
            "a",
            "Climbing would raise the loss. Training walks against the slope.",
            "The step goes downhill.",
          ),
        ],
        true,
      ),
    ],
  ),
];
