import { choice, lesson, skill, slider, type SkillDraft } from "./helpers";

export const chanceSkills: SkillDraft[] = [
  skill(
    "outcomes",
    "Outcomes",
    "You can list what can happen.",
    "Pip can list outcomes.",
    "chance",
    [
      lesson("One toss", "A model scores an outcome before it knows which one happens.", [
        choice(
          "lands",
          "A fair toss lands as...",
          [
            ["a", "Heads or tails"],
            ["b", "Heads only"],
          ],
          "a",
          "A fair toss has two landings, not one.",
          "Two outcomes, equally open.",
        ),
        choice(
          "count",
          "How many outcomes does one toss have?",
          [
            ["a", "Two"],
            ["b", "One"],
          ],
          "a",
          "Heads and tails are both possible.",
          "One toss, two outcomes.",
        ),
        slider(
          "how",
          "Set how many outcomes a single toss has.",
          0,
          10,
          2,
          "Heads and tails are two outcomes. Move up.",
          "A single toss has fewer than that. Move down.",
          "Two ways to land.",
        ),
        choice(
          "fair",
          "Each outcome of a fair toss is...",
          [
            ["a", "Equally likely"],
            ["b", "Sure to be heads"],
          ],
          "a",
          "Sure heads would erase tails. A fair toss shares the chance.",
          "Fair means equal chances.",
        ),
        choice(
          "what",
          "An outcome is...",
          [
            ["a", "One way the toss can land"],
            ["b", "Only the toss that already happened"],
          ],
          "a",
          "You can list outcomes before the toss. They are the ways it can land.",
          "An outcome is a possible landing.",
        ),
      ]),
      lesson("Two tosses", "Both heads is one outcome. One head can happen in more ways.", [
        choice(
          "both",
          "Two tosses. Both heads is...",
          [
            ["a", "One outcome"],
            ["b", "The same as every result with a head"],
          ],
          "a",
          "Results with one head are different outcomes. Both heads is one of them.",
          "Both heads is a single outcome.",
        ),
        choice(
          "more",
          "Which can happen in more ways?",
          [
            ["a", "Exactly one head"],
            ["b", "Both heads"],
          ],
          "a",
          "Both heads is only one listing. Exactly one head has two listings.",
          "One head has more ways.",
        ),
        slider(
          "four",
          "List HH, HT, TH, and TT. Set how many outcomes that is.",
          0,
          10,
          4,
          "Each listing is an outcome. Move up.",
          "You counted a listing twice. Move down.",
          "Four listings, four outcomes.",
        ),
        choice(
          "order",
          "HT and TH are...",
          [
            ["a", "Different outcomes with one head each"],
            ["b", "The same outcome"],
          ],
          "a",
          "The first toss differs. HT and TH are different listings.",
          "Order makes them different outcomes.",
        ),
        choice(
          "why",
          "Both heads is not the same as one head, because...",
          [
            ["a", "They are different outcomes"],
            ["b", "Both heads includes every toss with a head"],
          ],
          "a",
          "Both heads does not include HT or TH. Those are other outcomes.",
          "Different listings, different outcomes.",
        ),
      ]),
    ],
  ),
  skill(
    "chance-size",
    "Size of a chance",
    "You can compare favorable with possible.",
    "Pip can size a chance.",
    "chance",
    [
      lesson("One out of two", "A score between impossible and sure is a chance.", [
        choice(
          "half",
          "1 favorable out of 2 possible. The chance is...",
          [
            ["a", "1 out of 2"],
            ["b", "2 out of 1"],
          ],
          "a",
          "2 out of 1 swaps the counts. Favorable comes first.",
          "Favorable out of possible.",
        ),
        slider(
          "scale",
          "1 favorable out of 2. Set that chance out of 10.",
          0,
          10,
          5,
          "Half of 10 is higher. Move up.",
          "Half of 10 is lower. Move down.",
          "1 out of 2 is half.",
        ),
        choice(
          "more",
          "A larger favorable count, with the same possible count, makes the chance...",
          [
            ["a", "Larger"],
            ["b", "Smaller"],
          ],
          "a",
          "More favorable outcomes, same total, is a larger chance.",
          "More favorable, larger chance.",
        ),
        slider(
          "eight",
          "4 favorable out of 8. Set how many that is out of 10.",
          0,
          10,
          5,
          "4 out of 8 is half of 10. Move up.",
          "4 out of 8 is not more than half. Move down.",
          "4 out of 8 matches half.",
        ),
        choice(
          "compares",
          "Chance compares favorable outcomes with...",
          [
            ["a", "All possible outcomes"],
            ["b", "Only the favorable ones"],
          ],
          "a",
          "Favorable alone has no total. Chance needs the possible count too.",
          "Favorable out of possible.",
        ),
      ]),
      lesson("Favorable out of possible", "The chance is the favorable count out of the possible count.", [
        slider(
          "red",
          "The bag has 8 chips, and 3 are blue. Set how many are red.",
          0,
          10,
          5,
          "Red is the rest of the bag. Move up.",
          "Red is not the whole bag. Move down.",
          "Red is possible minus blue.",
        ),
        choice(
          "frac",
          "Favorable 1, possible 4. The chance is...",
          [
            ["a", "1 out of 4"],
            ["b", "4 out of 1"],
            ["c", "1 out of 3"],
          ],
          "a",
          "4 out of 1 swaps them. 1 out of 3 drops a possible outcome.",
          "Favorable out of possible.",
        ),
        slider(
          "not",
          "9 chips, 4 red. Set how many are not red.",
          0,
          10,
          5,
          "The rest of the bag is larger. Move up.",
          "The rest is smaller than that. Move down.",
          "Not red is the rest of the chips.",
        ),
        choice(
          "forgot",
          "You forgot the chips that are not favorable. The chance looks...",
          [
            ["a", "Too large"],
            ["b", "Too small"],
          ],
          "a",
          "Dropping the other chips shrinks the possible count, so the chance looks larger.",
          "The missing chips were part of the total.",
        ),
        choice(
          "which",
          "2 of 5 chips are red. The chance of red is...",
          [
            ["a", "2 out of 5"],
            ["b", "2 out of 3"],
            ["c", "5 out of 2"],
          ],
          "a",
          "2 out of 3 drops the other chips. 5 out of 2 swaps the counts.",
          "Red out of all the chips.",
        ),
      ]),
      lesson("At least one", "At least one is a bigger event than exactly one.", [
        choice(
          "exact",
          "Two tosses. Exactly one head means...",
          [
            ["a", "HT or TH"],
            ["b", "HH, HT, or TH"],
          ],
          "a",
          "HH is both heads, not exactly one. Exactly one is HT or TH.",
          "Exactly one leaves both heads out.",
        ),
        choice(
          "least",
          "At least one head means...",
          [
            ["a", "HH, HT, or TH"],
            ["b", "Only HT"],
          ],
          "a",
          "Only HT drops TH and HH. At least one keeps every listing with a head.",
          "At least one is the larger event.",
        ),
        slider(
          "three",
          "Out of HH, HT, TH, and TT, at least one head covers how many?",
          0,
          10,
          3,
          "TT is the one listing with no head. Move up.",
          "You counted TT. Move down.",
          "Three listings have a head.",
        ),
        slider(
          "two",
          "Exactly one head covers how many of those four listings?",
          0,
          10,
          2,
          "HT and TH are the listings. Move up.",
          "HH is both heads, not exactly one. Move down.",
          "Two listings have exactly one head.",
        ),
        choice(
          "why",
          "At least one is larger than exactly one because...",
          [
            ["a", "It also counts both heads"],
            ["b", "It counts fewer outcomes"],
          ],
          "a",
          "Both heads is extra, so at least one is the bigger event.",
          "At least one includes both heads.",
        ),
      ]),
    ],
  ),
  skill(
    "sure-and-none",
    "Sure and impossible",
    "You can tell sure from impossible.",
    "Pip can tell sure from impossible.",
    "chance",
    [
      lesson("Zero and one", "A model can be sure, unsure, or sure something will not happen.", [
        choice(
          "none",
          "An outcome that cannot happen has chance...",
          [
            ["a", "0"],
            ["b", "1"],
          ],
          "a",
          "1 would mean it must happen. Impossible is 0.",
          "Impossible is 0.",
        ),
        choice(
          "sure",
          "An outcome that must happen has chance...",
          [
            ["a", "1"],
            ["b", "0"],
          ],
          "a",
          "0 would mean it cannot happen. Sure is 1.",
          "Sure is 1.",
        ),
        slider(
          "cannot",
          "Set the chance of a result that cannot happen.",
          0,
          10,
          0,
          "Impossible is not below zero. The chance is zero.",
          "A result that cannot happen is not a positive chance. Move down.",
          "Impossible sits at zero.",
        ),
        slider(
          "must",
          "Set the chance of a result that must happen.",
          0,
          10,
          10,
          "Sure is the top of this scale. Move up.",
          "Sure is not past the top. Move down.",
          "Sure sits at the top.",
        ),
        choice(
          "one",
          "A chance of 1 means...",
          [
            ["a", "Sure"],
            ["b", "Impossible"],
          ],
          "a",
          "Impossible is 0. 1 means it must happen.",
          "1 means sure.",
        ),
      ]),
      lesson("Almost is not sure", "Almost sure still leaves a way to fail.", [
        choice(
          "nine",
          "9 out of 10 is...",
          [
            ["a", "Likely, not sure"],
            ["b", "Sure"],
          ],
          "a",
          "One way still fails. Likely is not sure.",
          "9 out of 10 can still fail.",
        ),
        choice(
          "zero",
          "0 out of 10 is...",
          [
            ["a", "Impossible"],
            ["b", "Unlikely but possible"],
          ],
          "a",
          "Unlikely still has a way to happen. 0 out of 10 has none.",
          "None means impossible.",
        ),
        slider(
          "red",
          "A bag has 10 chips and 3 are blue. Set the red chance out of 10.",
          0,
          10,
          7,
          "Red is the rest of the bag. Move up.",
          "Red is not every chip. Move down.",
          "Red is the chips that are not blue.",
        ),
        choice(
          "almost",
          "Almost sure still leaves...",
          [
            ["a", "A way to fail"],
            ["b", "No way to fail"],
          ],
          "a",
          "No way to fail is sure. Almost sure still has a miss.",
          "Almost is not sure.",
        ),
        choice(
          "which",
          "Which can you call sure?",
          [
            ["a", "10 out of 10"],
            ["b", "9 out of 10"],
            ["c", "1 out of 10"],
          ],
          "a",
          "9 out of 10 can fail. 1 out of 10 is unlikely. Sure needs every outcome.",
          "Every outcome, or it is not sure.",
        ),
      ]),
    ],
  ),
  skill(
    "the-other-way",
    "The other way",
    "You can find the chance of not happening.",
    "Pip can take the other way.",
    "chance",
    [
      lesson("Not happening", "The chance of the other result is what remains.", [
        choice(
          "left",
          "The chance of red is 1 out of 4. The chance of not red is...",
          [
            ["a", "3 out of 4"],
            ["b", "1 out of 4"],
          ],
          "a",
          "1 out of 4 is red again. Not red is the rest.",
          "The rest is not red.",
        ),
        slider(
          "ten",
          "Chance of red is 3 out of 10. Set the chance of not red, out of 10.",
          0,
          10,
          7,
          "Not red is the rest. Move up.",
          "Not red is not the whole scale. Move down.",
          "Not red is what remains.",
        ),
        slider(
          "rain",
          "Chance of rain is 4 out of 10. Set the chance of no rain, out of 10.",
          0,
          10,
          6,
          "No rain is the rest. Move up.",
          "No rain is smaller than that. Move down.",
          "No rain is the other way.",
        ),
        choice(
          "uses",
          "Not happening uses...",
          [
            ["a", "The outcomes left over"],
            ["b", "The same outcomes again"],
          ],
          "a",
          "The same outcomes would repeat the first chance. The other way is the rest.",
          "The leftover outcomes.",
        ),
        choice(
          "sure",
          "If red is sure, not red is...",
          [
            ["a", "Impossible"],
            ["b", "Also sure"],
          ],
          "a",
          "Both cannot be sure. If red must happen, not red cannot.",
          "Sure one way, impossible the other.",
        ),
      ]),
      lesson("The miss", "The stated event may be the one you do not want.", [
        choice(
          "want",
          "You want a miss. The stated chance is a hit, 2 out of 5. You need...",
          [
            ["a", "3 out of 5"],
            ["b", "2 out of 5"],
          ],
          "a",
          "2 out of 5 is the hit. A miss is the rest.",
          "Flip to the event you want.",
        ),
        slider(
          "hits",
          "Hits are 7 out of 10. Set the miss chance out of 10.",
          0,
          10,
          3,
          "Misses are the rest. Move up.",
          "Misses are fewer than that. Move down.",
          "The miss is the other way from the hit.",
        ),
        choice(
          "should",
          "The prompt names the event you do not want. You should...",
          [
            ["a", "Take the other way"],
            ["b", "Copy the stated chance"],
          ],
          "a",
          "Copying keeps the event you do not want.",
          "Take what remains.",
        ),
        slider(
          "five",
          "The unwanted event is 1 out of 5. Set its complement out of 5.",
          0,
          10,
          4,
          "The complement is the rest of 5. Move up.",
          "The complement is smaller than that. Move down.",
          "One unwanted, four the other way.",
        ),
        choice(
          "small",
          "A hit chance of 9 out of 10. The miss chance is...",
          [
            ["a", "1 out of 10"],
            ["b", "9 out of 10"],
            ["c", "0"],
          ],
          "a",
          "9 out of 10 is the hit again. 0 would mean a miss cannot happen.",
          "One miss remains.",
        ),
      ]),
    ],
  ),
  skill(
    "more-likely",
    "More likely",
    "You can tell which chance is larger.",
    "Pip can pick the more likely result.",
    "chance",
    [
      lesson("Same total", "Picking the more likely result is how a model chooses.", [
        choice(
          "three",
          "3 out of 4, or 1 out of 4. Which is more likely?",
          [
            ["a", "3 out of 4"],
            ["b", "1 out of 4"],
          ],
          "a",
          "The totals match. 3 favorable beats 1.",
          "Same total, larger favorable count.",
        ),
        choice(
          "four",
          "2 out of 5, or 4 out of 5. Which is more likely?",
          [
            ["a", "4 out of 5"],
            ["b", "2 out of 5"],
          ],
          "a",
          "The totals match. 4 favorable beats 2.",
          "The larger favorable count wins.",
        ),
        choice(
          "zero",
          "0 out of 4, or 2 out of 4. Which is more likely?",
          [
            ["a", "2 out of 4"],
            ["b", "0 out of 4"],
          ],
          "a",
          "0 cannot happen. 2 out of 4 still can.",
          "A real chance beats none.",
        ),
        choice(
          "means",
          "More likely means...",
          [
            ["a", "The larger chance"],
            ["b", "The larger possible count"],
          ],
          "a",
          "A larger possible count can make a chance smaller. Compare the chances.",
          "Larger chance, more likely.",
        ),
        choice(
          "same",
          "Same possible count. You compare...",
          [
            ["a", "The favorable counts"],
            ["b", "The names of the bags"],
          ],
          "a",
          "Names do not change the chance. The favorable counts do.",
          "Compare the favorable counts.",
        ),
      ]),
      lesson("Different totals", "A bigger bag is not automatically more likely.", [
        choice(
          "half",
          "1 out of 2, or 1 out of 6. Which is more likely?",
          [
            ["a", "1 out of 2"],
            ["b", "1 out of 6"],
          ],
          "a",
          "The favorable counts match. The smaller total is the larger chance.",
          "1 out of 2 is the larger chance.",
        ),
        slider(
          "ten",
          "Bag A: 2 red out of 4. Set A's red chance out of 10.",
          0,
          10,
          5,
          "2 out of 4 is half of 10. Move up.",
          "2 out of 4 is not more than half. Move down.",
          "2 out of 4 is half.",
        ),
        choice(
          "six",
          "3 out of 6, or 1 out of 6. Which is more likely?",
          [
            ["a", "3 out of 6"],
            ["b", "1 out of 6"],
          ],
          "a",
          "The totals match here. 3 favorable beats 1.",
          "Same total, more favorable.",
        ),
        choice(
          "compare",
          "A bigger bag is not automatically more likely. You compare...",
          [
            ["a", "Favorable divided by possible"],
            ["b", "Only the bag size"],
          ],
          "a",
          "Bag size alone ignores how many are favorable.",
          "Compare the fractions.",
        ),
        choice(
          "two",
          "2 out of 3, or 3 out of 6. Which is more likely?",
          [
            ["a", "2 out of 3"],
            ["b", "3 out of 6"],
          ],
          "a",
          "3 out of 6 is half. 2 out of 3 is more than half.",
          "2 out of 3 is the larger chance.",
        ),
      ]),
      lesson("Bigger count", "A bigger favorable count can still be the smaller chance.", [
        choice(
          "trap",
          "3 out of 4, or 5 out of 8. Which is more likely?",
          [
            ["a", "3 out of 4"],
            ["b", "5 out of 8"],
          ],
          "a",
          "5 is the bigger count, but 5 out of 8 is the smaller chance.",
          "3 out of 4 wins.",
        ),
        choice(
          "why",
          "Why does 5 out of 8 lose?",
          [
            ["a", "Its possible count grew faster than its favorable count"],
            ["b", "5 is smaller than 3"],
          ],
          "a",
          "5 is larger than 3. The total grew more than the favorable count.",
          "The fraction shrank.",
        ),
        slider(
          "eighths",
          "3 out of 4 is how many out of 8?",
          0,
          10,
          6,
          "3 out of 4 is more than half of 8. Move up.",
          "3 out of 4 is not that many eighths. Move down.",
          "6 out of 8 matches 3 out of 4.",
        ),
        choice(
          "third",
          "1 out of 3, or 3 out of 10. Which is more likely?",
          [
            ["a", "1 out of 3"],
            ["b", "3 out of 10"],
          ],
          "a",
          "3 is the bigger count. 3 out of 10 is still the smaller chance.",
          "1 out of 3 wins.",
        ),
        choice(
          "winner",
          "You compare chances, not raw counts. The winner is...",
          [
            ["a", "The larger fraction"],
            ["b", "The larger favorable count"],
          ],
          "a",
          "The larger favorable count can sit in a larger total and lose.",
          "The larger fraction wins.",
        ),
      ]),
    ],
  ),
  skill(
    "balance-point",
    "Balance point",
    "You can find the mean.",
    "Pip can find the balance point.",
    "chance",
    [
      lesson("A level set", "An average is the balance point of a batch of scores.", [
        choice(
          "level",
          "The numbers 4, 4, and 4 balance at...",
          [
            ["a", "4"],
            ["b", "12"],
          ],
          "a",
          "12 adds them and forgets to share. The balance is 4.",
          "A level set balances at the repeated number.",
        ),
        slider(
          "mix",
          "The numbers are 2, 3, and 7. Set the balance point.",
          0,
          10,
          4,
          "Share the total across three numbers. Move up.",
          "The balance is lower than that. Move down.",
          "The mean is the shared total.",
        ),
        slider(
          "pull",
          "The numbers are 1, 1, and 10. Set the balance point.",
          0,
          10,
          4,
          "The 10 pulls the balance up. Move up.",
          "The balance is not as high as the 10. Move down.",
          "The mean sits between the cluster and the 10.",
        ),
        choice(
          "name",
          "The balance point is the...",
          [
            ["a", "Mean"],
            ["b", "Largest number"],
          ],
          "a",
          "The largest number is one score. The mean balances all of them.",
          "The balance point is the mean.",
        ),
        choice(
          "repeat",
          "A level set balances at...",
          [
            ["a", "The repeated number"],
            ["b", "Zero"],
          ],
          "a",
          "Zero would ignore the scores. A level set sits on its own number.",
          "The repeated number is the mean.",
        ),
      ]),
      lesson("Not the middle", "The mean is the balance, not always the middle item.", [
        choice(
          "list",
          "The list is 1, 2, 9. The middle item is 2. The mean is...",
          [
            ["a", "4"],
            ["b", "2"],
            ["c", "9"],
          ],
          "a",
          "2 is the middle item. 9 is the large score. The mean balances all three.",
          "The mean is not the middle item.",
        ),
        slider(
          "mean",
          "The numbers are 1, 2, and 9. Set the mean.",
          0,
          10,
          4,
          "Share the total across three scores. Move up.",
          "The mean is lower than the 9. Move down.",
          "The mean balances the three scores.",
        ),
        choice(
          "differ",
          "The middle item and the mean...",
          [
            ["a", "Can differ"],
            ["b", "Are always the same number"],
          ],
          "a",
          "A lopsided list pulls the mean off the middle item.",
          "Mean and middle can differ.",
        ),
        slider(
          "zeros",
          "The numbers are 0, 0, and 9. Set the mean.",
          0,
          10,
          3,
          "The 9 is shared across three scores. Move up.",
          "The mean is lower than the 9. Move down.",
          "The mean is the shared 9.",
        ),
        choice(
          "want",
          "You want the balance, so you compute...",
          [
            ["a", "The mean"],
            ["b", "The middle item only"],
          ],
          "a",
          "The middle item ignores how far the ends sit. The mean balances them.",
          "The balance is the mean.",
        ),
      ]),
      lesson("One outlier", "An average can hide an outlier that the middle item ignores.", [
        choice(
          "moved",
          "The numbers are 2, 2, 2, and 10. The middle is 2. The mean is...",
          [
            ["a", "4"],
            ["b", "2"],
            ["c", "10"],
          ],
          "a",
          "2 is the middle. 10 is the outlier. The mean is pulled up between them.",
          "The outlier moved the mean.",
        ),
        slider(
          "set",
          "Set the mean of 2, 2, 2, and 10.",
          0,
          10,
          4,
          "Share the total across four scores. Move up.",
          "The mean is lower than the 10. Move down.",
          "The mean sits above the middle.",
        ),
        choice(
          "which",
          "The outlier moved...",
          [
            ["a", "The mean, and left the middle at 2"],
            ["b", "The middle, and left the mean at 2"],
          ],
          "a",
          "The middle stays 2. The mean is the one that moved.",
          "The outlier pulls the mean.",
        ),
        choice(
          "hide",
          "A model that reports only the mean can hide...",
          [
            ["a", "One score far from the rest"],
            ["b", "Nothing, the mean shows every score"],
          ],
          "a",
          "The mean is one number. It does not show that one score sits far away.",
          "The mean can hide an outlier.",
        ),
        choice(
          "stays",
          "Which summary stays at 2?",
          [
            ["a", "The middle"],
            ["b", "The mean"],
          ],
          "a",
          "The mean moved up. The middle of 2, 2, 2, 10 stays at 2.",
          "The middle ignores the outlier.",
        ),
      ]),
    ],
  ),
  skill(
    "spread",
    "Spread",
    "You can tell a tight batch from a wide one.",
    "Pip can compare spread.",
    "chance",
    [
      lesson("Same mean", "Two batches can share a mean and still differ in spread.", [
        choice(
          "match",
          "Batch A is 4, 4, 4. Batch B is 0, 4, 8. The means...",
          [
            ["a", "Match"],
            ["b", "Differ"],
          ],
          "a",
          "B is spread out, but 0, 4, and 8 still balance at 4.",
          "Same mean, different spread.",
        ),
        slider(
          "odd",
          "Set the mean of 1, 2, and 9.",
          0,
          10,
          4,
          "Share the total across three scores. Move up.",
          "The mean is lower than the 9. Move down.",
          "The wide batch still has a mean.",
        ),
        choice(
          "level",
          "1, 2, and 9 versus 4, 4, and 4. The means...",
          [
            ["a", "Match"],
            ["b", "Differ"],
          ],
          "a",
          "The shapes differ. Both batches balance at 4.",
          "The means match.",
        ),
        choice(
          "wide",
          "The batch 1, 2, 9 is...",
          [
            ["a", "More spread out"],
            ["b", "The tighter batch"],
          ],
          "a",
          "4, 4, 4 sits in one place. 1, 2, 9 travels.",
          "Same mean, wider spread.",
        ),
        choice(
          "not",
          "Same mean does not mean...",
          [
            ["a", "Same spread"],
            ["b", "The batches are unrelated"],
          ],
          "a",
          "The means match, so the batches are related. The spreads can still differ.",
          "Mean and spread are different facts.",
        ),
      ]),
      lesson("More predictable", "A tighter batch is the more predictable one.", [
        choice(
          "which",
          "Batch A is 5, 5, 5. Batch B is 1, 5, 9. Which is more predictable?",
          [
            ["a", "A"],
            ["b", "B, because the numbers travel farther"],
          ],
          "a",
          "Traveling farther is less predictable. The tight batch stays put.",
          "The tighter batch is more predictable.",
        ),
        choice(
          "means",
          "Predictable means...",
          [
            ["a", "The scores stay near the mean"],
            ["b", "The mean is larger"],
          ],
          "a",
          "A larger mean can still be wild. Predictable means the scores stay close.",
          "Close to the mean, more predictable.",
        ),
        slider(
          "wild",
          "Batch 3, 3, and 9. Set the mean.",
          0,
          10,
          5,
          "Share the total across three scores. Move up.",
          "The mean is lower than the 9. Move down.",
          "The outlier pulls the mean up.",
        ),
        choice(
          "even",
          "The tighter set is more predictable even when...",
          [
            ["a", "The means match"],
            ["b", "Only when its mean is larger"],
          ],
          "a",
          "A larger mean is not what makes a forecast steady. Tightness is.",
          "Same mean, tighter set, steadier forecast.",
        ),
        choice(
          "trust",
          "You would trust a forecast more from...",
          [
            ["a", "The tighter batch"],
            ["b", "The batch with the wild outlier"],
          ],
          "a",
          "The outlier makes the next score harder to guess.",
          "Tight scores, steadier forecast.",
        ),
      ]),
    ],
  ),
  skill(
    "new-clue",
    "A new clue",
    "You can update a count with a clue.",
    "Pip can update a belief.",
    "chance",
    [
      lesson(
        "Update the count",
        "A new clue updates the count a model uses to pick.",
        [
          choice(
            "before",
            "Bag A has 4 red and 1 blue. Bag B has 1 red and 4 blue. A red draw is more likely from...",
            [
              ["a", "Bag A"],
              ["b", "Bag B"],
            ],
            "a",
            "Bag B has more blue. Red is more likely from the bag with more red.",
            "Bag A holds more red.",
          ),
          slider(
            "count",
            "Bag A has 5 chips and 1 is blue. Set the red count.",
            0,
            10,
            4,
            "Red is the rest of the bag. Move up.",
            "Red is not every chip. Move down.",
            "Four chips are red.",
          ),
          choice(
            "red",
            "You draw a red chip. Which bag becomes more likely?",
            [
              ["a", "Bag A"],
              ["b", "Bag B"],
            ],
            "a",
            "A red chip fits Bag A better. Bag B is mostly blue.",
            "The red clue raises Bag A.",
          ),
          choice(
            "raises",
            "A clue that matches Bag A better...",
            [
              ["a", "Raises Bag A's chance"],
              ["b", "Leaves the chances where they started"],
            ],
            "a",
            "A matching clue changes the count. It does not leave the chances put.",
            "A matching clue updates the chance.",
          ),
          choice(
            "blue",
            "New clue: the chip is blue. Now the more likely bag is...",
            [
              ["a", "Bag B"],
              ["b", "Bag A"],
            ],
            "a",
            "Blue fits the bag with more blue. That is Bag B.",
            "The blue clue flips the pick.",
          ),
          choice(
            "same",
            "Both bags have 5 chips. The clue is only that you drew a chip. The odds...",
            [
              ["a", "Stay as they were"],
              ["b", "Jump to Bag A"],
            ],
            "a",
            "Both bags explain a chip equally. The clue adds no new count.",
            "A clue both bags share does not move the odds.",
          ),
          slider(
            "add",
            "Bag A started with 1 red out of 5. You add 3 red. Set the new red count.",
            0,
            10,
            4,
            "Add the new red chips to the old count. Move up.",
            "The new count is smaller than that. Move down.",
            "The clue updated the count.",
          ),
          choice(
            "pick",
            "After a red clue, Pip picks...",
            [
              ["a", "The bag with more red"],
              ["b", "The bag with more blue"],
            ],
            "a",
            "A red clue supports the bag that holds more red.",
            "Pip picks the bag the clue supports.",
          ),
        ],
        true,
      ),
    ],
  ),
];
