import { choice, drag, lesson, skill, slider, type SkillDraft } from "./helpers";

export const spaceSkills: SkillDraft[] = [
  skill(
    "coordinate-plane",
    "Coordinate plane",
    "You can place a point on the plane.",
    "Pip can land on a point.",
    "space",
    [
      lesson("Place a point", "A model stores a position as two numbers.", [
        drag(
          "land",
          "Drag Pip onto the mark.",
          [1, 1],
          [7, 3],
          "The mark sits up and to the right of the tail.",
          "The aim is right. Stretch or shorten until the tip meets the mark.",
          "The tip is on the mark.",
        ),
        choice(
          "signs",
          "The mark sits up and to the right. That means...",
          [
            ["a", "x and y are both positive"],
            ["b", "x is positive and y is negative"],
          ],
          "a",
          "Up means y is positive. Right means x is positive.",
          "Both steps are positive.",
        ),
        slider(
          "x",
          "The mark is 2 right of x = 5. Set x.",
          0,
          10,
          7,
          "Start at 5 and step right twice. Move higher.",
          "Two steps right of 5 is not that far. Move lower.",
          "x is 5 plus 2.",
        ),
        slider(
          "y",
          "The same mark is 4 up from y = 1. Set y.",
          0,
          10,
          5,
          "Start at 1 and climb 4. Move higher.",
          "Four steps up from 1 is less than that. Move lower.",
          "y is 1 plus 4.",
        ),
        drag(
          "quiet",
          "From (2, 1), go 4 right and 3 up.",
          [2, 1],
          [6, 4],
          "4 right and 3 up leaves the horizontal line.",
          "The direction matches. The run is 4 and the rise is 3.",
          "The tip is the tail plus that move.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Read a point", "Swapping the two numbers sends a model to the wrong place.", [
        choice(
          "origin",
          "Where is the point (0, 0)?",
          [
            ["a", "Where the axes cross"],
            ["b", "High on the vertical axis"],
          ],
          "a",
          "Both numbers are zero, so the point sits where the axes cross.",
          "The origin is the crossing of the axes.",
        ),
        choice(
          "swap",
          "Which pair is 2 right and 5 up?",
          [
            ["a", "(2, 5)"],
            ["b", "(5, 2)"],
          ],
          "a",
          "(5, 2) is 5 right and 2 up. Right is the first number.",
          "Right is the first number. Up is the second.",
        ),
        slider(
          "read-x",
          "A point moves from x = 2 to x = 8. How many steps right?",
          0,
          10,
          6,
          "The ends are farther apart. Move higher.",
          "The gap is the difference, not the larger end. Move lower.",
          "The mark is 6 steps right of where it started.",
        ),
        slider(
          "read-y",
          "That point's y went from 1 to 5. How many steps up?",
          0,
          10,
          4,
          "The rise is larger than that. Move higher.",
          "The rise is smaller than that. Move lower.",
          "The mark climbed 4.",
        ),
        drag(
          "place",
          "From the tail at (1, 2), go 5 right and 1 up.",
          [1, 2],
          [6, 3],
          "The point sits up and to the right of the tail.",
          "The run is 5 and the rise is 1.",
          "The tip names the point.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "quadrants",
    "Quadrants",
    "You can name the quadrant of a point.",
    "Pip knows which side of the plane it is on.",
    "space",
    [
      lesson("Name the side", "Signs tell a model which direction a value points.", [
        choice(
          "q1",
          "x is positive and y is positive. Where is the point?",
          [
            ["a", "Upper right"],
            ["b", "Lower left"],
          ],
          "a",
          "Positive x is right. Positive y is up. That corner is the upper right.",
          "Both positive means the upper right.",
        ),
        choice(
          "q2",
          "x is negative and y is positive. Where is the point?",
          [
            ["a", "Upper left"],
            ["b", "Lower right"],
          ],
          "a",
          "Negative x is left. Positive y is still up.",
          "Left and up is the upper left.",
        ),
        slider(
          "neg-x",
          "The point is 3 left of the origin. Set x.",
          -5,
          5,
          -3,
          "Three left is not farther than that. Move toward zero.",
          "Left of the origin is negative. Move below zero.",
          "Three left is a negative x.",
        ),
        choice(
          "q3",
          "Both numbers are negative. Where is the point?",
          [
            ["a", "Lower left"],
            ["b", "Upper left"],
          ],
          "a",
          "Negative y is down. Negative x alone would stay up.",
          "Both negative means the lower left.",
        ),
        choice(
          "trap",
          "Which point is in the lower right?",
          [
            ["a", "(4, -1)"],
            ["b", "(-4, -1)"],
            ["c", "(4, 1)"],
          ],
          "a",
          "Lower right needs positive x and negative y. (-4, -1) is left. (4, 1) is up.",
          "Right and down is the lower right.",
        ),
      ]),
    ],
  ),
  skill(
    "axis-distance",
    "Axis distance",
    "You can measure distance along one axis.",
    "Pip can measure a straight gap.",
    "space",
    [
      lesson("Measure one axis", "Error along one axis is the simplest loss.", [
        choice(
          "gap",
          "From x = 2 to x = 5, the gap along the axis is...",
          [
            ["a", "3"],
            ["b", "7"],
            ["c", "2"],
          ],
          "a",
          "7 adds the ends. 2 is only the start. Subtract.",
          "The horizontal gap is 3.",
        ),
        choice(
          "which",
          "Points (4, 1) and (4, 6) share x. The gap is...",
          [
            ["a", "Vertical"],
            ["b", "Horizontal"],
          ],
          "a",
          "x does not change. The whole gap is in y.",
          "Same x means the gap is vertical.",
        ),
        slider(
          "y-gap",
          "From y = 2 to y = 9, how far up the axis?",
          0,
          10,
          7,
          "The ends are farther apart. Move higher.",
          "The gap is the difference, not the larger end. Move lower.",
          "The vertical gap is 7.",
        ),
        drag(
          "flat",
          "From (2, 3), move 6 right and stay on that line.",
          [2, 3],
          [8, 3],
          "Stay on the horizontal line. The move is to the right.",
          "The direction is right. The gap is 6.",
          "You moved along one axis.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "either",
          "From x = 1 to x = 4 is a gap of 3. From x = 4 back to x = 1 is...",
          [
            ["a", "Also 3"],
            ["b", "A different distance, because it points left"],
            ["c", "0"],
          ],
          "a",
          "Direction can flip. The size of the gap stays 3.",
          "Distance is the size of the gap, either way.",
        ),
      ]),
    ],
  ),
  skill(
    "closer-point",
    "Closer point",
    "You can tell which point is closer.",
    "Pip can pick the nearer point.",
    "space",
    [
      lesson("Pick the nearer point", "Nearest match is the first idea in similarity.", [
        choice(
          "near-x",
          "The target is at x = 1. Which point is closer?",
          [
            ["a", "x = 2"],
            ["b", "x = 9"],
          ],
          "a",
          "x = 2 is one step away. x = 9 is much farther.",
          "The smaller gap is the closer point.",
        ),
        choice(
          "near-y",
          "The target is at y = 8. Which point is closer?",
          [
            ["a", "y = 7"],
            ["b", "y = 1"],
          ],
          "a",
          "y = 7 is one step from 8. y = 1 is far down.",
          "Stay with the smaller vertical gap.",
        ),
        slider(
          "dist",
          "How far is x = 3 from the target at x = 8?",
          0,
          10,
          5,
          "The gap is larger than that. Move higher.",
          "The gap is smaller than that. Move lower.",
          "The gap is 5.",
        ),
        choice(
          "pair",
          "The target is (5, 5). Which point is closer?",
          [
            ["a", "(6, 5)"],
            ["b", "(5, 1)"],
          ],
          "a",
          "(6, 5) is one step right. (5, 1) is four steps down.",
          "One step beats four steps.",
        ),
        choice(
          "tie",
          "Two points sit the same distance from the target. They are...",
          [
            ["a", "Equally close"],
            ["b", "The one with the larger coordinates"],
            ["c", "The left one, always"],
          ],
          "a",
          "A larger coordinate is not a smaller gap. Equal gaps tie.",
          "Equal gaps mean a tie.",
        ),
      ]),
      lesson("Compare gaps", "A model picks a neighbor by the smaller gap.", [
        choice(
          "origin",
          "The target is (0, 0). Which point is closer?",
          [
            ["a", "(1, 0)"],
            ["b", "(3, 4)"],
          ],
          "a",
          "(1, 0) is one step away. (3, 4) is far on both axes.",
          "The short step is the neighbor.",
        ),
        slider(
          "one",
          "How many steps from (5, 5) to (8, 5) along x?",
          0,
          10,
          3,
          "Only x changes, and the change is larger. Move higher.",
          "Only x changes, and the change is smaller. Move lower.",
          "The horizontal gap is 3.",
        ),
        choice(
          "axes",
          "Point A is 1 step away. Point B is 4 steps away on both axes. Which is closer?",
          [
            ["a", "A"],
            ["b", "B, because it moves on two axes"],
          ],
          "a",
          "Moving on two axes can make a longer trip. Compare the gaps.",
          "One step beats four steps.",
        ),
        slider(
          "zero",
          "What is the distance from y = 4 to y = 4?",
          0,
          10,
          0,
          "A distance is not below zero. This gap is zero.",
          "Same y means there is no gap. Move down.",
          "A point is zero away from itself.",
        ),
        drag(
          "near",
          "The nearer point is 1 right of (5, 5), on the same line.",
          [5, 5],
          [6, 5],
          "The nearer point stays on the horizontal line.",
          "The aim is right. The gap is one step.",
          "One step beats a long step.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "arrow-parts",
    "Arrow parts",
    "You can point an arrow from tail to tip.",
    "Pip can aim an arrow.",
    "space",
    [
      lesson("Tail and tip", "A vector is an arrow a model can add and scale.", [
        choice(
          "tail",
          "The tail of an arrow is which end?",
          [
            ["a", "Where it starts"],
            ["b", "Where it points"],
          ],
          "a",
          "The tail stays put. The tip is where it points.",
          "The tail is the start.",
        ),
        choice(
          "tip",
          "The tip is which end?",
          [
            ["a", "Where it points"],
            ["b", "The middle of the shaft"],
          ],
          "a",
          "The tip is the end you move. The middle is not a new place.",
          "The tip names the end of the move.",
        ),
        drag(
          "aim",
          "The tail stays. Drag Pip onto the mark.",
          [2, 2],
          [8, 5],
          "The mark is up and to the right of the tail.",
          "The direction is right. Match the length to the mark.",
          "Tail and tip tell the whole move.",
        ),
        slider(
          "rise",
          "From y = 2 to y = 7, how far does the tip rise?",
          0,
          10,
          5,
          "The tip rises more than that. Move higher.",
          "The tip rises less than that. Move lower.",
          "The rise is the change in y.",
        ),
        choice(
          "move",
          "Tail and tip together describe what?",
          [
            ["a", "A move with size and direction"],
            ["b", "Only where the tail sits"],
            ["c", "Only the length"],
          ],
          "a",
          "The tail alone is a place. Length alone has no aim. Together they are a move.",
          "An arrow is a move with size and direction.",
        ),
      ]),
      lesson("Read the move", "The move stays the same when tail and tip shift together.", [
        drag(
          "flat",
          "Leave the tail fixed. Drag Pip onto the mark.",
          [1, 4],
          [6, 4],
          "The mark is straight to the right.",
          "The direction is right. The mark is 5 units away.",
          "The tail stayed. The tip moved.",
        ),
        choice(
          "shift",
          "Tail and tip both shift by the same amount. The arrow...",
          [
            ["a", "Keeps the same move"],
            ["b", "Points a new way"],
          ],
          "a",
          "A shared shift moves the whole arrow. The move itself stays.",
          "Equal arrows can start in different places.",
        ),
        slider(
          "run",
          "Tip x is 9 and tail x is 2. How far right is the move?",
          0,
          10,
          7,
          "Subtract the tail from the tip. Move higher.",
          "The run is smaller than that. Move lower.",
          "The run is tip x minus tail x.",
        ),
        choice(
          "left",
          "The tip is left of the tail. The arrow points which way?",
          [
            ["a", "Left"],
            ["b", "Right"],
          ],
          "a",
          "The tip leads. If the tip is left, the arrow points left.",
          "Follow the tip, not the tail.",
        ),
        drag(
          "up",
          "Point straight up. The rise is 5. The tail is at (4, 1).",
          [4, 1],
          [4, 6],
          "Straight up. The tip shares the tail's x.",
          "The aim is up. The rise is 5.",
          "Same x means a vertical move.",
          undefined,
          undefined,
          false,
        ),
      ]),
    ],
  ),
  skill(
    "equal-arrows",
    "Equal arrows",
    "You can spot arrows with the same displacement.",
    "Pip treats equal arrows as the same move.",
    "space",
    [
      lesson("Same displacement", "Equal vectors are the same feature, wherever they start.", [
        choice(
          "same",
          "Two arrows each go 3 right from different tails. They are...",
          [
            ["a", "The same move"],
            ["b", "Different because the tails differ"],
          ],
          "a",
          "The tails can sit anywhere. The shared move is what matches.",
          "Equal arrows share a displacement.",
        ),
        slider(
          "rise",
          "Both arrows rise the same amount. One rises from 1 to 5. Set the shared rise.",
          0,
          10,
          4,
          "The shared rise is the change, and it is larger. Move up.",
          "The shared rise is the change, and it is smaller. Move down.",
          "Equal arrows share this rise.",
        ),
        drag(
          "copy",
          "Match the move of 3 right and 2 up. Start at (1, 1).",
          [1, 1],
          [4, 3],
          "The move goes right and a little up.",
          "The direction matches. The run is 3 and the rise is 2.",
          "That displacement matches the other arrow.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "feature",
          "A model treats equal arrows as what?",
          [
            ["a", "The same feature"],
            ["b", "Different features, because they start apart"],
          ],
          "a",
          "The start can change. The move is the feature.",
          "Same displacement, same feature.",
        ),
        choice(
          "unequal",
          "Arrow A is (+2, +0). Arrow B is (+2, +1). Are they equal?",
          [
            ["a", "No"],
            ["b", "Yes, they share the run"],
          ],
          "a",
          "They share the run, but B also rises. The moves differ.",
          "One extra step up makes a different arrow.",
        ),
      ]),
    ],
  ),
  skill(
    "add-arrows",
    "Add arrows",
    "You can add arrows tip to tail.",
    "Pip can chain two moves.",
    "space",
    [
      lesson("Tip to tail", "Adding vectors is how layers combine signals.", [
        choice(
          "place",
          "To add two arrows, where do you put the second tail?",
          [
            ["a", "On the first tip"],
            ["b", "Back at the origin only"],
          ],
          "a",
          "The second move starts where the first move ends.",
          "Tip to tail chains the moves.",
        ),
        drag(
          "first",
          "Draw the first move: 3 right from (1, 2).",
          [1, 2],
          [4, 2],
          "The first move is straight right.",
          "The direction is right. Stop 3 units out.",
          "The first arrow is drawn.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "sum-x",
          "Start at x = 1, go 3 right, then 2 more right. Where does x land?",
          0,
          10,
          6,
          "1, then 3, then 2 more. Move higher.",
          "That landing is past the chain. Move lower.",
          "The chained x is 6.",
        ),
        choice(
          "order",
          "Adding the arrows in the other order lands where?",
          [
            ["a", "On the same point"],
            ["b", "On a different point"],
          ],
          "a",
          "The two paths form a parallelogram and meet.",
          "Order does not change the sum.",
        ),
        drag(
          "sum",
          "The combined move is 4 right and 2 up from (1, 1).",
          [1, 1],
          [5, 3],
          "The sum goes right and a little up.",
          "The direction matches. The run is 4 and the rise is 2.",
          "One arrow can stand for the chain.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Combine moves", "A residual path adds a second arrow onto the first.", [
        slider(
          "cancel-part",
          "3 right plus 1 left is how many right?",
          0,
          10,
          2,
          "Left takes one step back from 3. Move higher.",
          "You gave back more than one step. Move lower.",
          "Opposite steps shrink the sum.",
        ),
        choice(
          "zero",
          "Opposite arrows of the same length add to what?",
          [
            ["a", "No move"],
            ["b", "A longer arrow"],
            ["c", "A turn"],
          ],
          "a",
          "The second arrow walks back what the first arrow walked. It does not turn.",
          "Equal opposites sum to a zero move.",
        ),
        drag(
          "up",
          "Add a move of 4 up. The tail is at (3, 1).",
          [3, 1],
          [3, 5],
          "This move is straight up, not sideways.",
          "The aim is up. The rise is 4.",
          "You added a vertical arrow.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "ups",
          "2 up plus 5 up is how far up?",
          0,
          10,
          7,
          "Add the rises. Move higher.",
          "The rises add to less than that. Move lower.",
          "Same direction means the lengths add.",
        ),
        choice(
          "layer",
          "A layer adds two signals of the same shape by...",
          [
            ["a", "Adding matching places"],
            ["b", "Keeping only the longer signal"],
            ["c", "Averaging the directions and dropping the lengths"],
          ],
          "a",
          "The longer signal is not the sum. Each place has a partner to add.",
          "Combined signals are a sum of matching places.",
        ),
      ]),
    ],
  ),
  skill(
    "scale-arrow",
    "Scale an arrow",
    "You can make an arrow longer or shorter.",
    "Pip can stretch a move.",
    "space",
    [
      lesson("Twice as long", "A weight scales how much an input matters.", [
        choice(
          "twice",
          "Twice as long means you do what?",
          [
            ["a", "Keep the direction and double the length"],
            ["b", "Turn the arrow around"],
            ["c", "Double only the vertical part"],
          ],
          "a",
          "Scaling stretches the whole move. It does not reverse it or leave a part out.",
          "Direction stays. Length doubles.",
        ),
        slider(
          "double",
          "An arrow is 3 long. Set twice that length.",
          0,
          10,
          6,
          "Twice 3 is higher. Move up.",
          "Twice 3 is lower than that. Move down.",
          "The scaled length is 6.",
        ),
        drag(
          "stretch",
          "The short arrow runs 2 right from (2, 2). Drag twice as far.",
          [2, 2],
          [6, 2],
          "Stay on the horizontal line. Twice as far is still to the right.",
          "The direction is right. Twice the run of 2 reaches farther.",
          "Same direction, double length.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "half",
          "An arrow is 8 long. Set half of that.",
          0,
          10,
          4,
          "Half of 8 is higher. Move up.",
          "Half of 8 is lower. Move down.",
          "Half the length is 4.",
        ),
        choice(
          "weight",
          "A weight scales a signal by changing what?",
          [
            ["a", "Its length"],
            ["b", "Its direction only"],
            ["c", "The tail's place only"],
          ],
          "a",
          "The aim can stay. The tail can stay. The weight changes the length.",
          "Scaling changes length.",
        ),
      ]),
      lesson("Half as long", "A smaller weight shortens the arrow and keeps its aim.", [
        drag(
          "half-draw",
          "Full length would run 6 right from (2, 3). Stop halfway.",
          [2, 3],
          [5, 3],
          "Halfway is still straight right, not a new direction.",
          "The aim is right. Half of the 6-unit run stops sooner.",
          "Half the length keeps the direction.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "times3",
          "Length 2, times 4, is what?",
          0,
          10,
          8,
          "2 times 4 is higher. Move up.",
          "2 times 4 is lower. Move down.",
          "The scale multiplies the length.",
        ),
        choice(
          "zero",
          "Scaling by 0 leaves what?",
          [
            ["a", "No arrow"],
            ["b", "The same arrow"],
          ],
          "a",
          "A scale of 0 shrinks every step to nothing.",
          "Zero scale is a zero move.",
        ),
        slider(
          "half10",
          "Length 10, halved, is what?",
          0,
          10,
          5,
          "Half of 10 is higher. Move up.",
          "Half of 10 is lower. Move down.",
          "Half of 10 is 5.",
        ),
        choice(
          "closer",
          "Half as long keeps the direction. The tip moves...",
          [
            ["a", "Closer to the tail"],
            ["b", "Onto a new heading"],
            ["c", "Twice as far"],
          ],
          "a",
          "Shorter means the tip stops sooner on the same line.",
          "The heading stays. The tip comes in.",
        ),
      ]),
    ],
  ),
  skill(
    "arrow-length",
    "Arrow length",
    "You can tell which arrow is longer.",
    "Pip can compare lengths.",
    "space",
    [
      lesson("Which is longer", "Length is the size of a feature, not its direction.", [
        choice(
          "longer",
          "Arrow A spans 2 units. Arrow B spans 6. Which is longer?",
          [
            ["a", "B"],
            ["b", "A"],
          ],
          "a",
          "6 is a bigger move than 2.",
          "The longer arrow has the bigger length.",
        ),
        slider(
          "span",
          "How long is a flat arrow from x = 1 to x = 8?",
          0,
          10,
          7,
          "The ends are farther apart. Move higher.",
          "The ends are closer than that. Move lower.",
          "The length is the gap.",
        ),
        choice(
          "aim",
          "A longer arrow can...",
          [
            ["a", "Keep the same direction"],
            ["b", "Be forced to turn"],
          ],
          "a",
          "Length and direction are separate. You can stretch without turning.",
          "Size can change while the aim stays.",
        ),
        drag(
          "draw",
          "Draw the longer move, 5 right from (1, 4).",
          [1, 4],
          [6, 4],
          "The longer move is straight right.",
          "The direction is right. The length is 5.",
          "That arrow is the long one.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "compare",
          "Two arrows point different ways. You compare their size by...",
          [
            ["a", "Which arrow is longer"],
            ["b", "Which arrow points right"],
            ["c", "Which tail is higher"],
          ],
          "a",
          "Direction and the tail's place are not the size. Length is.",
          "Bigger length, bigger feature.",
        ),
      ]),
    ],
  ),
  skill(
    "pip-checkpoint",
    "Guide Pip",
    "You can guide Pip to a point.",
    "Pip can reach a marked point.",
    "space",
    [
      lesson(
        "Reach the mark",
        "Reaching a target is the shape of a training step.",
        [
          choice(
            "aim",
            "Pip starts at (1, 1). The mark is right and up. First you...",
            [
              ["a", "Aim toward the mark"],
              ["b", "Move left, away from the mark"],
            ],
            "a",
            "The mark has a direction from the start. Aim there.",
            "The first move points at the mark.",
          ),
          drag(
            "guide",
            "Guide Pip from (1, 1) onto the mark.",
            [1, 1],
            [6, 4],
            "The mark is up and to the right.",
            "The aim is right. Match the distance to the mark.",
            "Pip reaches the mark.",
          ),
          slider(
            "x",
            "The mark is 3 right of x = 2. Set x.",
            0,
            10,
            5,
            "Start at 2 and step right. Move higher.",
            "Three steps right of 2 is not that far. Move lower.",
            "Pip's x matches the mark.",
          ),
          slider(
            "y",
            "The mark is 2 up from y = 3. Set y.",
            0,
            10,
            5,
            "Start at 3 and climb. Move up.",
            "Two steps up from 3 is lower than that. Move down.",
            "Pip's y matches the mark.",
          ),
          choice(
            "arrow",
            "The move that reached the mark is what?",
            [
              ["a", "An arrow with length and direction"],
              ["b", "Only the name of the mark"],
            ],
            "a",
            "A name does not say how far or which way. The move does.",
            "You guided Pip with an arrow.",
          ),
          drag(
            "step",
            "From (1, 1), Pip must go 4 right and 2 up.",
            [1, 1],
            [5, 3],
            "The step goes right and up.",
            "The run is 4 and the rise is 2.",
            "That step aims at the target.",
            undefined,
            undefined,
            false,
          ),
        ],
        true,
      ),
    ],
  ),
];
