import { choice, drag, lesson, skill, slider, type SkillDraft } from "./helpers";

export const spaceSkills: SkillDraft[] = [
  skill(
    "coordinate-plane",
    "Coordinate plane",
    "You can place a point on the plane.",
    "Pip can land on a point.",
    "space",
    [
      lesson("Place a point", "A model stores a position as two numbers.", [
        drag(
          "land",
          "Drag the tip onto the mark.",
          [1, 1],
          [7, 3],
          "The mark sits up and to the right of the tail.",
          "The aim is right. Stretch or shorten until the tip meets the mark.",
          "The tip is on the mark.",
        ),
        slider(
          "x",
          "That mark is 7 units right of the origin. Set x.",
          0,
          10,
          7,
          "x counts steps to the right. Move higher.",
          "That x is past the mark. Move lower.",
          "x is the horizontal step.",
        ),
        slider(
          "y",
          "The same mark is 3 units up. Set y.",
          0,
          10,
          3,
          "y counts steps up. Move higher.",
          "That y is above the mark. Move lower.",
          "y is the vertical step.",
        ),
        drag(
          "named",
          "Drag the tip to the point at (4, 6).",
          [1, 1],
          [4, 6],
          "The point sits up and to the right.",
          "The direction is right. Match the distance to (4, 6).",
          "The tip lands on the point the pair names.",
        ),
        drag(
          "quiet",
          "Drag the tip onto the mark.",
          [2, 2],
          [8, 2],
          "The mark sits to the right of the tail.",
          "The aim is right. Stretch or shorten until the tip meets the mark.",
          "The tip is on the mark.",
        ),
      ]),
      lesson("Read a point", "Swapping the two numbers sends a model to the wrong place.", [
        drag(
          "mark",
          "Drag the tip onto the marked point.",
          [1, 1],
          [6, 4],
          "The mark sits up and to the right of the tail.",
          "The aim is right. Stretch or shorten to the mark.",
          "The tip is on the mark.",
        ),
        slider(
          "read-x",
          "What is the x of the point you reached?",
          0,
          10,
          6,
          "Count the steps right from zero. Move higher.",
          "That count goes past the mark. Move lower.",
          "The mark is 6 units right.",
        ),
        slider(
          "read-y",
          "What is the y of that point?",
          0,
          10,
          4,
          "Count the steps up. Move higher.",
          "That count is above the mark. Move lower.",
          "The mark is 4 units up.",
        ),
        choice(
          "origin",
          "Where is the point (0, 0)?",
          [
            ["a", "The origin"],
            ["b", "High on the y axis"],
          ],
          "a",
          "Both numbers are zero, so the point sits where the axes cross.",
          "The origin is the crossing of the axes.",
        ),
        choice(
          "swap",
          "Which pair is 2 right and 5 up?",
          [
            ["a", "(2, 5)"],
            ["b", "(5, 2)"],
          ],
          "a",
          "(5, 2) is 5 right and 2 up. You want the smaller x.",
          "Right is the first number. Up is the second.",
        ),
      ]),
    ],
  ),
  skill(
    "quadrants",
    "Quadrants",
    "You can name the quadrant of a point.",
    "Pip knows which side of the plane it is on.",
    "space",
    [
      lesson("Name the side", "Signs tell a model which direction a value points.", [
        choice(
          "q1",
          "x is positive and y is positive. Where is the point?",
          [
            ["a", "Upper right"],
            ["b", "Lower left"],
          ],
          "a",
          "Positive x is right. Positive y is up. That corner is the upper right.",
          "Both positive means the upper right.",
        ),
        choice(
          "q2",
          "x is negative and y is positive. Where is the point?",
          [
            ["a", "Upper left"],
            ["b", "Upper right"],
          ],
          "a",
          "Negative x is left. Positive y is still up.",
          "Left and up is the upper left.",
        ),
        slider(
          "neg-x",
          "A point in the upper left has negative x. Set x.",
          -5,
          5,
          -2,
          "That x is farther left than this point. Move toward zero.",
          "The upper left stays negative. Move left of zero.",
          "Negative x sits left of the origin.",
        ),
        choice(
          "q3",
          "Both numbers are negative. Where is the point?",
          [
            ["a", "Lower left"],
            ["b", "Upper right"],
          ],
          "a",
          "Negative x is left and negative y is down.",
          "Both negative means the lower left.",
        ),
        drag(
          "place",
          "Drag the tip onto the mark in the upper right.",
          [1, 1],
          [8, 7],
          "The mark sits up and to the right.",
          "The aim is right. Stretch or shorten until the tip meets the mark.",
          "The tip is in the upper right.",
        ),
      ]),
    ],
  ),
  skill(
    "axis-distance",
    "Axis distance",
    "You can measure distance along one axis.",
    "Pip can measure a straight gap.",
    "space",
    [
      lesson("Measure one axis", "Error along one axis is the simplest loss.", [
        slider(
          "x-gap",
          "From x = 1 to x = 6, how far along the axis?",
          0,
          10,
          5,
          "Subtract the smaller x from the larger. Move higher.",
          "The gap is smaller than that. Move lower.",
          "The horizontal gap is 5.",
        ),
        slider(
          "y-gap",
          "From y = 2 to y = 8, how far up the axis?",
          0,
          10,
          6,
          "The rise is larger than that. Move higher.",
          "The rise is smaller than that. Move lower.",
          "The vertical gap is 6.",
        ),
        choice(
          "sign",
          "Distance along an axis counts what?",
          [
            ["a", "The gap, either way"],
            ["b", "Only the larger coordinate"],
          ],
          "a",
          "A step left and a step right of the same size have the same distance.",
          "Distance is the size of the gap.",
        ),
        drag(
          "flat",
          "Drag straight right from (2, 3) to (8, 3).",
          [2, 3],
          [8, 3],
          "Stay on the horizontal line. The mark is to the right.",
          "The direction is right. The gap is 6 units.",
          "You moved along one axis.",
        ),
        slider(
          "shared-x",
          "Points (4, 1) and (4, 7) share x. What is the vertical gap?",
          0,
          10,
          6,
          "The y numbers are farther apart. Move higher.",
          "The y numbers are closer than that. Move lower.",
          "Same x means the whole gap is vertical.",
        ),
      ]),
    ],
  ),
  skill(
    "closer-point",
    "Closer point",
    "You can tell which point is closer.",
    "Pip can pick the nearer point.",
    "space",
    [
      lesson("Pick the nearer point", "Nearest match is the first idea in similarity.", [
        choice(
          "near-x",
          "The target is at x = 1. Which point is closer?",
          [
            ["a", "x = 2"],
            ["b", "x = 9"],
          ],
          "a",
          "x = 2 is one step away. x = 9 is eight steps away.",
          "The smaller gap is the closer point.",
        ),
        slider(
          "dist",
          "How far is x = 2 from the target at x = 1?",
          0,
          10,
          1,
          "The gap is one step. Move higher.",
          "That gap is larger than one step. Move lower.",
          "Closer means the smaller gap.",
        ),
        choice(
          "near-y",
          "The target is at y = 8. Which point is closer?",
          [
            ["a", "y = 7"],
            ["b", "y = 1"],
          ],
          "a",
          "y = 7 is one step from 8. y = 1 is much farther down.",
          "Stay with the smaller vertical gap.",
        ),
        drag(
          "mark",
          "Drag the tip to the nearer mark at (3, 6).",
          [1, 1],
          [3, 6],
          "The nearer mark is up and a little to the right.",
          "The aim is right. Match the short distance to (3, 6).",
          "You landed on the nearer mark.",
        ),
        choice(
          "tie",
          "Two points sit the same distance from the target. They are...",
          [
            ["a", "Equally close"],
            ["b", "The left one, always"],
          ],
          "a",
          "The same gap means neither point wins.",
          "Equal gaps mean a tie.",
        ),
      ]),
      lesson("Compare gaps", "A model picks a neighbor by the smaller gap.", [
        choice(
          "pair",
          "The target is (5, 5). Which point is closer?",
          [
            ["a", "(6, 5)"],
            ["b", "(5, 1)"],
          ],
          "a",
          "(6, 5) is one step right. (5, 1) is four steps down.",
          "One step beats four steps.",
        ),
        slider(
          "one",
          "How many steps from (5, 5) to (6, 5) along x?",
          0,
          10,
          1,
          "The x numbers differ by one. Move higher.",
          "The x numbers differ by less than that. Move lower.",
          "Only x changes, by 1.",
        ),
        choice(
          "origin",
          "The target is (0, 0). Which point is closer?",
          [
            ["a", "(1, 0)"],
            ["b", "(4, 4)"],
          ],
          "a",
          "(1, 0) is one step away. (4, 4) is far on both axes.",
          "The origin's neighbor is the short step.",
        ),
        slider(
          "zero",
          "What is the distance from y = 3 to y = 3?",
          0,
          10,
          0,
          "A distance is not below zero. This gap is zero.",
          "Same y means the gap is zero. Move down.",
          "A point is zero away from itself.",
        ),
        drag(
          "near",
          "Drag the tip onto the nearer mark.",
          [5, 5],
          [6, 5],
          "The nearer mark is one step to the right.",
          "The aim is right. The nearer mark is one step away.",
          "One step beats a long step.",
        ),
      ]),
    ],
  ),
  skill(
    "arrow-parts",
    "Arrow parts",
    "You can point an arrow from tail to tip.",
    "Pip can aim an arrow.",
    "space",
    [
      lesson("Tail and tip", "A vector is an arrow a model can add and scale.", [
        choice(
          "tail",
          "The tail of an arrow is which end?",
          [
            ["a", "Where it starts"],
            ["b", "Where it points"],
          ],
          "a",
          "The tail stays put. The tip is where it points.",
          "The tail is the start.",
        ),
        choice(
          "tip",
          "The tip is which end?",
          [
            ["a", "Where it points"],
            ["b", "The middle of the shaft"],
          ],
          "a",
          "The tip is the end you move. The middle is not a new place.",
          "The tip names the end of the move.",
        ),
        drag(
          "aim",
          "The tail stays at (2, 2). Drag the tip to (8, 5).",
          [2, 2],
          [8, 5],
          "The mark is up and to the right of the tail.",
          "The direction is right. Match the length to (8, 5).",
          "Tail and tip tell the whole move.",
        ),
        choice(
          "move",
          "Tail and tip together describe what?",
          [
            ["a", "A move"],
            ["b", "Only a color"],
          ],
          "a",
          "The useful part is the move from tail to tip.",
          "An arrow is a move with size and direction.",
        ),
        slider(
          "rise",
          "From y = 2 to y = 5, how far does the tip rise?",
          0,
          10,
          3,
          "The tip rises more than that. Move higher.",
          "The tip rises less than that. Move lower.",
          "The rise is the change in y.",
        ),
      ]),
      lesson("Read the move", "The move stays the same when tail and tip shift together.", [
        drag(
          "flat",
          "Drag the tip. Leave the tail fixed.",
          [1, 4],
          [6, 4],
          "The mark is straight to the right.",
          "The direction is right. The mark is 5 units away.",
          "The tail stayed. The tip moved.",
        ),
        choice(
          "shift",
          "Tail and tip both shift by the same amount. The arrow...",
          [
            ["a", "Keeps the same move"],
            ["b", "Becomes a new direction"],
          ],
          "a",
          "A shared shift moves the whole arrow. The move itself stays.",
          "Equal arrows can start in different places.",
        ),
        slider(
          "run",
          "Tip x is 6 and tail x is 1. How far right is the move?",
          0,
          10,
          5,
          "Subtract the tail from the tip. Move higher.",
          "The run is smaller than that. Move lower.",
          "The run is tip x minus tail x.",
        ),
        choice(
          "left",
          "The tip is left of the tail. The arrow points which way?",
          [
            ["a", "Left"],
            ["b", "Right"],
          ],
          "a",
          "The tip leads. If the tip is left, the arrow points left.",
          "Follow the tip, not the tail.",
        ),
        drag(
          "up",
          "Point the arrow up. Tail at (4, 1), tip at (4, 7).",
          [4, 1],
          [4, 7],
          "Straight up. The mark shares the tail's x.",
          "The aim is up. Match the height of the mark.",
          "Same x means a vertical move.",
        ),
      ]),
    ],
  ),
  skill(
    "equal-arrows",
    "Equal arrows",
    "You can spot arrows with the same displacement.",
    "Pip treats equal arrows as the same move.",
    "space",
    [
      lesson("Same displacement", "Equal vectors are the same feature, wherever they start.", [
        choice(
          "same",
          "Two arrows each go 3 right from different tails. They are...",
          [
            ["a", "The same move"],
            ["b", "Different because the tails differ"],
          ],
          "a",
          "The tails can sit anywhere. The shared move is what matches.",
          "Equal arrows share a displacement.",
        ),
        slider(
          "rise",
          "Both arrows rise 4. Set that shared rise.",
          0,
          10,
          4,
          "The shared rise is higher. Move up.",
          "The shared rise is lower. Move down.",
          "Equal arrows share this rise.",
        ),
        drag(
          "copy",
          "Match the move: 4 right and 2 up. Start at (1, 1).",
          [1, 1],
          [5, 3],
          "The move goes right and a little up.",
          "The direction matches. The move is 4 right and 2 up.",
          "That displacement matches the other arrow.",
        ),
        choice(
          "feature",
          "A model treats equal arrows as what?",
          [
            ["a", "The same feature"],
            ["b", "Unrelated pictures"],
          ],
          "a",
          "The start point can change. The move is the feature.",
          "Same displacement, same feature.",
        ),
        choice(
          "unequal",
          "Arrow A is (+2, +0). Arrow B is (+2, +1). Are they equal?",
          [
            ["a", "No"],
            ["b", "Yes"],
          ],
          "a",
          "They share the run, but B also rises. The moves differ.",
          "One extra step up makes a different arrow.",
        ),
      ]),
    ],
  ),
  skill(
    "add-arrows",
    "Add arrows",
    "You can add arrows tip to tail.",
    "Pip can chain two moves.",
    "space",
    [
      lesson("Tip to tail", "Adding vectors is how layers combine signals.", [
        choice(
          "place",
          "To add two arrows, where do you put the second tail?",
          [
            ["a", "On the first tip"],
            ["b", "Back at the origin only"],
          ],
          "a",
          "The second move starts where the first move ends.",
          "Tip to tail chains the moves.",
        ),
        drag(
          "first",
          "Draw the first move: 3 right from (1, 2).",
          [1, 2],
          [4, 2],
          "The first move is straight right.",
          "The direction is right. Stop 3 units out.",
          "The first arrow is drawn.",
        ),
        slider(
          "sum-x",
          "Then add 2 more right. The tail was at x = 1. Where does x land?",
          0,
          10,
          6,
          "1, then 3, then 2 more. Move higher.",
          "That landing is past the chain. Move lower.",
          "The chained x is 6.",
        ),
        choice(
          "order",
          "Adding the arrows in the other order lands where?",
          [
            ["a", "On the same point"],
            ["b", "On a different point"],
          ],
          "a",
          "The two paths form a parallelogram and meet.",
          "Order does not change the sum.",
        ),
        drag(
          "sum",
          "The combined move is 5 right and 2 up from (1, 1). Drag the tip.",
          [1, 1],
          [6, 3],
          "The sum goes right and a little up.",
          "The direction matches. The sum is 5 right and 2 up.",
          "One arrow can stand for the chain.",
        ),
      ]),
      lesson("Combine moves", "A residual path adds a second arrow onto the first.", [
        slider(
          "cancel-part",
          "3 right plus 1 left is how many right?",
          0,
          10,
          2,
          "Left takes one step back from 3. Move higher.",
          "You gave back less than one step. Move lower.",
          "Opposite steps shrink the sum.",
        ),
        choice(
          "zero",
          "Opposite arrows of the same length add to what?",
          [
            ["a", "No move"],
            ["b", "A longer arrow"],
          ],
          "a",
          "The second arrow walks back what the first arrow walked.",
          "Equal opposites sum to a zero move.",
        ),
        drag(
          "up",
          "Add a move of 4 up. Tail at (3, 1), tip at (3, 5).",
          [3, 1],
          [3, 5],
          "This move is straight up, not sideways.",
          "The aim is up. The rise is 4.",
          "You added a vertical arrow.",
        ),
        slider(
          "ups",
          "2 up plus 3 up is how far up?",
          0,
          10,
          5,
          "Add the rises. Move higher.",
          "The rises add to less than that. Move lower.",
          "Same direction means the lengths add.",
        ),
        choice(
          "layer",
          "A layer adds two signals of the same shape by...",
          [
            ["a", "Adding their arrows"],
            ["b", "Picking a color"],
          ],
          "a",
          "The signals are arrows. Adding them combines the moves.",
          "Combined signals are a sum of arrows.",
        ),
      ]),
    ],
  ),
  skill(
    "scale-arrow",
    "Scale an arrow",
    "You can make an arrow longer or shorter.",
    "Pip can stretch a move.",
    "space",
    [
      lesson("Twice as long", "A weight scales how much an input matters.", [
        choice(
          "twice",
          "Twice as long means you do what?",
          [
            ["a", "Keep the direction and double the length"],
            ["b", "Turn the arrow around"],
          ],
          "a",
          "Scaling stretches the move. It does not reverse it.",
          "Direction stays. Length doubles.",
        ),
        slider(
          "double",
          "An arrow is 3 long. Set twice that length.",
          0,
          10,
          6,
          "Twice 3 is higher. Move up.",
          "Twice 3 is lower than that. Move down.",
          "The scaled length is 6.",
        ),
        drag(
          "stretch",
          "The short arrow ends at (4, 2) from (2, 2). Drag twice as far, to (6, 2).",
          [2, 2],
          [6, 2],
          "Stay on the horizontal line. Twice as far is still to the right.",
          "The direction is right. Twice the short arrow reaches x = 6.",
          "Same direction, double length.",
        ),
        slider(
          "half",
          "An arrow is 8 long. Set half of that.",
          0,
          10,
          4,
          "Half of 8 is higher. Move up.",
          "Half of 8 is lower. Move down.",
          "Half the length is 4.",
        ),
        choice(
          "weight",
          "A weight scales a signal by changing what?",
          [
            ["a", "Its length"],
            ["b", "Only its color"],
          ],
          "a",
          "The weight multiplies the size of the move.",
          "Scaling changes length.",
        ),
      ]),
      lesson("Half as long", "A smaller weight shortens the arrow and keeps its aim.", [
        drag(
          "half-draw",
          "Full length would reach (8, 3) from (2, 3). Stop halfway, at (5, 3).",
          [2, 3],
          [5, 3],
          "Halfway is still straight right, not a new direction.",
          "The aim is right. Half of the 6-unit run stops at x = 5.",
          "Half the length keeps the direction.",
        ),
        slider(
          "times3",
          "Length 2, times 3, is what?",
          0,
          10,
          6,
          "2 times 3 is higher. Move up.",
          "2 times 3 is lower. Move down.",
          "The scale multiplies the length.",
        ),
        choice(
          "zero",
          "Scaling by 0 leaves what?",
          [
            ["a", "No arrow"],
            ["b", "The same arrow"],
          ],
          "a",
          "A scale of 0 shrinks every step to nothing.",
          "Zero scale is a zero move.",
        ),
        slider(
          "half10",
          "Length 10, halved, is what?",
          0,
          10,
          5,
          "Half of 10 is higher. Move up.",
          "Half of 10 is lower. Move down.",
          "Half of 10 is 5.",
        ),
        choice(
          "closer",
          "Half as long keeps the direction. The tip moves...",
          [
            ["a", "Closer to the tail"],
            ["b", "Onto a new heading"],
          ],
          "a",
          "Shorter means the tip stops sooner on the same line.",
          "The heading stays. The tip comes in.",
        ),
      ]),
    ],
  ),
  skill(
    "arrow-length",
    "Arrow length",
    "You can tell which arrow is longer.",
    "Pip can compare lengths.",
    "space",
    [
      lesson("Which is longer", "Length is the size of a feature, not its direction.", [
        choice(
          "longer",
          "Arrow A spans 2 units. Arrow B spans 6. Which is longer?",
          [
            ["a", "B"],
            ["b", "A"],
          ],
          "a",
          "6 is a bigger move than 2.",
          "The longer arrow has the bigger length.",
        ),
        slider(
          "span",
          "How long is a flat arrow from x = 1 to x = 7?",
          0,
          10,
          6,
          "The ends are farther apart. Move higher.",
          "The ends are closer than that. Move lower.",
          "The length is the gap, 6.",
        ),
        choice(
          "aim",
          "A longer arrow is a larger move. Its direction can...",
          [
            ["a", "Stay the same"],
            ["b", "Be forced to turn"],
          ],
          "a",
          "Length and direction are separate. You can stretch without turning.",
          "Size can change while the aim stays.",
        ),
        drag(
          "draw",
          "Draw the longer move, 6 right from (1, 4).",
          [1, 4],
          [7, 4],
          "The longer move is straight right.",
          "The direction is right. The length is 6.",
          "That arrow is the long one.",
        ),
        choice(
          "compare",
          "A model can compare two features by...",
          [
            ["a", "Which arrow is longer"],
            ["b", "Which name is louder"],
          ],
          "a",
          "Length is the size you can compare.",
          "Bigger length, bigger feature.",
        ),
      ]),
    ],
  ),
  skill(
    "pip-checkpoint",
    "Guide Pip",
    "You can guide Pip to a point.",
    "Pip can reach a marked point.",
    "space",
    [
      lesson(
        "Reach the mark",
        "Reaching a target is the shape of a training step.",
        [
          choice(
            "aim",
            "Pip starts at (1, 1). The mark is right and up. First you...",
            [
              ["a", "Aim toward the mark"],
              ["b", "Ignore both axes"],
            ],
            "a",
            "The mark has a direction from the start. Aim there.",
            "The first move points at the mark.",
          ),
          drag(
            "guide",
            "Guide Pip from (1, 1) to the mark at (6, 4).",
            [1, 1],
            [6, 4],
            "The mark is up and to the right.",
            "The aim is right. Match the distance to (6, 4).",
            "Pip reaches the mark.",
          ),
          slider(
            "x",
            "The mark has x = 6. Set x.",
            0,
            10,
            6,
            "The mark is farther right. Move higher.",
            "The mark is not that far right. Move lower.",
            "Pip's x matches the mark.",
          ),
          slider(
            "y",
            "The mark has y = 4. Set y.",
            0,
            10,
            4,
            "The mark is higher. Move up.",
            "The mark is lower. Move down.",
            "Pip's y matches the mark.",
          ),
          choice(
            "arrow",
            "The move that reached the mark is what?",
            [
              ["a", "An arrow"],
              ["b", "Only a label"],
            ],
            "a",
            "It has a tail, a tip, a length, and a direction. That is an arrow.",
            "You guided Pip with an arrow.",
          ),
          choice(
            "train",
            "Taking a step toward a target is the shape of what?",
            [
              ["a", "A training step"],
              ["b", "A stored photo"],
            ],
            "a",
            "Training steps move toward a target. A photo just sits there.",
            "A training step aims at a target.",
          ),
        ],
        true,
      ),
    ],
  ),
];
