import { choice, drag, lesson, match, matrix, skill, slider, type SkillDraft } from "./helpers";

const right = { start: [2, 5] as [number, number], tip: [7, 5] as [number, number] };

export const vectorSkills: SkillDraft[] = [
  skill(
    "vector-pair",
    "Vector pair",
    "You can read an arrow as two numbers.",
    "Pip can read a vector.",
    "vectors",
    [
      lesson("Arrow and pair", "A feature vector is a list of numbers with a direction.", [
        drag(
          "draw",
          "Drag the tip onto the mark. Read the move it makes.",
          [1, 1],
          [5, 3],
          "The move goes right and up.",
          "The direction matches. Stretch until the tip meets the mark.",
          "The tip shows the pair.",
        ),
        slider(
          "dx",
          "Tip x is 6. Tail x is 2. Set the run.",
          0,
          10,
          4,
          "Subtract the tail from the tip. Move higher.",
          "The run is shorter than that. Move lower.",
          "The first number is the horizontal move.",
        ),
        slider(
          "dy",
          "Tip y is 7. Tail y is 2. Set the rise.",
          0,
          10,
          5,
          "The rise is larger. Move higher.",
          "The rise is smaller. Move lower.",
          "The second number is the vertical move.",
        ),
        choice(
          "pair",
          "You write run 4 and rise 5 as which pair?",
          [
            ["a", "(4, 5)"],
            ["b", "(5, 4)"],
          ],
          "a",
          "Right is first. Up is second. (5, 4) swaps them.",
          "The pair is (run, rise).",
        ),
        choice(
          "store",
          "The pair records the move, not the place. It stores...",
          [
            ["a", "The move"],
            ["b", "Only the tail's place"],
          ],
          "a",
          "The tail can sit anywhere. The pair is the displacement.",
          "The pair is the move.",
        ),
      ]),
      lesson("Left and up", "A negative first number points left.", [
        drag(
          "left",
          "The arrow goes 3 left from (6, 4).",
          [6, 4],
          [3, 4],
          "Left stays on the horizontal line.",
          "The aim is left. The move is 3 units.",
          "The tip is 3 left of the tail.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "neg",
          "A move of 4 left. Set the first number.",
          -5,
          5,
          -4,
          "Four left is not farther than that. Move toward zero.",
          "Left is negative. Stay below zero.",
          "Four left is a negative first number.",
        ),
        choice(
          "up",
          "Up 5 and right 0 is which pair?",
          [
            ["a", "(0, 5)"],
            ["b", "(5, 0)"],
          ],
          "a",
          "(5, 0) is right 5. You want no right and 5 up.",
          "No horizontal move, then the rise.",
        ),
        slider(
          "rise",
          "The rise is the change from y = 1 to y = 6. Set the second number.",
          0,
          10,
          5,
          "The rise is higher. Move up.",
          "The rise is lower. Move down.",
          "The second number is the change in y.",
        ),
        choice(
          "tail",
          "The tip shifts with the tail. The pair still records...",
          [
            ["a", "The move"],
            ["b", "The tail's place"],
          ],
          "a",
          "A shared shift moves the whole arrow. The pair is the displacement.",
          "The pair is the move.",
        ),
      ]),
      lesson("Read without a hint", "The pair is tip minus tail, one axis at a time.", [
        choice(
          "vertical",
          "An arrow from (2, 2) to (2, 6). The pair is...",
          [
            ["a", "(0, 4)"],
            ["b", "(4, 0)"],
          ],
          "a",
          "x does not change. y grows by 4, so the pair is (0, 4).",
          "Same x, rise 4.",
        ),
        slider(
          "part",
          "y goes from 3 to 8. Set the vertical part.",
          0,
          10,
          5,
          "y climbs more than that. Move higher.",
          "The rise is smaller than that. Move lower.",
          "The vertical part is the change in y.",
        ),
        drag(
          "three",
          "Draw the pair (3, 1) from (2, 2).",
          [2, 2],
          [5, 3],
          "The pair goes right and a little up.",
          "The direction matches. The run is 3 and the rise is 1.",
          "The tip is tail plus the pair.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "name",
          "Two numbers with a direction are called what?",
          [
            ["a", "A vector"],
            ["b", "A quadrant"],
          ],
          "a",
          "A quadrant is a region. This pair is a vector.",
          "The pair is a vector.",
        ),
        choice(
          "down",
          "(1, -2) points which way?",
          [
            ["a", "Right and down"],
            ["b", "Left and up"],
            ["c", "Right and up"],
          ],
          "a",
          "Positive first number is right. Negative second number is down.",
          "Right, then down.",
        ),
      ]),
    ],
  ),
  skill(
    "component-add",
    "Component addition",
    "You can add vectors component by component.",
    "Pip can add two vectors.",
    "vectors",
    [
      lesson("Add each place", "Residual connections add vectors of the same shape.", [
        choice(
          "how",
          "Add (2, 1) and (3, 4) by adding what?",
          [
            ["a", "Each place separately"],
            ["b", "Only the first numbers"],
          ],
          "a",
          "The second numbers add too. Both places get a sum.",
          "Add the firsts, then add the seconds.",
        ),
        slider(
          "first",
          "Add the first places of (2, 1) and (3, 4). Set that sum.",
          0,
          10,
          5,
          "2 and 3 add to more. Move up.",
          "2 and 3 add to less. Move down.",
          "The first place sums to 5.",
        ),
        slider(
          "second",
          "Add the second places of (2, 1) and (3, 6). Set that sum.",
          0,
          10,
          7,
          "1 and 6 add to more. Move up.",
          "1 and 6 add to less. Move down.",
          "The second place has its own sum.",
        ),
        choice(
          "sum",
          "The sum of (2, 1) and (3, 4) is...",
          [
            ["a", "(5, 5)"],
            ["b", "(6, 3)"],
            ["c", "(5, 4)"],
          ],
          "a",
          "(6, 3) crosses the places. (5, 4) leaves a second number out.",
          "Each place has its own sum.",
        ),
        drag(
          "draw",
          "Draw the sum (4, 2) from (1, 1).",
          [1, 1],
          [5, 3],
          "The sum goes right and up.",
          "The direction matches. The run is 4 and the rise is 2.",
          "The sum is one arrow.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Add a negative", "A negative component pulls that place back.", [
        slider(
          "back",
          "4 plus a step of 1 left. Set the result.",
          -2,
          8,
          3,
          "Left takes one step back from 4. Move up.",
          "You gave back more than one step. Move down.",
          "4 and one step left meet at 3.",
        ),
        slider(
          "up",
          "The second places are 2 and 5. Set their sum.",
          0,
          10,
          7,
          "The seconds add to more. Move up.",
          "The seconds add to less. Move down.",
          "The second place has its own sum.",
        ),
        choice(
          "pair",
          "(4, 2) + (-1, 3) is...",
          [
            ["a", "(3, 5)"],
            ["b", "(5, 5)"],
            ["c", "(3, -1)"],
          ],
          "a",
          "(5, 5) adds 1 instead of subtracting. (3, -1) subtracts the seconds.",
          "Subtract on the first place, add on the second.",
        ),
        choice(
          "double",
          "Adding a vector to itself is the same as...",
          [
            ["a", "Doubling it"],
            ["b", "Erasing it"],
          ],
          "a",
          "Each place is added to itself, so each place doubles.",
          "v + v doubles v.",
        ),
        drag(
          "three",
          "Draw (3, 2) from (2, 1).",
          [2, 1],
          [5, 3],
          "The arrow goes right and up.",
          "The direction matches. The run is 3 and the rise is 2.",
          "Tail plus the pair is the tip.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Add without a scaffold", "Order does not change a sum of vectors.", [
        choice(
          "axes",
          "(1, 0) + (0, 1) is...",
          [
            ["a", "(1, 1)"],
            ["b", "(0, 0)"],
            ["c", "(1, 0)"],
          ],
          "a",
          "Nothing cancels. Each place receives the 1 from one arrow.",
          "One step right plus one step up.",
        ),
        choice(
          "zero",
          "5 + 0 equals...",
          [
            ["a", "5"],
            ["b", "0"],
            ["c", "10"],
          ],
          "a",
          "Adding zero leaves the number. It does not erase it or double it.",
          "Zero adds nothing.",
        ),
        choice(
          "residual",
          "A residual connection adds two vectors by adding...",
          [
            ["a", "Matching places"],
            ["b", "The two first numbers only"],
          ],
          "a",
          "The shapes match, so each place has a partner to add.",
          "Matching places add.",
        ),
        slider(
          "three",
          "The second places are 1 and 6. Set their sum.",
          0,
          10,
          7,
          "The second place is higher. Move up.",
          "The second place is lower. Move down.",
          "The seconds add on their own.",
        ),
        choice(
          "order",
          "(2, 3) + (4, 0) equals...",
          [
            ["a", "(6, 3)"],
            ["b", "(2, 7)"],
            ["c", "(8, 0)"],
          ],
          "a",
          "(2, 7) adds across places. (8, 0) drops the 3.",
          "Add straight down the pair.",
        ),
      ]),
    ],
  ),
  skill(
    "scalar-multiply",
    "Scalar multiplication",
    "You can scale both components together.",
    "Pip can scale a vector.",
    "vectors",
    [
      lesson("Scale both numbers", "A weight multiplies every part of a signal.", [
        choice(
          "both",
          "Multiply (2, 3) by 2. You scale which numbers?",
          [
            ["a", "Both numbers"],
            ["b", "Only the first"],
          ],
          "a",
          "A scalar hits every component, not just the first.",
          "Both places double.",
        ),
        slider(
          "first",
          "The first number is 3, times 2. Set the result.",
          0,
          10,
          6,
          "3 times 2 is higher. Move up.",
          "3 times 2 is lower. Move down.",
          "The first place doubled.",
        ),
        slider(
          "second",
          "The second number is 4, times 2. Set the result.",
          0,
          10,
          8,
          "4 times 2 is higher. Move up.",
          "4 times 2 is lower. Move down.",
          "The second place doubled too.",
        ),
        choice(
          "result",
          "(2, 3) times 2 is...",
          [
            ["a", "(4, 6)"],
            ["b", "(2, 6)"],
            ["c", "(4, 3)"],
          ],
          "a",
          "(2, 6) leaves the first number. (4, 3) leaves the second.",
          "Both numbers doubled.",
        ),
        drag(
          "draw",
          "The short move is (2, 1) from (1, 1). Draw it doubled.",
          [1, 1],
          [5, 3],
          "The doubled arrow goes right and up.",
          "The direction matches. Both parts of (2, 1) double.",
          "Doubling scales the whole arrow.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Scale by a half", "Halving multiplies every component by the same amount.", [
        slider(
          "half-first",
          "Half of 8. Set the first number of (8, 6) halved.",
          0,
          10,
          4,
          "Half of 8 is higher. Move up.",
          "Half of 8 is lower. Move down.",
          "The first place is halved.",
        ),
        slider(
          "half-second",
          "Half of the second number, which is 6. Set it.",
          0,
          10,
          3,
          "Half of 6 is higher. Move up.",
          "Half of 6 is lower. Move down.",
          "The second place is halved too.",
        ),
        choice(
          "pair",
          "(6, 4) times 1/2 is...",
          [
            ["a", "(3, 2)"],
            ["b", "(6, 2)"],
            ["c", "(3, 4)"],
          ],
          "a",
          "(6, 2) halves only the second. (3, 4) halves only the first.",
          "Both places are halved.",
        ),
        choice(
          "zero",
          "Times 0 gives...",
          [
            ["a", "(0, 0)"],
            ["b", "The same vector"],
          ],
          "a",
          "Every component times 0 is 0.",
          "A zero scale clears the vector.",
        ),
        choice(
          "weight",
          "A weight scales a signal by changing...",
          [
            ["a", "Every component"],
            ["b", "Only the first component"],
          ],
          "a",
          "The weight is one number applied to each place.",
          "Every component feels the weight.",
        ),
      ]),
      lesson("Scale a signed pair", "A positive scale keeps the direction.", [
        choice(
          "signed",
          "(1, -2) times 3 is...",
          [
            ["a", "(3, -6)"],
            ["b", "(-3, 2)"],
            ["c", "(3, 6)"],
          ],
          "a",
          "(-3, 2) flips the signs. (3, 6) drops the minus on the second place.",
          "Both places triple, signs included.",
        ),
        slider(
          "three",
          "2 times 4. Set the first number.",
          -8,
          8,
          8,
          "2 times 4 is higher. Move up.",
          "2 times 4 is lower. Move down.",
          "The first place is scaled.",
        ),
        slider(
          "neg",
          "-2 times 3. Set the second number.",
          -8,
          8,
          -6,
          "That is past -6. Move toward zero.",
          "-2 times 3 is lower. Move down.",
          "The sign stays with the second place.",
        ),
        drag(
          "flat",
          "Draw (4, 0) from (2, 3).",
          [2, 3],
          [6, 3],
          "This scaled arrow is straight right.",
          "The aim is right. The run is 4.",
          "The second number stayed 0.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "aim",
          "A positive scale keeps the direction. The arrow...",
          [
            ["a", "Stays aimed the same way"],
            ["b", "Must turn around"],
          ],
          "a",
          "Multiplying by a positive number stretches. It does not turn.",
          "Positive scale, same aim.",
        ),
      ]),
    ],
  ),
  skill(
    "length-unit",
    "Length and direction",
    "You can separate length from direction.",
    "Pip can tell size from aim.",
    "vectors",
    [
      lesson("Size and aim", "Normalization keeps direction and drops raw size.", [
        choice(
          "split",
          "Length is the size of the move. Direction is...",
          [
            ["a", "Which way it points"],
            ["b", "The same number as the length"],
          ],
          "a",
          "Two arrows can share an aim and still have different lengths.",
          "Aim and size are different facts.",
        ),
        slider(
          "three",
          "A flat arrow runs from x = 2 to x = 7. Set its length.",
          0,
          10,
          5,
          "Along one axis, the length is the gap. Move higher.",
          "The gap is smaller than that. Move lower.",
          "A flat arrow's length is its run.",
        ),
        choice(
          "longer",
          "(0, 5) and (0, 2) share a direction. Which is longer?",
          [
            ["a", "(0, 5)"],
            ["b", "(0, 2)"],
          ],
          "a",
          "Both point up. 5 is a longer rise than 2.",
          "Same aim, greater length.",
        ),
        drag(
          "unit",
          "Draw a unit step right from (2, 3).",
          [2, 3],
          [3, 3],
          "A unit step right stays on the horizontal line.",
          "The aim is right. A unit step is 1 unit long.",
          "Length 1, direction right.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "unit-name",
          "A unit direction keeps the aim and sets the length to...",
          [
            ["a", "1"],
            ["b", "0"],
          ],
          "a",
          "Zero length has no direction left. A unit length is 1.",
          "Unit length is 1.",
        ),
      ]),
      lesson("Drop the size", "Dividing by the length keeps the direction.", [
        choice(
          "same",
          "(8, 0) points the same way as...",
          [
            ["a", "(1, 0)"],
            ["b", "(0, 1)"],
          ],
          "a",
          "(0, 1) points up. (8, 0) and (1, 0) both point right.",
          "Same direction, different length.",
        ),
        slider(
          "six",
          "Set the length of a flat arrow from x = 1 to x = 9.",
          0,
          10,
          8,
          "The flat arrow is longer than that. Move up.",
          "The flat arrow is shorter than that. Move down.",
          "The length is the horizontal gap.",
        ),
        choice(
          "divide",
          "Dividing by the length keeps...",
          [
            ["a", "The direction"],
            ["b", "A new turn"],
          ],
          "a",
          "You shrink the arrow onto length 1. The aim stays.",
          "The aim survives the resize.",
        ),
        slider(
          "up",
          "Set the length of a pure up arrow from y = 2 to y = 6.",
          0,
          10,
          4,
          "The rise is the length. Move higher.",
          "The rise is shorter than that. Move lower.",
          "Straight up, the length is the rise.",
        ),
        choice(
          "norm",
          "Normalization drops raw size so that...",
          [
            ["a", "A huge number cannot drown the aim"],
            ["b", "Every vector becomes zero"],
          ],
          "a",
          "The aim stays. Only the raw size is removed.",
          "Direction stays. Size is set aside.",
        ),
      ]),
      lesson("Keep the aim", "You can change length and keep the direction.", [
        choice(
          "greater",
          "Two arrows point the same way. The longer one has...",
          [
            ["a", "Greater length"],
            ["b", "A different direction"],
          ],
          "a",
          "Same way means the direction matches. Length is what differs.",
          "Longer means greater length.",
        ),
        slider(
          "four",
          "A flat arrow of run 3 is doubled. Set the new length.",
          0,
          10,
          6,
          "Double the run. Move up.",
          "Double the run is lower than that. Move down.",
          "Doubling length does not turn the arrow.",
        ),
        drag(
          "up",
          "Draw the direction of (0, 1) with length 4. Tail (3, 1).",
          [3, 1],
          [3, 5],
          "That direction is straight up.",
          "The aim is up. The length is 4.",
          "Same aim as (0, 1), longer body.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "down",
          "(0, -3) points which way?",
          [
            ["a", "Down"],
            ["b", "Up"],
            ["c", "Right"],
          ],
          "a",
          "A negative second number points down, not up or right.",
          "Negative y is down.",
        ),
        choice(
          "separate",
          "You can change the length and...",
          [
            ["a", "Keep the direction"],
            ["b", "Be forced to turn"],
          ],
          "a",
          "Length and direction come apart. Changing one can leave the other.",
          "Size and aim are separate.",
        ),
      ]),
    ],
  ),
  skill(
    "dot-agreement",
    "Dot product",
    "You can see how much two arrows agree.",
    "Pip can score agreement.",
    "vectors",
    [
      lesson("Same, opposite, right angle", "A neuron's first step is this agreement score.", [
        drag(
          "same",
          "Drag your tip the same way as the gray arrow.",
          [2, 2],
          [7, 2],
          "Your arrow turns away. The gray arrow points right.",
          "The direction matches. Stretch or shorten to the mark.",
          "Same direction means a positive agreement.",
          right,
          "positive",
        ),
        drag(
          "opposite",
          "Drag your tip the opposite way from the gray arrow.",
          [7, 2],
          [2, 2],
          "Opposite means the other way. The gray arrow points right.",
          "You are aimed the other way. Match the length of the mark.",
          "Opposite arrows disagree.",
          right,
          "negative",
        ),
        drag(
          "perp",
          "Drag your tip so it meets the gray arrow at a right angle.",
          [4, 1],
          [4, 6],
          "Straight up meets the gray arrow at a right angle.",
          "The aim is up. Match the length of the mark.",
          "A right angle means no agreement.",
          { start: [2, 3], tip: [7, 3] },
          "zero",
        ),
        slider(
          "score",
          "(2, 0) dot (4, 0). Set the score.",
          0,
          10,
          8,
          "Multiply the matching places, then add. Move up.",
          "The product of the runs is lower than that. Move down.",
          "Matching places multiply, then you add.",
        ),
        choice(
          "neuron",
          "What score do these arrows earn?",
          [
            ["a", "Positive"],
            ["b", "Zero"],
            ["c", "Negative"],
          ],
          "a",
          "They point the same way, so the score is positive.",
          "Same direction scores positive.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [2, 3], tip: [7, 3] },
            ],
          },
        ),
      ]),
      lesson("Compute the score", "You multiply matching places, then add those products.", [
        choice(
          "one",
          "(1, 0) dot (1, 0) is...",
          [
            ["a", "1"],
            ["b", "0"],
          ],
          "a",
          "1 times 1, plus 0 times 0, is 1.",
          "Same unit arrows score 1.",
          {
            arrows: [
              { start: [2, 6], tip: [6, 6], guide: true },
              { start: [2, 3], tip: [6, 3] },
            ],
            score: "positive",
          },
        ),
        choice(
          "against",
          "(1, 0) dot (-1, 0) is...",
          [
            ["a", "-1"],
            ["b", "1"],
          ],
          "a",
          "1 times -1 is -1. The zeros add nothing.",
          "Opposite unit arrows score -1.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [7, 3], tip: [2, 3] },
            ],
            score: "negative",
          },
        ),
        choice(
          "square",
          "(1, 0) dot (0, 1) is...",
          [
            ["a", "0"],
            ["b", "1"],
          ],
          "a",
          "1 times 0 plus 0 times 1 is 0. A right angle shares nothing.",
          "A right angle scores 0.",
          {
            arrows: [
              { start: [2, 4], tip: [7, 4], guide: true },
              { start: [4, 2], tip: [4, 7] },
            ],
            score: "zero",
          },
        ),
        slider(
          "high",
          "(3, 1) dot (2, 0). Set the score.",
          0,
          10,
          6,
          "3 times 2 is the whole score here. Move up.",
          "The second product is 0. Move down.",
          "Multiply matching places, then add.",
        ),
        choice(
          "product",
          "(2, 1) dot (3, 2) is...",
          [
            ["a", "8"],
            ["b", "15"],
            ["c", "6"],
          ],
          "a",
          "15 multiplies the sums. 6 keeps only the first product.",
          "Add the two products.",
        ),
      ]),
      lesson("Read a negative", "A negative score tells the model the signals point apart.", [
        slider(
          "four",
          "(2, 1) dot (3, 1). Set the score.",
          0,
          10,
          7,
          "Both products are positive. Their sum is higher. Move up.",
          "You added too much. Move down.",
          "Add the two products.",
        ),
        choice(
          "apart",
          "What score do these arrows earn?",
          [
            ["a", "Negative"],
            ["b", "Positive"],
          ],
          "a",
          "They point against each other, so the score is negative.",
          "Opposite arrows score negative.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [7, 3], tip: [2, 3] },
            ],
          },
        ),
        choice(
          "four-sum",
          "(3, 1) dot (-1, 2) is...",
          [
            ["a", "-1"],
            ["b", "5"],
            ["c", "1"],
          ],
          "a",
          "5 adds the sizes and drops the minus. 1 drops the first product.",
          "A minus on one product can pull the sum down.",
        ),
        slider(
          "mark",
          "(4, 0) dot (-1, 5). Set the score.",
          -8,
          8,
          -4,
          "The only product is negative, and it is lower. Move down.",
          "That is past the product. Move toward zero.",
          "The zeros add nothing. The first product decides.",
        ),
        choice(
          "share",
          "Bigger agreement means the arrows...",
          [
            ["a", "Share more direction"],
            ["b", "Must be perpendicular"],
          ],
          "a",
          "Perpendicular is zero. More shared direction raises the score.",
          "More shared direction, higher score.",
        ),
      ]),
      lesson("Rank the pairs", "The model keeps the pattern with the stronger agreement.", [
        choice(
          "most",
          "Which pair agrees most?",
          [
            ["a", "The pair that points the same way"],
            ["b", "The pair at a right angle"],
          ],
          "a",
          "A right angle scores 0. The pair that points the same way scores higher.",
          "Same direction beats a right angle.",
          {
            arrows: [
              { start: [1, 7], tip: [5, 7], guide: true },
              { start: [1, 5], tip: [5, 5] },
              { start: [6, 2], tip: [6, 6] },
            ],
          },
        ),
        choice(
          "least",
          "Which pair agrees least?",
          [
            ["a", "The pair that points opposite ways"],
            ["b", "The pair that points the same way"],
          ],
          "a",
          "Same direction scores positive. Opposite scores negative.",
          "Opposite is the low score.",
          {
            arrows: [
              { start: [2, 7], tip: [7, 7], guide: true },
              { start: [7, 4], tip: [2, 4] },
            ],
            score: "negative",
          },
        ),
        choice(
          "zero",
          "(4, 0) dot (0, 3) is...",
          [
            ["a", "0"],
            ["b", "12"],
            ["c", "7"],
          ],
          "a",
          "12 multiplies across a right angle. 7 adds the parts. Nothing is shared.",
          "No shared direction, score 0.",
        ),
        choice(
          "useful",
          "Perpendicular arrows matter because the score says they...",
          [
            ["a", "Share nothing"],
            ["b", "Are equal"],
          ],
          "a",
          "Equal arrows agree. A right angle shares no direction.",
          "Zero means they share nothing.",
        ),
        choice(
          "winner",
          "What score wins?",
          [
            ["a", "Positive"],
            ["b", "Zero"],
          ],
          "a",
          "Zero shares nothing. The positive pair wins.",
          "Keep the strongest agreement.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [2, 3], tip: [7, 3] },
            ],
            score: "positive",
          },
        ),
      ]),
    ],
  ),
  skill(
    "pattern-match",
    "Pattern match",
    "You can match the closer pattern.",
    "Pip can tell which pattern is closer.",
    "vectors",
    [
      lesson("Keep the match", "Attention starts by scoring which pattern agrees.", [
        choice(
          "keep",
          "Which pattern should Pip keep?",
          [
            ["a", "The one that points the same way"],
            ["b", "The one that points the other way"],
          ],
          "a",
          "The gray arrow and the blue arrow point the same way.",
          "Pip keeps the agreeing pattern.",
          {
            arrows: [
              { start: [1, 6], tip: [6, 6], guide: true },
              { start: [1, 4], tip: [6, 4] },
              { start: [8, 2], tip: [3, 2] },
            ],
          },
        ),
        match(
          "pairs",
          "Match each pattern with the way it points.",
          [
            ["sample", "Sample"],
            ["other", "Other"],
          ],
          [
            ["same", "Same way"],
            ["opp", "Opposite way"],
          ],
          [
            ["sample", "same"],
            ["other", "opp"],
          ],
          "Pair both patterns.",
          "The sample matches the same way. The other matches the opposite way.",
          "Each pattern has a direction relative to the sample.",
        ),
        slider(
          "high",
          "(2, 0) dot (3, 0) for the match. Set the score.",
          0,
          10,
          6,
          "The runs multiply. Move up.",
          "The second places are zero. Move down.",
          "The match scores the product of the runs.",
        ),
        choice(
          "low",
          "A low score means the patterns...",
          [
            ["a", "Point apart"],
            ["b", "Match"],
          ],
          "a",
          "A match scores high. A low score means they point apart.",
          "Low agreement means they differ.",
        ),
        choice(
          "tool",
          "Pip compares the patterns with...",
          [
            ["a", "A dot product"],
            ["b", "The order they were drawn"],
          ],
          "a",
          "Drawing order is not a score. The comparison is the dot product.",
          "The dot product is the comparison.",
        ),
      ]),
      lesson("Closer means agreement", "Closer, here, means a higher agreement score.", [
        choice(
          "pick",
          "Pattern A agrees. Pattern B is perpendicular. Pip picks...",
          [
            ["a", "A"],
            ["b", "B"],
          ],
          "a",
          "Perpendicular scores zero. The agreeing pattern scores higher.",
          "Higher agreement is the closer pattern.",
        ),
        choice(
          "zero",
          "The perpendicular pattern scores...",
          [
            ["a", "0"],
            ["b", "A high positive number"],
          ],
          "a",
          "A right angle shares no direction, so the score is 0.",
          "Perpendicular agreement is 0.",
        ),
        choice(
          "meaning",
          "Closer, on this path, means...",
          [
            ["a", "Higher agreement"],
            ["b", "Drawn nearer on the page"],
          ],
          "a",
          "The page position is not the score. Agreement is.",
          "Closer means the higher score.",
        ),
        drag(
          "aim",
          "Aim with the matching pattern: 4 right from (2, 3).",
          [2, 3],
          [6, 3],
          "The matching pattern sits to the right.",
          "The aim is right. The run is 4.",
          "You aimed at the match.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "store",
          "The match you keep is...",
          [
            ["a", "A score"],
            ["b", "Whichever pattern was drawn first"],
          ],
          "a",
          "The first drawing is not the winner. The agreement is.",
          "The match is a score.",
        ),
      ]),
      lesson("Pick the winner", "Keep the pattern with the higher agreement.", [
        choice(
          "winner",
          "Scores are 1, 6, and 0. Pip keeps...",
          [
            ["a", "The score of 6"],
            ["b", "The score of 1"],
            ["c", "The score of 0"],
          ],
          "a",
          "6 agrees more than 1 or 0.",
          "The highest score wins.",
        ),
        choice(
          "five",
          "A score of 2 and a score of 5. The winner is...",
          [
            ["a", "5"],
            ["b", "2"],
          ],
          "a",
          "5 agrees more than 2.",
          "The higher score wins.",
        ),
        choice(
          "tie",
          "If two scores tie, the patterns...",
          [
            ["a", "Agree equally"],
            ["b", "The left one wins anyway"],
          ],
          "a",
          "A tie means the agreements match. Place on the page is not the score.",
          "Equal scores, equal agreement.",
        ),
        match(
          "kinds",
          "Match each score with its directions.",
          [
            ["high", "High score"],
            ["zero", "Zero score"],
          ],
          [
            ["same", "Same direction"],
            ["right", "Right angle"],
          ],
          [
            ["high", "same"],
            ["zero", "right"],
          ],
          "Pair both scores.",
          "A high score is the same direction. Zero is a right angle.",
          "The score names the directions.",
        ),
        choice(
          "next",
          "Score the patterns, then...",
          [
            ["a", "Keep the stronger match"],
            ["b", "Keep every pattern equally"],
          ],
          "a",
          "Equal keeping ignores the score you just computed.",
          "The stronger match stays.",
        ),
      ]),
    ],
  ),
  skill(
    "projection",
    "Projection",
    "You can see one arrow's shadow on another.",
    "Pip can cast a shadow.",
    "vectors",
    [
      lesson("Shadow on a line", "A projection keeps the part of a signal along one direction.", [
        choice(
          "keep",
          "The shadow of an arrow on a rightward line keeps...",
          [
            ["a", "The rightward part"],
            ["b", "The upward part"],
          ],
          "a",
          "The line points right, so the shadow keeps the rightward part.",
          "The shadow keeps the part along the line.",
        ),
        drag(
          "along",
          "The shadow runs 4 right from (1, 3).",
          [1, 3],
          [5, 3],
          "The shadow lies on the horizontal line.",
          "The aim is right. The run is 4.",
          "The shadow stays on the line.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "len",
          "Arrow (4, 3) onto a horizontal line. The shadow length is...",
          [
            ["a", "4"],
            ["b", "3"],
            ["c", "7"],
          ],
          "a",
          "3 is the part off the line. 7 adds both parts.",
          "The shadow length is the matching part.",
        ),
        choice(
          "drop",
          "The leftover upward part is...",
          [
            ["a", "Left off the shadow"],
            ["b", "Added onto the shadow"],
          ],
          "a",
          "The shadow keeps only the part along the line.",
          "The rest drops away.",
        ),
        slider(
          "rest",
          "A shadow runs from x = 2 to x = 8. Set its length.",
          0,
          10,
          6,
          "The ends are farther apart. Move higher.",
          "The gap is smaller than that. Move lower.",
          "Only the matching part stays.",
        ),
      ]),
      lesson("Onto the vertical", "The shadow on the y axis keeps the vertical part.", [
        choice(
          "pair",
          "Onto the y axis, (2, 5) leaves a shadow of...",
          [
            ["a", "(0, 5)"],
            ["b", "(2, 0)"],
          ],
          "a",
          "(2, 0) is the shadow on the x axis. The y axis keeps (0, 5).",
          "Vertical shadow, horizontal part gone.",
        ),
        slider(
          "len",
          "The vertical part runs from y = 1 to y = 7. Set the shadow length.",
          0,
          10,
          6,
          "The vertical part is taller. Move higher.",
          "The horizontal part is not on this axis. Move lower.",
          "The shadow is the vertical part.",
        ),
        drag(
          "up",
          "Draw that vertical shadow, length 4, from (4, 1).",
          [4, 1],
          [4, 5],
          "The shadow is straight up.",
          "The aim is up. The length is 4.",
          "The shadow stands on the vertical line.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "none",
          "A perpendicular arrow casts...",
          [
            ["a", "No shadow"],
            ["b", "A full copy"],
          ],
          "a",
          "Perpendicular means no shared direction, so the shadow length is 0.",
          "Nothing lands on the line.",
        ),
        choice(
          "zero",
          "(0, 4) onto the x axis has shadow length...",
          [
            ["a", "0"],
            ["b", "4"],
          ],
          "a",
          "The arrow is vertical. The horizontal shadow has nothing to keep.",
          "No horizontal part, no shadow.",
        ),
      ]),
      lesson("Project twice", "Projecting twice onto the same line changes nothing the second time.", [
        choice(
          "stay",
          "(3, 0) onto the x axis is...",
          [
            ["a", "(3, 0)"],
            ["b", "(0, 3)"],
          ],
          "a",
          "It already lies on the x axis. The shadow is itself.",
          "Already on the line, so it stays.",
        ),
        choice(
          "twice",
          "Projecting twice onto the same line...",
          [
            ["a", "Changes nothing the second time"],
            ["b", "Doubles the arrow"],
          ],
          "a",
          "The second projection sees an arrow that is already on the line.",
          "The second pass is the same shadow.",
        ),
        slider(
          "three",
          "The shadow runs from x = 2 to x = 6. After a second projection, set the length.",
          0,
          10,
          4,
          "The second pass keeps the same gap. Move higher.",
          "The second pass does not grow the shadow. Move lower.",
          "The shadow length stays the gap.",
        ),
        drag(
          "draw",
          "Draw (3, 0) from (2, 2).",
          [2, 2],
          [5, 2],
          "The shadow is horizontal.",
          "The aim is right. The length is 3.",
          "The shadow is the horizontal arrow.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "name",
          "Keeping only the part along one direction is a...",
          [
            ["a", "Projection"],
            ["b", "A turn onto a new heading"],
          ],
          "a",
          "A turn would change the aim. A projection keeps the matching aim.",
          "That kept part is a projection.",
        ),
      ]),
      lesson("Name the shadow", "You used the agreement with (1, 0) to keep the matching part.", [
        choice(
          "which",
          "Arrow (4, 2) onto (1, 0). The shadow is...",
          [
            ["a", "(4, 0)"],
            ["b", "(0, 2)"],
            ["c", "(4, 2)"],
          ],
          "a",
          "(0, 2) keeps the off-line part. (4, 2) keeps both.",
          "The horizontal part stays.",
        ),
        choice(
          "second",
          "The second number of that shadow is...",
          [
            ["a", "0"],
            ["b", "2"],
          ],
          "a",
          "2 was the part off the line. The shadow drops it.",
          "The off-line part is 0 on the shadow.",
        ),
        slider(
          "first",
          "A horizontal shadow from x = 1 to x = 6. Set its length.",
          0,
          10,
          5,
          "The matching part is longer. Move higher.",
          "The matching part is shorter. Move lower.",
          "The first number is the run along the line.",
        ),
        choice(
          "discard",
          "The off-line part of (4, 2) on the x axis...",
          [
            ["a", "Is discarded"],
            ["b", "Becomes the shadow"],
          ],
          "a",
          "The shadow is the matching part. The rest is discarded.",
          "Only the agreement along the line stays.",
        ),
        choice(
          "onto-y",
          "(1, 4) onto (0, 1). The shadow is...",
          [
            ["a", "(0, 4)"],
            ["b", "(1, 0)"],
            ["c", "(1, 4)"],
          ],
          "a",
          "(1, 0) is the shadow on the x axis. (1, 4) drops nothing.",
          "The vertical part stays.",
        ),
      ]),
    ],
  ),
  skill(
    "matrix-numbers",
    "Matrix numbers",
    "You can read a matrix as four numbers.",
    "Pip can read a 2 by 2 matrix.",
    "vectors",
    [
      lesson("Four numbers", "A small layer is a table of weights.", [
        choice(
          "count",
          "A 2 by 2 matrix holds how many numbers?",
          [
            ["a", "Four"],
            ["b", "Two"],
            ["c", "One"],
          ],
          "a",
          "Two rows of two numbers is four cells, not one reused cell.",
          "Four cells, two rows.",
        ),
        matrix(
          "identity",
          "Match the shown table. It leaves a point where it was.",
          [1, 0, 0, 1],
          "The diagonal cells stay 1. The other two stay 0.",
          "That table leaves a point where it was.",
          true,
        ),
        choice(
          "a",
          "In 3, 0 / 0, 1, the top left number is...",
          [
            ["a", "3"],
            ["b", "0"],
            ["c", "1"],
          ],
          "a",
          "Top left is the first cell. 0 is beside it. 1 is bottom right.",
          "Top left is the first weight.",
        ),
        matrix(
          "row",
          "Top row 2, 1. Bottom row 0, 3. The phone does not show them.",
          [2, 1, 0, 3],
          "Read left to right, top row first. Bottom left stays 0.",
          "You set all four weights.",
        ),
        choice(
          "layer",
          "These four numbers are weights. A small layer is...",
          [
            ["a", "A table of weights"],
            ["b", "One weight reused four times"],
          ],
          "a",
          "The four cells can differ. The layer is the whole table.",
          "A small layer is this table.",
        ),
      ]),
      lesson("Read the cells", "The identity table is 1, 0 on the top row and 0, 1 below.", [
        matrix(
          "build",
          "Build the identity: the table that keeps every point.",
          [1, 0, 0, 1],
          "The diagonal cells are 1. The other two stay 0.",
          "Those four weights keep the point.",
        ),
        choice(
          "c",
          "In a, b / c, d, the bottom left cell is...",
          [
            ["a", "c"],
            ["b", "b"],
            ["c", "d"],
          ],
          "a",
          "b is top right. d is bottom right. Bottom left is c.",
          "Bottom left is c.",
        ),
        choice(
          "identity",
          "1, 0 / 0, 1 leaves a point...",
          [
            ["a", "Where it was"],
            ["b", "At the origin always"],
          ],
          "a",
          "The identity keeps each point. It does not send everything to the origin.",
          "The identity keeps the point.",
        ),
        matrix(
          "again",
          "Build the identity again, with no numbers shown.",
          [1, 0, 0, 1],
          "The diagonal cells are 1. The other two stay 0.",
          "You can rebuild the identity from the rule.",
        ),
        match(
          "axes",
          "Match the matrix words with the way you read them.",
          [
            ["row", "Row"],
            ["col", "Column"],
          ],
          [
            ["across", "Across"],
            ["down", "Down"],
          ],
          [
            ["row", "across"],
            ["col", "down"],
          ],
          "Pair both words.",
          "A row runs across. A column runs down.",
          "Rows across, columns down.",
        ),
      ]),
    ],
  ),
  skill(
    "matrix-vector",
    "Matrix times vector",
    "You can warp a point with a matrix.",
    "Pip can warp a point.",
    "vectors",
    [
      lesson("Double x", "A layer stretches the input this way.", [
        choice(
          "which",
          "The matrix 2, 0 / 0, 1 doubles which coordinate?",
          [
            ["a", "x"],
            ["b", "y"],
            ["c", "Both, by the same amount"],
          ],
          "a",
          "The bottom right is 1, so y stays. Both would need two 2s.",
          "x doubles. y stays.",
        ),
        matrix(
          "set",
          "Set the table that doubles x and leaves y.",
          [2, 0, 0, 1],
          "Top left doubles x. Bottom right keeps y. The other cells stay 0.",
          "That table doubles x.",
        ),
        slider(
          "x",
          "x doubles. Start at x = 3. Set the new x.",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "x lands at twice the start.",
        ),
        choice(
          "y",
          "Its y, under 2, 0 / 0, 1, ...",
          [
            ["a", "Stays the same"],
            ["b", "Doubles too"],
          ],
          "a",
          "The matrix multiplies y by 1.",
          "y is unchanged.",
        ),
        drag(
          "move",
          "From (2, 3), x doubles and y stays. Drag the tip.",
          [2, 3],
          [4, 3],
          "x doubles, so the move is straight right.",
          "The aim is right. x grows and y stays.",
          "The point slid right.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Double y", "The bottom right weight scales y.", [
        choice(
          "which",
          "The matrix 1, 0 / 0, 2 doubles...",
          [
            ["a", "y"],
            ["b", "x"],
          ],
          "a",
          "Top left is 1, so x stays. Bottom right 2 doubles y.",
          "y doubles.",
        ),
        matrix(
          "set",
          "Set the table that doubles y and leaves x.",
          [1, 0, 0, 2],
          "Top left keeps x. Bottom right doubles y. The other cells stay 0.",
          "That table doubles y.",
        ),
        slider(
          "y",
          "y starts at 3 and doubles. Set the new y.",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "y lands at twice the start.",
        ),
        choice(
          "x",
          "x under that table...",
          [
            ["a", "Stays the same"],
            ["b", "Doubles"],
          ],
          "a",
          "The top left weight is 1, so x is unchanged.",
          "x stays.",
        ),
        drag(
          "move",
          "From (3, 2), y doubles and x stays. Drag the tip.",
          [3, 2],
          [3, 4],
          "y doubles, so the move is straight up.",
          "The aim is up. y grows and x stays.",
          "The point rose.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Slide sideways", "The top right weight mixes y into x.", [
        choice(
          "send",
          "1, 1 / 0, 1 sends (0, 1) to...",
          [
            ["a", "(1, 1)"],
            ["b", "(0, 1)"],
            ["c", "(1, 0)"],
          ],
          "a",
          "(0, 1) forgets the mix. (1, 0) drops y.",
          "y is added into x. y stays.",
        ),
        matrix(
          "set",
          "Set the slide that adds y into x and keeps y.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "That table mixes y into x.",
        ),
        slider(
          "x",
          "Start at x = 2, y = 4, and x becomes x + y. Set the new x.",
          0,
          10,
          6,
          "Add y onto x. Move up.",
          "x plus y is lower than that. Move down.",
          "The new x is the sum.",
        ),
        choice(
          "y",
          "y under 1, 1 / 0, 1...",
          [
            ["a", "Stays the same"],
            ["b", "Becomes x"],
          ],
          "a",
          "The bottom row keeps y and adds nothing from x.",
          "y is unchanged.",
        ),
        drag(
          "move",
          "From (2, 3), add y into x. Drag the tip.",
          [2, 3],
          [5, 3],
          "The slide is straight right. y stays.",
          "The aim is right. x grows by the size of y.",
          "The point slid sideways.",
          undefined,
          undefined,
          false,
        ),
      ]),
      lesson("Stretch both", "The four numbers decide where each point moves.", [
        choice(
          "zero",
          "0, 0 / 0, 0 sends every point to...",
          [
            ["a", "The origin"],
            ["b", "The same point"],
          ],
          "a",
          "Every weight is 0, so both new coordinates are 0.",
          "A zero table sends points to the origin.",
        ),
        matrix(
          "both",
          "Set a double on both axes.",
          [2, 0, 0, 2],
          "Both diagonal cells are 2. The other cells stay 0.",
          "Both axes double.",
        ),
        slider(
          "x",
          "x starts at 3 and both axes double. Set the new x.",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "x lands at twice the start.",
        ),
        slider(
          "y",
          "y starts at 4 under that same double. Set the new y.",
          0,
          10,
          8,
          "4 doubled is higher. Move up.",
          "4 doubled is lower. Move down.",
          "y lands at twice the start.",
        ),
        choice(
          "decide",
          "The four numbers decide...",
          [
            ["a", "Where each point moves"],
            ["b", "Only which point is first"],
          ],
          "a",
          "Order in a list is not the warp. The table moves the point.",
          "The warp is the move.",
        ),
      ]),
    ],
  ),
  skill(
    "drawing-stretch",
    "Drawing stretch",
    "You can watch a drawing stretch.",
    "Pip can stretch a drawing.",
    "vectors",
    [
      lesson("Stretch sideways", "Features move together when a matrix warps space.", [
        choice(
          "every",
          "A tiny drawing is a few points. The same matrix moves...",
          [
            ["a", "Every point"],
            ["b", "Only the first point"],
          ],
          "a",
          "One table applies to every point in the drawing.",
          "Every point uses the same warp.",
        ),
        matrix(
          "wide",
          "Set the table that doubles width and keeps height.",
          [2, 0, 0, 1],
          "Top left is 2, bottom right is 1, and the other cells stay 0.",
          "That stretch doubles width.",
        ),
        slider(
          "corner",
          "A corner at x = 3 doubles. Set the new x.",
          0,
          10,
          6,
          "x doubles. Move higher.",
          "x doubles to less than that. Move lower.",
          "The corner's x doubles.",
        ),
        drag(
          "travel",
          "That corner travels from (2, 3) when x doubles. Drag the tip.",
          [2, 3],
          [4, 3],
          "The corner moves straight right.",
          "The aim is right. x doubles and y stays.",
          "The corner moved with the stretch.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "shape",
          "The height stays put. The drawing gets...",
          [
            ["a", "Wider"],
            ["b", "Taller"],
          ],
          "a",
          "y is multiplied by 1. Only x grows, so the drawing gets wider.",
          "Width grows. Height stays.",
        ),
      ]),
      lesson("Stretch upward", "The same rule can stretch height instead of width.", [
        matrix(
          "tall",
          "Set the table that doubles height and leaves width.",
          [1, 0, 0, 2],
          "Top left is 1 and bottom right is 2. The other cells stay 0.",
          "That table doubles height.",
        ),
        choice(
          "gets",
          "The drawing gets...",
          [
            ["a", "Taller"],
            ["b", "Only wider"],
          ],
          "a",
          "y doubles and x stays, so the drawing grows upward.",
          "Height doubles.",
        ),
        slider(
          "top",
          "A top at y = 3 doubles. Set the new y.",
          0,
          10,
          6,
          "y doubles. Move higher.",
          "y doubles to less than that. Move lower.",
          "The top doubles.",
        ),
        drag(
          "rise",
          "From (3, 2), height doubles. Drag the tip.",
          [3, 2],
          [3, 4],
          "This corner moves straight up.",
          "The aim is up. y doubles and x stays.",
          "The corner rose.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "line",
          "Points that sat on a line still sit on a line. The warp is...",
          [
            ["a", "Even"],
            ["b", "A bend"],
          ],
          "a",
          "A matrix moves lines to lines. It does not bend them.",
          "Lines stay lines.",
        ),
      ]),
      lesson("Grow both ways", "Doubling both axes grows the drawing and keeps its shape.", [
        matrix(
          "both",
          "Set the table that doubles both axes.",
          [2, 0, 0, 2],
          "Both diagonal cells are 2. The other cells stay 0.",
          "Both axes double.",
        ),
        choice(
          "shape",
          "Both axes double. The drawing...",
          [
            ["a", "Grows and keeps its shape"],
            ["b", "Flips upside down"],
            ["c", "Grows wider and shrinks taller"],
          ],
          "a",
          "Both scales are positive and equal, so the shape grows without a flip or a squash.",
          "Same scale on both axes keeps the shape.",
        ),
        slider(
          "x",
          "A point at x = 3 doubles with both axes. Set the new x.",
          0,
          10,
          6,
          "x doubles. Move higher.",
          "x doubles to less than that. Move lower.",
          "The new x is twice the start.",
        ),
        slider(
          "y",
          "That point's y starts at 4. Set the new y.",
          0,
          10,
          8,
          "y doubles too. Move higher.",
          "y doubles to less than that. Move lower.",
          "The new y is twice the start.",
        ),
        choice(
          "why",
          "Features move together. A matrix can...",
          [
            ["a", "Stretch a whole drawing"],
            ["b", "Move one point and leave the rest"],
          ],
          "a",
          "Every point of the drawing uses the same table.",
          "The whole drawing stretches together.",
        ),
      ]),
    ],
  ),
  skill(
    "two-warps",
    "Two warps",
    "You can apply one warp, then another.",
    "Pip can stack two warps.",
    "vectors",
    [
      lesson("One, then the other", "Stacked layers are transformations applied in order.", [
        choice(
          "order",
          "You apply the first matrix, then the second. The point moves...",
          [
            ["a", "Twice, in order"],
            ["b", "Only by the first matrix"],
          ],
          "a",
          "The second matrix sees the point the first matrix produced.",
          "Two warps, in order.",
        ),
        matrix(
          "first",
          "Set the first warp, the one that doubles x and leaves y.",
          [2, 0, 0, 1],
          "Top left doubles x. Bottom right keeps y. The other cells stay 0.",
          "The first warp doubles x.",
        ),
        matrix(
          "second",
          "Set the second warp, the one that doubles y and leaves x.",
          [1, 0, 0, 2],
          "Top left keeps x. Bottom right doubles y. The other cells stay 0.",
          "The second warp doubles y.",
        ),
        slider(
          "x",
          "Start at x = 3. After x doubles, set x.",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "x ends at twice the start.",
        ),
        slider(
          "y",
          "Start at y = 4. After y doubles, set y.",
          0,
          10,
          8,
          "4 doubled is higher. Move up.",
          "4 doubled is lower. Move down.",
          "y ends at twice the start.",
        ),
      ]),
      lesson("Order matters", "The second warp sees the first warp's output.", [
        choice(
          "matters",
          "Doing A then B can differ from B then A. Order...",
          [
            ["a", "Matters"],
            ["b", "Never matters"],
          ],
          "a",
          "The second warp acts on an already moved point.",
          "Order can change the result.",
        ),
        matrix(
          "a",
          "Warp A adds y into x and keeps y. Set it.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "Warp A is set.",
        ),
        choice(
          "land",
          "(2, 3) through A lands at...",
          [
            ["a", "(5, 3)"],
            ["b", "(2, 3)"],
            ["c", "(2, 5)"],
          ],
          "a",
          "(2, 3) skips the mix. (2, 5) adds into y instead of x.",
          "A slides the point by adding y into x.",
        ),
        matrix(
          "b",
          "Set the table that doubles width and leaves height.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "Warp B doubles x.",
        ),
        choice(
          "sees",
          "The second warp sees...",
          [
            ["a", "The first warp's output"],
            ["b", "Only the original point"],
          ],
          "a",
          "Stacking means the output of one becomes the input of the next.",
          "The second warp sees the first result.",
        ),
      ]),
      lesson("Two identities", "Two copies of the identity leave a point where it started.", [
        choice(
          "stay",
          "Two identity matrices in a row leave a point...",
          [
            ["a", "Where it started"],
            ["b", "At the origin"],
          ],
          "a",
          "Each identity keeps the point, so two of them still keep it.",
          "The point never moves.",
        ),
        matrix(
          "one",
          "Set the identity.",
          [1, 0, 0, 1],
          "Diagonal cells are 1. The other two stay 0.",
          "The first identity is set.",
        ),
        matrix(
          "two",
          "Set the second identity.",
          [1, 0, 0, 1],
          "Diagonal cells are 1 again. The other two stay 0.",
          "The second identity is set.",
        ),
        choice(
          "x",
          "Start at x = 4. After both identities, x is...",
          [
            ["a", "4"],
            ["b", "0"],
            ["c", "8"],
          ],
          "a",
          "Each identity keeps x. It does not clear it or double it.",
          "x is still where it started.",
        ),
        choice(
          "read",
          "A deep stack still applies the warps...",
          [
            ["a", "In order"],
            ["b", "All at once, with order dropped"],
          ],
          "a",
          "You can combine them later. The stack still applies them in order.",
          "Order stays, even in a stack.",
        ),
      ]),
    ],
  ),
  skill(
    "eigen-direction",
    "Eigen direction",
    "You can find a direction that only stretches.",
    "Pip can find a stretch direction.",
    "vectors",
    [
      lesson("A direction that stays", "Some directions only scale, and those directions structure a transformation.", [
        choice(
          "stay",
          "2, 0 / 0, 1 takes a rightward arrow to a longer rightward arrow. The direction...",
          [
            ["a", "Stays"],
            ["b", "Turns up"],
          ],
          "a",
          "x doubles and y stays 0, so a rightward arrow stays rightward.",
          "It stretches and does not turn.",
        ),
        drag(
          "draw",
          "A rightward arrow at (2, 3) has run 2. Double the run and keep the aim.",
          [2, 3],
          [6, 3],
          "The stretch stays on the horizontal line.",
          "The aim is right. The run doubles.",
          "Same direction, greater length.",
          undefined,
          undefined,
          false,
        ),
        matrix(
          "set",
          "Set the table that stretches x and leaves y.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "That table stretches x.",
        ),
        choice(
          "name",
          "An arrow that only scales, and does not turn, lies on...",
          [
            ["a", "An eigen direction"],
            ["b", "A direction the matrix turns"],
          ],
          "a",
          "A turned arrow left the eigen direction. This one only scaled.",
          "That direction is an eigen direction.",
        ),
        choice(
          "right",
          "An up arrow stays up but does not get longer. A right arrow...",
          [
            ["a", "Gets longer"],
            ["b", "Turns left"],
          ],
          "a",
          "x is doubled. A rightward arrow grows and stays right.",
          "The rightward direction stretches.",
        ),
      ]),
      lesson("Every direction scales", "Equal scales on both axes leave every aim in place.", [
        choice(
          "all",
          "2, 0 / 0, 2 scales every direction by 2. Arrows...",
          [
            ["a", "Stay aimed the same way"],
            ["b", "All turn"],
          ],
          "a",
          "Both coordinates double, so the aim of any arrow stays.",
          "Everything stretches, nothing turns.",
        ),
        matrix(
          "set",
          "Set the table that scales both axes by the same amount.",
          [2, 0, 0, 2],
          "Both diagonal cells are 2. The other cells stay 0.",
          "Both axes scale together.",
        ),
        drag(
          "diag",
          "A diagonal that does not turn doubles from (2, 2).",
          [2, 2],
          [4, 4],
          "The diagonal stays on the line y = x.",
          "The aim matches. The tip is twice as far.",
          "The diagonal only got longer.",
          undefined,
          undefined,
          false,
        ),
        slider(
          "scale",
          "A step of 3 becomes 6. Set the scale.",
          0,
          10,
          2,
          "6 is twice 3. The scale is higher. Move up.",
          "The scale is how many times 3 fits into 6. Move down.",
          "The scale is the factor, not the new length.",
        ),
        choice(
          "found",
          "Directions the matrix only scales...",
          [
            ["a", "Organize the warp"],
            ["b", "Are turned away"],
          ],
          "a",
          "Those directions organize how the warp acts.",
          "Stretch directions structure the warp.",
        ),
      ]),
      lesson("One direction turns", "A sideways slide turns an upward arrow and leaves a horizontal arrow.", [
        choice(
          "up",
          "1, 1 / 0, 1 slides points sideways. A straight-up arrow...",
          [
            ["a", "Tilts"],
            ["b", "Only gets longer"],
          ],
          "a",
          "(0, 1) becomes (1, 1). It gains a sideways part, so it tilts.",
          "Up is not an eigen direction of this matrix.",
        ),
        drag(
          "flat",
          "The direction that does not turn is horizontal. From (2, 4), draw a run of 3.",
          [2, 4],
          [5, 4],
          "The stable direction is straight right.",
          "The aim is right. The run is 3.",
          "Horizontal arrows stay horizontal.",
          undefined,
          undefined,
          false,
        ),
        choice(
          "tilt",
          "(0, 1) through 1, 1 / 0, 1 becomes (1, 1). The arrow...",
          [
            ["a", "Turns"],
            ["b", "Stays vertical"],
          ],
          "a",
          "A new horizontal part means it is no longer vertical.",
          "It turns.",
        ),
        matrix(
          "set",
          "Set the sideways slide.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "That is the sideways slide.",
        ),
        choice(
          "organize",
          "The horizontal arrow stays. The vertical arrow turns. The eigen direction is...",
          [
            ["a", "Horizontal"],
            ["b", "Vertical"],
          ],
          "a",
          "The direction that only stretches is the one that does not turn.",
          "Horizontal is the eigen direction here.",
        ),
      ]),
    ],
  ),
  skill(
    "pip-capstone",
    "Teach Pip",
    "You can teach Pip to match patterns.",
    "Pip can match a pattern with a dot product.",
    "vectors",
    [
      lesson(
        "Match by agreement",
        "Matching by agreement is how a tiny network recognizes a pattern.",
        [
          drag(
            "same",
            "Match the gray arrow. It points right.",
            [2, 2],
            [7, 2],
            "The gray arrow points right. Aim the same way.",
            "The direction matches. Reach the mark.",
            "Same direction means the patterns agree.",
            right,
          ),
          choice(
            "agree",
            "That match means the patterns...",
            [
              ["a", "Agree"],
              ["b", "Point opposite ways"],
            ],
            "a",
            "Same direction is agreement, not opposition.",
            "The patterns agree.",
          ),
          drag(
            "opposite",
            "Now point the opposite way from the gray arrow.",
            [7, 3],
            [2, 3],
            "Opposite is left if the gray arrow points right.",
            "You are aimed the other way. Match the length.",
            "Opposite arrows get a negative score.",
            right,
          ),
          choice(
            "keep",
            "Pip keeps the pattern with...",
            [
              ["a", "The higher agreement"],
              ["b", "The pattern that was drawn first"],
            ],
            "a",
            "Drawing order is not the score. The higher agreement wins.",
            "Higher agreement stays.",
          ),
          match(
            "scores",
            "Match each direction with its score.",
            [
              ["agree", "Agree"],
              ["oppose", "Oppose"],
              ["square", "Right angle"],
            ],
            [
              ["pos", "Positive"],
              ["neg", "Negative"],
              ["zero", "Zero"],
            ],
            [
              ["agree", "pos"],
              ["oppose", "neg"],
              ["square", "zero"],
            ],
            "Pair all three directions.",
            "Agree is positive, oppose is negative, and a right angle is zero.",
            "Each direction has a score.",
          ),
          slider(
            "high",
            "(3, 0) dot (2, 0) for the match. Set the score.",
            0,
            10,
            6,
            "The runs multiply. Move up.",
            "The second places add nothing. Move down.",
            "The match scores that product.",
          ),
          choice(
            "name",
            "A tiny layer scores that agreement with...",
            [
              ["a", "A dot product"],
              ["b", "The pattern's place in a list"],
            ],
            "a",
            "Place in a list is not the score. The score is a dot product.",
            "The score is a dot product.",
          ),
          choice(
            "taught",
            "You taught Pip to match. The math...",
            [
              ["a", "Scored which pattern agrees"],
              ["b", "Kept every pattern equally"],
            ],
            "a",
            "Matching here is a score, not an equal keep.",
            "Pip matches by agreement.",
          ),
        ],
        true,
      ),
    ],
  ),
];
