import { choice, drag, lesson, match, matrix, skill, slider, type SkillDraft } from "./helpers";

const right = { start: [2, 5] as [number, number], tip: [7, 5] as [number, number] };

export const vectorSkills: SkillDraft[] = [
  skill(
    "vector-pair",
    "Vector pair",
    "You can read an arrow as two numbers.",
    "Pip can read a vector.",
    "vectors",
    [
      lesson("Arrow and pair", "A feature vector is a list of numbers with a direction.", [
        drag(
          "draw",
          "This arrow runs 4 right and 2 up. Drag the tip.",
          [1, 1],
          [5, 3],
          "The move goes right and up.",
          "The direction matches. The move is 4 right and 2 up.",
          "The tip matches the pair.",
        ),
        slider(
          "dx",
          "How many right? Set the first number.",
          0,
          10,
          4,
          "The first number is the run to the right. Move higher.",
          "The run is shorter than that. Move lower.",
          "The first number is the horizontal move.",
        ),
        slider(
          "dy",
          "How many up? Set the second number.",
          0,
          10,
          2,
          "The second number is the rise. Move higher.",
          "The rise is smaller than that. Move lower.",
          "The second number is the vertical move.",
        ),
        choice(
          "pair",
          "You write that arrow as which pair?",
          [
            ["a", "(4, 2)"],
            ["b", "(2, 4)"],
          ],
          "a",
          "Right is first. Up is second. (2, 4) swaps them.",
          "The pair is (run, rise).",
        ),
        choice(
          "store",
          "The pair records the move, not the place. A model stores it as...",
          [
            ["a", "A feature vector"],
            ["b", "A color name"],
          ],
          "a",
          "The numbers and their direction are the feature.",
          "A feature vector is this pair.",
        ),
      ]),
      lesson("Left and up", "A negative first number points left.", [
        drag(
          "left",
          "The arrow goes 3 left. Tail (6, 4), tip (3, 4).",
          [6, 4],
          [3, 4],
          "Left stays on the horizontal line.",
          "The aim is left. The move is 3 units.",
          "The tip is 3 left of the tail.",
        ),
        slider(
          "neg",
          "Left is a negative first number. Set the move of 3 left.",
          -5,
          5,
          -3,
          "More negative is farther left. This move is only 3 left.",
          "Left is negative. Stay below zero.",
          "Three left is -3.",
        ),
        choice(
          "up",
          "Up 5 and right 0 is which pair?",
          [
            ["a", "(0, 5)"],
            ["b", "(5, 0)"],
          ],
          "a",
          "(5, 0) is right 5. You want no right and 5 up.",
          "No horizontal move, then the rise.",
        ),
        slider(
          "rise",
          "Set the second number for a rise of 5.",
          0,
          10,
          5,
          "The rise is higher. Move up.",
          "The rise is lower. Move down.",
          "The second number is 5.",
        ),
        choice(
          "tail",
          "Changing the tail does not change the pair. The pair records...",
          [
            ["a", "The move"],
            ["b", "The tail's place"],
          ],
          "a",
          "The place of the tail can change. The pair is the displacement.",
          "The pair is the move.",
        ),
      ]),
      lesson("Read without a hint", "The pair is tip minus tail, one axis at a time.", [
        choice(
          "vertical",
          "An arrow from (2, 2) to (2, 6). The pair is...",
          [
            ["a", "(0, 4)"],
            ["b", "(4, 0)"],
          ],
          "a",
          "x does not change. y grows by 4, so the pair is (0, 4).",
          "Same x, rise 4.",
        ),
        slider(
          "part",
          "Set the vertical part of that pair.",
          0,
          10,
          4,
          "y goes from 2 to 6. Move higher.",
          "The rise is smaller than that. Move lower.",
          "The vertical part is 4.",
        ),
        drag(
          "three",
          "Draw (3, 1) from (2, 2). The tip is at (5, 3).",
          [2, 2],
          [5, 3],
          "The pair goes right and a little up.",
          "The direction matches. Stop at (5, 3).",
          "The tip is tail plus the pair.",
        ),
        choice(
          "name",
          "Two numbers with a direction are called what?",
          [
            ["a", "A vector"],
            ["b", "A quadrant"],
          ],
          "a",
          "A quadrant is a region. This pair is a vector.",
          "The pair is a vector.",
        ),
        choice(
          "down",
          "(1, -2) points which way?",
          [
            ["a", "Right and down"],
            ["b", "Left and up"],
          ],
          "a",
          "Positive first number is right. Negative second number is down.",
          "Right, then down.",
        ),
      ]),
    ],
  ),
  skill(
    "component-add",
    "Component addition",
    "You can add vectors component by component.",
    "Pip can add two vectors.",
    "vectors",
    [
      lesson("Add each place", "Residual connections add vectors of the same shape.", [
        choice(
          "how",
          "Add (2, 1) and (3, 4) by adding what?",
          [
            ["a", "Each place separately"],
            ["b", "Only the first numbers"],
          ],
          "a",
          "The second numbers add too. Both places get a sum.",
          "Add the firsts, then add the seconds.",
        ),
        slider(
          "first",
          "2 + 3. Set the first number of the sum.",
          0,
          10,
          5,
          "2 + 3 is higher. Move up.",
          "2 + 3 is lower. Move down.",
          "The first place sums to 5.",
        ),
        slider(
          "second",
          "1 + 4. Set the second number of the sum.",
          0,
          10,
          5,
          "1 + 4 is higher. Move up.",
          "1 + 4 is lower. Move down.",
          "The second place sums to 5.",
        ),
        choice(
          "sum",
          "The sum of (2, 1) and (3, 4) is...",
          [
            ["a", "(5, 5)"],
            ["b", "(6, 3)"],
          ],
          "a",
          "(6, 3) mixes the places. Add 2 with 3, and 1 with 4.",
          "Each place has its own sum.",
        ),
        drag(
          "draw",
          "Draw the sum (5, 2) from (1, 1).",
          [1, 1],
          [6, 3],
          "The sum goes right and up.",
          "The direction matches. The sum ends at (6, 3).",
          "The sum is one arrow.",
        ),
      ]),
      lesson("Add a negative", "A negative component pulls that place back.", [
        slider(
          "back",
          "4 + (-1). Set the first number.",
          -2,
          8,
          3,
          "4 plus negative 1 is higher than that. Move up.",
          "You subtracted less than 1. Move down.",
          "4 and -1 meet at 3.",
        ),
        slider(
          "up",
          "2 + 2. Set the second number.",
          0,
          10,
          4,
          "The seconds add to more. Move up.",
          "The seconds add to less. Move down.",
          "The second place is 4.",
        ),
        choice(
          "pair",
          "(4, 2) + (-1, 2) is...",
          [
            ["a", "(3, 4)"],
            ["b", "(5, 0)"],
          ],
          "a",
          "First place: 4 + -1 = 3. Second place: 2 + 2 = 4.",
          "Subtract on the first place, add on the second.",
        ),
        choice(
          "double",
          "Adding a vector to itself is the same as...",
          [
            ["a", "Doubling it"],
            ["b", "Erasing it"],
          ],
          "a",
          "Each place is added to itself, so each place doubles.",
          "v + v is 2v.",
        ),
        drag(
          "three",
          "Draw (3, 4) from (2, 1).",
          [2, 1],
          [5, 5],
          "The arrow goes right and up.",
          "The direction matches. Stop at (5, 5).",
          "Tail plus the pair is the tip.",
        ),
      ]),
      lesson("Add without a scaffold", "Order does not change a sum of vectors.", [
        choice(
          "axes",
          "(1, 0) + (0, 1) is...",
          [
            ["a", "(1, 1)"],
            ["b", "(0, 0)"],
          ],
          "a",
          "The first place gets 1. The second place gets 1. Nothing cancels.",
          "One step right plus one step up.",
        ),
        slider(
          "five",
          "5 + 0. Set the first number.",
          0,
          10,
          5,
          "Adding zero leaves 5. Move higher.",
          "Adding zero does not grow past 5. Move lower.",
          "Zero adds nothing.",
        ),
        choice(
          "residual",
          "A residual connection adds two vectors by adding...",
          [
            ["a", "Matching places"],
            ["b", "Their titles"],
          ],
          "a",
          "The shapes match, so each place has a partner to add.",
          "Matching places add.",
        ),
        slider(
          "three",
          "0 + 3. Set the second number.",
          0,
          10,
          3,
          "The second place is higher. Move up.",
          "The second place is lower. Move down.",
          "The second place is 3.",
        ),
        choice(
          "order",
          "(1, 2) + (3, 0) equals...",
          [
            ["a", "(4, 2)"],
            ["b", "(1, 5)"],
          ],
          "a",
          "1 + 3 is 4. 2 + 0 is 2. (1, 5) adds across places.",
          "Add straight down the pair.",
        ),
      ]),
    ],
  ),
  skill(
    "scalar-multiply",
    "Scalar multiplication",
    "You can scale both components together.",
    "Pip can scale a vector.",
    "vectors",
    [
      lesson("Scale both numbers", "A weight multiplies every part of a signal.", [
        choice(
          "both",
          "Multiply (2, 3) by 2. You scale which numbers?",
          [
            ["a", "Both numbers"],
            ["b", "Only the first"],
          ],
          "a",
          "A scalar hits every component, not just the first.",
          "Both places double.",
        ),
        slider(
          "first",
          "2 times 2. Set the first number.",
          0,
          10,
          4,
          "2 times 2 is higher. Move up.",
          "2 times 2 is lower. Move down.",
          "The first place is 4.",
        ),
        slider(
          "second",
          "3 times 2. Set the second number.",
          0,
          10,
          6,
          "3 times 2 is higher. Move up.",
          "3 times 2 is lower. Move down.",
          "The second place is 6.",
        ),
        choice(
          "result",
          "(2, 3) times 2 is...",
          [
            ["a", "(4, 6)"],
            ["b", "(2, 6)"],
          ],
          "a",
          "(2, 6) leaves the first number unscaled.",
          "Both numbers doubled.",
        ),
        drag(
          "draw",
          "Draw the doubled arrow (4, 2) from (1, 1).",
          [1, 1],
          [5, 3],
          "The doubled arrow goes right and up.",
          "The direction matches. Stop at (5, 3).",
          "Doubling scales the whole arrow.",
        ),
      ]),
      lesson("Scale by a half", "Halving multiplies every component by the same amount.", [
        slider(
          "half-first",
          "Half of 6. Set the first number of (6, 4) halved.",
          0,
          10,
          3,
          "Half of 6 is higher. Move up.",
          "Half of 6 is lower. Move down.",
          "The first place is 3.",
        ),
        slider(
          "half-second",
          "Half of 4. Set the second number.",
          0,
          10,
          2,
          "Half of 4 is higher. Move up.",
          "Half of 4 is lower. Move down.",
          "The second place is 2.",
        ),
        choice(
          "pair",
          "(6, 4) times 1/2 is...",
          [
            ["a", "(3, 2)"],
            ["b", "(6, 2)"],
          ],
          "a",
          "(6, 2) halves only the second number.",
          "Both places are halved.",
        ),
        choice(
          "zero",
          "Times 0 gives...",
          [
            ["a", "(0, 0)"],
            ["b", "The same vector"],
          ],
          "a",
          "Every component times 0 is 0.",
          "A zero scale clears the vector.",
        ),
        choice(
          "weight",
          "A weight multiplies a signal by scaling...",
          [
            ["a", "Every component"],
            ["b", "Only the label"],
          ],
          "a",
          "The weight is one number applied to each place.",
          "Every component feels the weight.",
        ),
      ]),
      lesson("Scale a signed pair", "A positive scale keeps the direction.", [
        choice(
          "signed",
          "(1, -2) times 3 is...",
          [
            ["a", "(3, -6)"],
            ["b", "(-3, 2)"],
          ],
          "a",
          "3 times 1 is 3. 3 times -2 is -6. The signs stay with their places.",
          "Both places triple, signs included.",
        ),
        slider(
          "three",
          "1 times 3. Set the first number.",
          -8,
          8,
          3,
          "1 times 3 is higher. Move up.",
          "1 times 3 is lower. Move down.",
          "The first place is 3.",
        ),
        slider(
          "neg",
          "-2 times 3. Set the second number.",
          -8,
          8,
          -6,
          "That is past -6. Move toward zero.",
          "-2 times 3 is -6. Move lower.",
          "The second place is -6.",
        ),
        drag(
          "flat",
          "Draw (3, 0) from (2, 4).",
          [2, 4],
          [5, 4],
          "This scaled arrow is straight right.",
          "The aim is right. The run is 3.",
          "The second number stayed 0.",
        ),
        choice(
          "aim",
          "A positive scale keeps the direction. The arrow...",
          [
            ["a", "Stays aimed the same way"],
            ["b", "Must turn"],
          ],
          "a",
          "Multiplying by a positive number stretches. It does not turn.",
          "Positive scale, same aim.",
        ),
      ]),
    ],
  ),
  skill(
    "length-unit",
    "Length and direction",
    "You can separate length from direction.",
    "Pip can tell size from aim.",
    "vectors",
    [
      lesson("Size and aim", "Normalization keeps direction and drops raw size.", [
        choice(
          "split",
          "Length is the size of the move. Direction is...",
          [
            ["a", "Which way it points"],
            ["b", "The same number as length"],
          ],
          "a",
          "Two arrows can share an aim and still have different lengths.",
          "Aim and size are different facts.",
        ),
        slider(
          "three",
          "An arrow (3, 0) has what length?",
          0,
          10,
          3,
          "Along one axis, the length is the absolute component. Move higher.",
          "The length is the size 3, not more. Move lower.",
          "A flat arrow's length is its run.",
        ),
        choice(
          "longer",
          "(0, 4) and (0, 2) share a direction. Which is longer?",
          [
            ["a", "(0, 4)"],
            ["b", "(0, 2)"],
          ],
          "a",
          "Both point up. 4 is a longer rise than 2.",
          "Same aim, greater length.",
        ),
        drag(
          "unit",
          "Draw a unit step right, from (2, 3) to (3, 3).",
          [2, 3],
          [3, 3],
          "A unit step right stays on the horizontal line.",
          "The aim is right. A unit step is 1 unit long.",
          "Length 1, direction right.",
        ),
        choice(
          "unit-name",
          "A unit direction keeps the aim and sets the length to...",
          [
            ["a", "1"],
            ["b", "0"],
          ],
          "a",
          "Zero length has no direction left. A unit length is 1.",
          "Unit length is 1.",
        ),
      ]),
      lesson("Drop the size", "Dividing by the length keeps the direction.", [
        slider(
          "six",
          "(6, 0) is twice (3, 0). Set the length of (6, 0).",
          0,
          10,
          6,
          "The flat arrow is longer than that. Move up.",
          "The flat arrow is shorter than that. Move down.",
          "The length is 6.",
        ),
        choice(
          "divide",
          "Dividing by the length keeps...",
          [
            ["a", "The direction"],
            ["b", "A new turn"],
          ],
          "a",
          "You shrink the arrow onto length 1. The aim stays.",
          "The aim survives the resize.",
        ),
        choice(
          "same",
          "(5, 0) points the same way as...",
          [
            ["a", "(1, 0)"],
            ["b", "(0, 1)"],
          ],
          "a",
          "(0, 1) points up. (5, 0) and (1, 0) both point right.",
          "Same direction, different length.",
        ),
        slider(
          "up",
          "Set the length of a pure up arrow (0, 4).",
          0,
          10,
          4,
          "The rise is the length. Move higher.",
          "The rise is shorter than that. Move lower.",
          "Straight up, length 4.",
        ),
        choice(
          "norm",
          "Normalization drops raw size so that...",
          [
            ["a", "A huge number cannot drown the aim"],
            ["b", "Every vector becomes zero"],
          ],
          "a",
          "The aim stays. Only the raw size is removed.",
          "Direction stays. Size is set aside.",
        ),
      ]),
      lesson("Keep the aim", "You can change length and keep the direction.", [
        choice(
          "greater",
          "Two arrows point the same way. The longer one has...",
          [
            ["a", "Greater length"],
            ["b", "A different direction"],
          ],
          "a",
          "Same way means the direction matches. Length is what differs.",
          "Longer means greater length.",
        ),
        slider(
          "four",
          "The length of (2, 0) doubled is...",
          0,
          10,
          4,
          "Double 2 is higher. Move up.",
          "Double 2 is lower. Move down.",
          "Doubling length does not turn the arrow.",
        ),
        drag(
          "up",
          "Draw the direction of (0, 1) with length 4. Tail (3, 1), tip (3, 5).",
          [3, 1],
          [3, 5],
          "That direction is straight up.",
          "The aim is up. The length is 4.",
          "Same aim as (0, 1), longer body.",
        ),
        choice(
          "down",
          "(0, -3) points which way?",
          [
            ["a", "Down"],
            ["b", "Up"],
          ],
          "a",
          "A negative second number points down.",
          "Negative y is down.",
        ),
        choice(
          "separate",
          "You can change the length and...",
          [
            ["a", "Keep the direction"],
            ["b", "Lose the vector"],
          ],
          "a",
          "Length and direction come apart. Changing one can leave the other.",
          "Size and aim are separate.",
        ),
      ]),
    ],
  ),
  skill(
    "dot-agreement",
    "Dot product",
    "You can see how much two arrows agree.",
    "Pip can score agreement.",
    "vectors",
    [
      lesson("Same, opposite, right angle", "A neuron's first step is this agreement score.", [
        drag(
          "same",
          "Drag your tip the same way as the gray arrow.",
          [2, 2],
          [7, 2],
          "Your arrow turns away. The gray arrow points right.",
          "The direction matches. Stretch or shorten to the mark.",
          "Same direction means a positive agreement.",
          right,
          "positive",
        ),
        drag(
          "opposite",
          "Drag your tip the opposite way from the gray arrow.",
          [7, 2],
          [2, 2],
          "Opposite means the other way. The gray arrow points right.",
          "You are aimed the other way. Match the length of the mark.",
          "Opposite arrows disagree.",
          right,
          "negative",
        ),
        drag(
          "perp",
          "Drag your tip so it meets the gray arrow at a right angle.",
          [4, 1],
          [4, 6],
          "Straight up meets the gray arrow at a right angle.",
          "The aim is up. Match the length of the mark.",
          "A right angle means no agreement.",
          { start: [2, 3], tip: [7, 3] },
          "zero",
        ),
        slider(
          "score",
          "Same way and fairly long. Set a high agreement, 8.",
          0,
          10,
          8,
          "Same direction is a high score. Move up.",
          "8 is high on this scale. Come down a little.",
          "Agreement is high when the arrows share a direction.",
        ),
        choice(
          "neuron",
          "What score do these arrows earn?",
          [
            ["a", "Positive"],
            ["b", "Zero"],
            ["c", "Negative"],
          ],
          "a",
          "They point the same way, so the score is positive.",
          "Same direction scores positive.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [2, 3], tip: [7, 3] },
            ],
          },
        ),
      ]),
      lesson("Compute the score", "You multiply matching places, then add those products.", [
        choice(
          "one",
          "(1, 0) dot (1, 0) is...",
          [
            ["a", "1"],
            ["b", "0"],
          ],
          "a",
          "1 times 1, plus 0 times 0, is 1.",
          "Same unit arrows score 1.",
          {
            arrows: [
              { start: [2, 6], tip: [6, 6], guide: true },
              { start: [2, 3], tip: [6, 3] },
            ],
            score: "positive",
          },
        ),
        choice(
          "against",
          "(1, 0) dot (-1, 0) is...",
          [
            ["a", "-1"],
            ["b", "1"],
          ],
          "a",
          "1 times -1 is -1. The zeros add nothing.",
          "Opposite unit arrows score -1.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [7, 3], tip: [2, 3] },
            ],
            score: "negative",
          },
        ),
        choice(
          "square",
          "(1, 0) dot (0, 1) is...",
          [
            ["a", "0"],
            ["b", "1"],
          ],
          "a",
          "1 times 0 plus 0 times 1 is 0. A right angle shares nothing.",
          "A right angle scores 0.",
          {
            arrows: [
              { start: [2, 4], tip: [7, 4], guide: true },
              { start: [4, 2], tip: [4, 7] },
            ],
            score: "zero",
          },
        ),
        slider(
          "high",
          "Two arrows point the same way. Set a high agreement.",
          0,
          10,
          8,
          "Same direction scores high. Move up.",
          "Stay high, but 8 is the mark on this scale. Move down.",
          "Shared direction scores high.",
        ),
        choice(
          "product",
          "(2, 0) dot (3, 0) is...",
          [
            ["a", "6"],
            ["b", "5"],
          ],
          "a",
          "2 times 3 is 6. Adding the zeros changes nothing.",
          "Multiply the matching places.",
        ),
      ]),
      lesson("Read a negative", "A negative score tells the model the signals point apart.", [
        slider(
          "four",
          "(4, 0) dot (1, 0) equals 4. Set that score.",
          0,
          10,
          4,
          "4 times 1 is higher than that. Move up.",
          "4 times 1 is lower than that. Move down.",
          "The score is 4.",
        ),
        choice(
          "apart",
          "What score do these arrows earn?",
          [
            ["a", "Negative"],
            ["b", "Positive"],
          ],
          "a",
          "They point against each other, so the score is negative.",
          "Opposite arrows score negative.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [7, 3], tip: [2, 3] },
            ],
          },
        ),
        choice(
          "four-sum",
          "(2, 1) dot (1, 2) is 2 + 2. That is...",
          [
            ["a", "4"],
            ["b", "3"],
          ],
          "a",
          "2 times 1 is 2, and 1 times 2 is 2. The sum is 4.",
          "Add the two products.",
        ),
        slider(
          "mark",
          "Set the score 4.",
          0,
          10,
          4,
          "The score is higher. Move up.",
          "The score is lower. Move down.",
          "The products added to 4.",
        ),
        choice(
          "share",
          "Bigger agreement means the arrows...",
          [
            ["a", "Share more direction"],
            ["b", "Must be perpendicular"],
          ],
          "a",
          "Perpendicular is zero. More shared direction raises the score.",
          "More shared direction, higher score.",
        ),
      ]),
      lesson("Rank the pairs", "The model keeps the pattern with the stronger agreement.", [
        choice(
          "most",
          "Which pair agrees most?",
          [
            ["a", "The pair that points the same way"],
            ["b", "The pair at a right angle"],
          ],
          "a",
          "A right angle scores 0. The pair that points the same way scores higher.",
          "Same direction beats a right angle.",
          {
            arrows: [
              { start: [1, 7], tip: [5, 7], guide: true },
              { start: [1, 5], tip: [5, 5] },
              { start: [6, 2], tip: [6, 6] },
            ],
          },
        ),
        choice(
          "least",
          "Which pair agrees least?",
          [
            ["a", "The pair that points opposite ways"],
            ["b", "The pair that points the same way"],
          ],
          "a",
          "Same direction scores positive. Opposite scores negative.",
          "Opposite is the low score.",
          {
            arrows: [
              { start: [2, 7], tip: [7, 7], guide: true },
              { start: [7, 4], tip: [2, 4] },
            ],
            score: "negative",
          },
        ),
        slider(
          "zero",
          "(3, 0) dot (0, 5) is zero. Set the score.",
          0,
          10,
          0,
          "A right angle is not below zero on this screen. The score is zero.",
          "The arrows are perpendicular. Move down to zero.",
          "No shared direction, score 0.",
        ),
        choice(
          "useful",
          "Perpendicular arrows matter because the score says they...",
          [
            ["a", "Share nothing"],
            ["b", "Are equal"],
          ],
          "a",
          "Equal arrows agree. A right angle shares no direction.",
          "Zero means they share nothing.",
        ),
        choice(
          "winner",
          "What score wins?",
          [
            ["a", "Positive"],
            ["b", "Zero"],
          ],
          "a",
          "Zero shares nothing. The positive pair wins.",
          "Keep the strongest agreement.",
          {
            arrows: [
              { start: [2, 6], tip: [7, 6], guide: true },
              { start: [2, 3], tip: [7, 3] },
            ],
            score: "positive",
          },
        ),
      ]),
    ],
  ),
  skill(
    "pattern-match",
    "Pattern match",
    "You can match the closer pattern.",
    "Pip can tell which pattern is closer.",
    "vectors",
    [
      lesson("Keep the match", "Attention starts by scoring which pattern agrees.", [
        choice(
          "keep",
          "Which pattern should Pip keep?",
          [
            ["a", "The one that points the same way"],
            ["b", "The one that points the other way"],
          ],
          "a",
          "The gray arrow and the blue arrow point the same way.",
          "Pip keeps the agreeing pattern.",
          {
            arrows: [
              { start: [1, 6], tip: [6, 6], guide: true },
              { start: [1, 4], tip: [6, 4] },
              { start: [8, 2], tip: [3, 2] },
            ],
          },
        ),
        match(
          "pairs",
          "Match each pattern with the way it points.",
          [
            ["sample", "Sample"],
            ["other", "Other"],
          ],
          [
            ["same", "Same way"],
            ["opp", "Opposite way"],
          ],
          [
            ["sample", "same"],
            ["other", "opp"],
          ],
          "Pair both patterns.",
          "The sample matches the same way. The other matches the opposite way.",
          "Each pattern has a direction relative to the sample.",
        ),
        slider(
          "high",
          "The matching pattern scores higher. Set 8.",
          0,
          10,
          8,
          "A match scores high. Move up.",
          "8 is the high mark here. Move down a little.",
          "The match scores higher.",
        ),
        choice(
          "low",
          "A low score means the patterns...",
          [
            ["a", "Point apart"],
            ["b", "Match"],
          ],
          "a",
          "A match scores high. A low score means they point apart.",
          "Low agreement means they differ.",
        ),
        choice(
          "tool",
          "Pip compares the patterns with a...",
          [
            ["a", "Dot product"],
            ["b", "Coin flip"],
          ],
          "a",
          "The comparison is the agreement score, the dot product.",
          "The dot product is the comparison.",
        ),
      ]),
      lesson("Closer means agreement", "Closer, here, means a higher agreement score.", [
        choice(
          "pick",
          "Pattern A agrees. Pattern B is perpendicular. Pip picks...",
          [
            ["a", "A"],
            ["b", "B"],
          ],
          "a",
          "Perpendicular scores zero. The agreeing pattern scores higher.",
          "Higher agreement is the closer pattern.",
        ),
        slider(
          "zero",
          "Set the agreement of the perpendicular pattern.",
          0,
          10,
          0,
          "A right angle does not score below zero here. The score is zero.",
          "A right angle scores zero. Move down.",
          "Perpendicular agreement is 0.",
        ),
        choice(
          "meaning",
          "Closer, on this path, means...",
          [
            ["a", "Higher agreement"],
            ["b", "Drawn nearer on the page"],
          ],
          "a",
          "The page position is not the score. Agreement is.",
          "Closer means the higher score.",
        ),
        drag(
          "aim",
          "Aim at the matching pattern, to the right.",
          [2, 3],
          [8, 3],
          "The matching pattern sits to the right.",
          "The aim is right. Reach the mark.",
          "You aimed at the match.",
        ),
        choice(
          "store",
          "You did not store a photo. You stored...",
          [
            ["a", "A score"],
            ["b", "A filename"],
          ],
          "a",
          "The match is a number, the agreement.",
          "The match is a score.",
        ),
      ]),
      lesson("Pick the winner", "Keep the pattern with the higher agreement.", [
        choice(
          "winner",
          "Scores are 1, 5, and 0. Pip keeps...",
          [
            ["a", "The score of 5"],
            ["b", "The score of 0"],
          ],
          "a",
          "5 agrees more than 1 or 0.",
          "The highest score wins.",
        ),
        slider(
          "five",
          "Set that winning score.",
          0,
          10,
          5,
          "The winner is higher. Move up.",
          "The winner is lower. Move down.",
          "The winner is 5.",
        ),
        choice(
          "tie",
          "If two scores tie, the patterns...",
          [
            ["a", "Agree equally"],
            ["b", "Cancel the lesson"],
          ],
          "a",
          "A tie means the agreements match. Nothing is cancelled.",
          "Equal scores, equal agreement.",
        ),
        match(
          "kinds",
          "Match each score with its directions.",
          [
            ["high", "High score"],
            ["zero", "Zero score"],
          ],
          [
            ["same", "Same direction"],
            ["right", "Right angle"],
          ],
          [
            ["high", "same"],
            ["zero", "right"],
          ],
          "Pair both scores.",
          "A high score is the same direction. Zero is a right angle.",
          "The score names the directions.",
        ),
        choice(
          "next",
          "Score the patterns, then...",
          [
            ["a", "Keep the stronger match"],
            ["b", "Keep every pattern equally"],
          ],
          "a",
          "Equal keeping ignores the score you just computed.",
          "The stronger match stays.",
        ),
      ]),
    ],
  ),
  skill(
    "projection",
    "Projection",
    "You can see one arrow's shadow on another.",
    "Pip can cast a shadow.",
    "vectors",
    [
      lesson("Shadow on a line", "A projection keeps the part of a signal along one direction.", [
        choice(
          "keep",
          "The shadow of an arrow on a rightward line keeps...",
          [
            ["a", "The rightward part"],
            ["b", "The upward part"],
          ],
          "a",
          "The line points right, so the shadow keeps the rightward part.",
          "The shadow keeps the part along the line.",
        ),
        drag(
          "along",
          "Drag along the rightward line, from (1, 3) to (6, 3).",
          [1, 3],
          [6, 3],
          "The shadow lies on the horizontal line.",
          "The aim is right. Match the shadow's length.",
          "The shadow stays on the line.",
        ),
        slider(
          "len",
          "Arrow (4, 3) onto a horizontal line. Set the shadow length.",
          0,
          10,
          4,
          "The horizontal part is 4. Move higher.",
          "The upward 3 is not on this line. Move lower.",
          "The shadow length is the matching part, 4.",
        ),
        choice(
          "drop",
          "The leftover upward part is...",
          [
            ["a", "Left off the shadow"],
            ["b", "Added onto the shadow"],
          ],
          "a",
          "The shadow keeps only the part along the line.",
          "The rest drops away.",
        ),
        choice(
          "rest",
          "A projection keeps one direction. The rest...",
          [
            ["a", "Drops away"],
            ["b", "Doubles"],
          ],
          "a",
          "Doubling would grow the leftover. A projection removes it.",
          "Only the matching part stays.",
        ),
      ]),
      lesson("Onto the vertical", "The shadow on the y axis keeps the vertical part.", [
        slider(
          "len",
          "Arrow (2, 5) onto the vertical axis. Set the shadow length.",
          0,
          10,
          5,
          "The vertical part is 5. Move higher.",
          "The horizontal 2 is not on this axis. Move lower.",
          "The shadow is the vertical part.",
        ),
        choice(
          "pair",
          "Onto the y axis, (2, 5) leaves a shadow of...",
          [
            ["a", "(0, 5)"],
            ["b", "(2, 0)"],
          ],
          "a",
          "(2, 0) is the shadow on the x axis. The y axis keeps (0, 5).",
          "Vertical shadow, horizontal part gone.",
        ),
        drag(
          "up",
          "Draw that vertical shadow from (4, 1) to (4, 6).",
          [4, 1],
          [4, 6],
          "The shadow is straight up.",
          "The aim is up. The length is 5.",
          "The shadow stands on the vertical line.",
        ),
        choice(
          "none",
          "A perpendicular arrow casts...",
          [
            ["a", "No shadow"],
            ["b", "A full copy"],
          ],
          "a",
          "Perpendicular means no shared direction, so the shadow length is 0.",
          "Nothing lands on the line.",
        ),
        slider(
          "zero",
          "(0, 3) onto the x axis. Set the shadow length.",
          0,
          10,
          0,
          "There is no horizontal part below zero. The shadow is zero.",
          "The arrow is vertical, so the horizontal shadow is zero. Move down.",
          "No horizontal part, no shadow.",
        ),
      ]),
      lesson("Project twice", "Projecting twice onto the same line changes nothing the second time.", [
        choice(
          "stay",
          "(3, 0) onto the x axis is...",
          [
            ["a", "(3, 0)"],
            ["b", "(0, 3)"],
          ],
          "a",
          "It already lies on the x axis. The shadow is itself.",
          "Already on the line, so it stays.",
        ),
        slider(
          "three",
          "Set that shadow length.",
          0,
          10,
          3,
          "The length on the axis is 3. Move higher.",
          "The length on the axis is shorter. Move lower.",
          "The shadow length is 3.",
        ),
        choice(
          "twice",
          "Projecting twice onto the same line...",
          [
            ["a", "Changes nothing the second time"],
            ["b", "Doubles the arrow"],
          ],
          "a",
          "The second projection sees an arrow that is already on the line.",
          "The second pass is the same shadow.",
        ),
        drag(
          "draw",
          "Draw (3, 0) from (2, 2) to (5, 2).",
          [2, 2],
          [5, 2],
          "The shadow is horizontal.",
          "The aim is right. The length is 3.",
          "The shadow is the horizontal arrow.",
        ),
        choice(
          "name",
          "Keeping only the part along one direction is a...",
          [
            ["a", "Projection"],
            ["b", "Random crop"],
          ],
          "a",
          "The kept part is chosen by the direction, not by chance.",
          "That kept part is a projection.",
        ),
      ]),
      lesson("Name the shadow", "You used the agreement with (1, 0) to keep the matching part.", [
        choice(
          "which",
          "Arrow (4, 2) onto (1, 0). The shadow is...",
          [
            ["a", "(4, 0)"],
            ["b", "(0, 2)"],
          ],
          "a",
          "(1, 0) is horizontal, so the shadow keeps 4 and drops 2.",
          "The horizontal part stays.",
        ),
        slider(
          "first",
          "Set the shadow's first number.",
          0,
          10,
          4,
          "The matching part is 4. Move higher.",
          "The matching part is smaller. Move lower.",
          "The first number is 4.",
        ),
        choice(
          "second",
          "The second number of that shadow is...",
          [
            ["a", "0"],
            ["b", "2"],
          ],
          "a",
          "2 was the part off the line. The shadow drops it.",
          "The off-line part is 0 on the shadow.",
        ),
        slider(
          "zero",
          "Set the second number of the shadow.",
          0,
          5,
          0,
          "The second number is not negative. It is zero.",
          "The upward part is gone. Move down to zero.",
          "The second number is 0.",
        ),
        choice(
          "discard",
          "The rest of the arrow...",
          [
            ["a", "Is discarded"],
            ["b", "Becomes the shadow"],
          ],
          "a",
          "The shadow is the matching part. The rest is discarded.",
          "Only the agreement along the line stays.",
        ),
      ]),
    ],
  ),
  skill(
    "matrix-numbers",
    "Matrix numbers",
    "You can read a matrix as four numbers.",
    "Pip can read a 2 by 2 matrix.",
    "vectors",
    [
      lesson("Four numbers", "A small layer is a table of weights.", [
        choice(
          "count",
          "A 2 by 2 matrix holds how many numbers?",
          [
            ["a", "Four"],
            ["b", "One"],
          ],
          "a",
          "Two rows of two numbers is four cells.",
          "Four cells, two rows.",
        ),
        matrix(
          "identity",
          "Set the cells, left to right, top then bottom: 1, 0, 0, 1.",
          [1, 0, 0, 1],
          "A cell still misses 1, 0, 0, 1. Check the diagonal.",
          "That table leaves a point where it was.",
          true,
        ),
        choice(
          "a",
          "In 2, 0 / 0, 1, the top left number is...",
          [
            ["a", "2"],
            ["b", "0"],
          ],
          "a",
          "Top left is the first cell. The zeros sit beside and below it.",
          "Top left is the first weight.",
        ),
        matrix(
          "row",
          "Set 2, 1 / 0, 1. Top row first.",
          [2, 1, 0, 1],
          "One cell is off 2, 1, 0, 1. The bottom left stays 0.",
          "You set all four weights.",
          true,
        ),
        choice(
          "layer",
          "These four numbers are weights. A small layer is...",
          [
            ["a", "A table of weights"],
            ["b", "A single label"],
          ],
          "a",
          "The layer is the table, not one name.",
          "A small layer is this table.",
        ),
      ]),
      lesson("Read the cells", "The identity table is 1, 0 on the top row and 0, 1 below.", [
        matrix(
          "build",
          "Build the table that puts 1 and 2 on top, 3 and 0 below.",
          [1, 2, 3, 0],
          "A cell is still off 1, 2, 3, 0. Bottom right stays 0.",
          "Those are the four weights.",
        ),
        choice(
          "c",
          "The bottom left cell is called...",
          [
            ["a", "c"],
            ["b", "b"],
          ],
          "a",
          "b is top right. Bottom left is c.",
          "Bottom left is c.",
        ),
        choice(
          "identity",
          "1, 0 / 0, 1 leaves a point...",
          [
            ["a", "Where it was"],
            ["b", "At the origin always"],
          ],
          "a",
          "The identity keeps each point. It does not send everything to the origin.",
          "The identity keeps the point.",
        ),
        matrix(
          "again",
          "Set the identity again: 1, 0 / 0, 1.",
          [1, 0, 0, 1],
          "The diagonal cells are 1. The other two stay 0.",
          "You can rebuild the identity from the four numbers.",
        ),
        match(
          "axes",
          "Match the matrix words with the way you read them.",
          [
            ["row", "Row"],
            ["col", "Column"],
          ],
          [
            ["across", "Across"],
            ["down", "Down"],
          ],
          [
            ["row", "across"],
            ["col", "down"],
          ],
          "Pair both words.",
          "A row runs across. A column runs down.",
          "Rows across, columns down.",
        ),
      ]),
    ],
  ),
  skill(
    "matrix-vector",
    "Matrix times vector",
    "You can warp a point with a matrix.",
    "Pip can warp a point.",
    "vectors",
    [
      lesson("Double x", "A layer stretches the input this way.", [
        choice(
          "which",
          "The matrix 2, 0 / 0, 1 doubles which coordinate?",
          [
            ["a", "x"],
            ["b", "Both, by the same amount"],
          ],
          "a",
          "The bottom right is 1, so y stays. The top left 2 doubles x.",
          "x doubles. y stays.",
        ),
        matrix(
          "set",
          "Set 2, 0 / 0, 1.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "That table doubles x.",
          true,
        ),
        slider(
          "x",
          "A point at x = 3 becomes x = ...",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "x lands at 6.",
        ),
        choice(
          "y",
          "Its y...",
          [
            ["a", "Stays the same"],
            ["b", "Doubles too"],
          ],
          "a",
          "The matrix multiplies y by 1.",
          "y is unchanged.",
        ),
        drag(
          "move",
          "The point moves from (2, 2) to (4, 2). Drag the tip.",
          [2, 2],
          [4, 2],
          "x doubles, so the move is straight right.",
          "The aim is right. x goes from 2 to 4.",
          "The point slid right.",
        ),
      ]),
      lesson("Double y", "The bottom right weight scales y.", [
        choice(
          "which",
          "The matrix 1, 0 / 0, 2 doubles...",
          [
            ["a", "y"],
            ["b", "x"],
          ],
          "a",
          "Top left is 1, so x stays. Bottom right 2 doubles y.",
          "y doubles.",
        ),
        matrix(
          "set",
          "Set 1, 0 / 0, 2.",
          [1, 0, 0, 2],
          "Top left is 1 and bottom right is 2. Off-diagonal cells stay 0.",
          "That table doubles y.",
          true,
        ),
        slider(
          "y",
          "y = 3 becomes...",
          0,
          10,
          6,
          "3 doubled is higher. Move up.",
          "3 doubled is lower. Move down.",
          "y lands at 6.",
        ),
        choice(
          "x",
          "x...",
          [
            ["a", "Stays the same"],
            ["b", "Becomes zero"],
          ],
          "a",
          "x is multiplied by 1, so it stays.",
          "x is unchanged.",
        ),
        drag(
          "move",
          "From (2, 2) the point goes to (2, 4). Drag the tip.",
          [2, 2],
          [2, 4],
          "y doubles, so the move is straight up.",
          "The aim is up. y goes from 2 to 4.",
          "The point rose.",
        ),
      ]),
      lesson("Slide sideways", "The top right weight mixes y into x.", [
        choice(
          "land",
          "(2, 1) through 1, 1 / 0, 1 lands at...",
          [
            ["a", "(3, 1)"],
            ["b", "(2, 1)"],
          ],
          "a",
          "New x is 1 times 2 plus 1 times 1. y stays 1.",
          "x picks up the y. y stays.",
        ),
        matrix(
          "set",
          "Set the table that slides x by y.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "That table slides x by y.",
        ),
        slider(
          "x",
          "Set the new x, which is 3.",
          0,
          10,
          3,
          "The new x is higher. Move up.",
          "The new x is lower. Move down.",
          "The new x is 3.",
        ),
        choice(
          "y",
          "y is unchanged at...",
          [
            ["a", "1"],
            ["b", "3"],
          ],
          "a",
          "The bottom row keeps y and does not take from x.",
          "y stays 1.",
        ),
        drag(
          "move",
          "Drag from (1, 1) to the image (2, 1).",
          [1, 1],
          [2, 1],
          "The image is straight right of the start.",
          "The aim is right. x grows by 1.",
          "The point slid sideways.",
        ),
      ]),
      lesson("Stretch both", "The four numbers decide where each point moves.", [
        choice(
          "zero",
          "0, 0 / 0, 0 sends every point to...",
          [
            ["a", "The origin"],
            ["b", "The same point"],
          ],
          "a",
          "Every weight is 0, so both new coordinates are 0.",
          "A zero table sends points to the origin.",
        ),
        matrix(
          "both",
          "Set a double on both axes: 2, 0 / 0, 2.",
          [2, 0, 0, 2],
          "The diagonal cells are 2. The other cells stay 0.",
          "Both axes double.",
        ),
        slider(
          "x",
          "x = 2 becomes...",
          0,
          10,
          4,
          "2 doubled is higher. Move up.",
          "2 doubled is lower. Move down.",
          "x lands at 4.",
        ),
        slider(
          "y",
          "y = 2 becomes...",
          0,
          10,
          4,
          "2 doubled is higher. Move up.",
          "2 doubled is lower. Move down.",
          "y lands at 4.",
        ),
        choice(
          "decide",
          "The four numbers decide...",
          [
            ["a", "Where each point moves"],
            ["b", "The point's color"],
          ],
          "a",
          "The table moves the point. It does not paint it.",
          "The warp is the move.",
        ),
      ]),
    ],
  ),
  skill(
    "drawing-stretch",
    "Drawing stretch",
    "You can watch a drawing stretch.",
    "Pip can stretch a drawing.",
    "vectors",
    [
      lesson("Stretch sideways", "Features move together when a matrix warps space.", [
        choice(
          "every",
          "A tiny drawing is a few points. The same matrix moves...",
          [
            ["a", "Every point"],
            ["b", "Only the first point"],
          ],
          "a",
          "One table applies to every point in the drawing.",
          "Every point uses the same warp.",
        ),
        matrix(
          "wide",
          "Use 2, 0 / 0, 1 to stretch the drawing sideways.",
          [2, 0, 0, 1],
          "Top left is 2, bottom right is 1, and the other cells stay 0.",
          "That stretch doubles width.",
          true,
        ),
        slider(
          "corner",
          "A corner at x = 1 moves to...",
          0,
          10,
          2,
          "x doubles. Move higher.",
          "x doubles to less than that. Move lower.",
          "The corner's x is 2.",
        ),
        drag(
          "travel",
          "That corner travels from (1, 2) to (2, 2). Drag the tip.",
          [1, 2],
          [2, 2],
          "The corner moves straight right.",
          "The aim is right. x grows from 1 to 2.",
          "The corner moved with the stretch.",
        ),
        choice(
          "shape",
          "The height stays put. The drawing gets...",
          [
            ["a", "Wider"],
            ["b", "Taller"],
          ],
          "a",
          "y is multiplied by 1. Only x grows, so the drawing gets wider.",
          "Width grows. Height stays.",
        ),
      ]),
      lesson("Stretch upward", "The same rule can stretch height instead of width.", [
        matrix(
          "tall",
          "Set the table that doubles height and leaves width alone.",
          [1, 0, 0, 2],
          "Top left is 1 and bottom right is 2. The other cells stay 0.",
          "That table doubles height.",
        ),
        choice(
          "gets",
          "The drawing gets...",
          [
            ["a", "Taller"],
            ["b", "Only wider"],
          ],
          "a",
          "y doubles and x stays, so the drawing grows upward.",
          "Height doubles.",
        ),
        slider(
          "top",
          "A top at y = 2 moves to...",
          0,
          10,
          4,
          "y doubles. Move higher.",
          "y doubles to less than that. Move lower.",
          "The top moves to 4.",
        ),
        drag(
          "rise",
          "From (3, 1) to (3, 2). Drag the tip.",
          [3, 1],
          [3, 2],
          "This corner moves straight up.",
          "The aim is up. The rise is 1.",
          "The corner rose.",
        ),
        choice(
          "line",
          "Points that sat on a line still sit on a line. The warp is...",
          [
            ["a", "Even"],
            ["b", "A scribble"],
          ],
          "a",
          "A matrix moves lines to lines. It does not scribble.",
          "Lines stay lines.",
        ),
      ]),
      lesson("Grow both ways", "Doubling both axes grows the drawing and keeps its shape.", [
        matrix(
          "both",
          "Set 2, 0 / 0, 2.",
          [2, 0, 0, 2],
          "Both diagonal cells are 2. The other cells stay 0.",
          "Both axes double.",
        ),
        choice(
          "shape",
          "Both axes double. The drawing...",
          [
            ["a", "Grows and keeps its shape"],
            ["b", "Flips upside down"],
          ],
          "a",
          "Both scales are positive and equal, so the shape grows without a flip.",
          "Same scale on both axes keeps the shape.",
        ),
        slider(
          "x",
          "A point at (1, 1) moves to x = ...",
          0,
          10,
          2,
          "x doubles. Move higher.",
          "x doubles to less than that. Move lower.",
          "The new x is 2.",
        ),
        slider(
          "y",
          "And y = ...",
          0,
          10,
          2,
          "y doubles too. Move higher.",
          "y doubles to less than that. Move lower.",
          "The new y is 2.",
        ),
        choice(
          "why",
          "Features move together. A matrix can...",
          [
            ["a", "Stretch a whole drawing"],
            ["b", "Paint one pixel and stop"],
          ],
          "a",
          "Every point of the drawing uses the same table.",
          "The whole drawing stretches together.",
        ),
      ]),
    ],
  ),
  skill(
    "two-warps",
    "Two warps",
    "You can apply one warp, then another.",
    "Pip can stack two warps.",
    "vectors",
    [
      lesson("One, then the other", "Stacked layers are transformations applied in order.", [
        choice(
          "order",
          "You apply the first matrix, then the second. The point moves...",
          [
            ["a", "Twice, in order"],
            ["b", "Only by the first matrix"],
          ],
          "a",
          "The second matrix sees the point the first matrix produced.",
          "Two warps, in order.",
        ),
        matrix(
          "first",
          "Set the first warp: 2, 0 / 0, 1.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "The first warp doubles x.",
          true,
        ),
        matrix(
          "second",
          "Set the second warp: 1, 0 / 0, 2.",
          [1, 0, 0, 2],
          "Top left is 1 and bottom right is 2. The other cells stay 0.",
          "The second warp doubles y.",
          true,
        ),
        slider(
          "x",
          "Start at 1. After x doubles, x ends at...",
          0,
          10,
          2,
          "1 doubled is higher. Move up.",
          "1 doubled is lower. Move down.",
          "x ends at 2.",
        ),
        slider(
          "y",
          "After y doubles, y ends at...",
          0,
          10,
          2,
          "1 doubled is higher. Move up.",
          "1 doubled is lower. Move down.",
          "y ends at 2.",
        ),
      ]),
      lesson("Order matters", "The second warp sees the first warp's output.", [
        choice(
          "matters",
          "Doing A then B can differ from B then A. Order...",
          [
            ["a", "Matters"],
            ["b", "Never matters"],
          ],
          "a",
          "The second warp acts on an already moved point.",
          "Order can change the result.",
        ),
        matrix(
          "a",
          "Warp A is 1, 1 / 0, 1. Set it.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "Warp A is set.",
          true,
        ),
        choice(
          "land",
          "(1, 1) through A lands at...",
          [
            ["a", "(2, 1)"],
            ["b", "(1, 1)"],
          ],
          "a",
          "New x is 1 plus 1. y stays 1.",
          "A slides the point to (2, 1).",
        ),
        matrix(
          "b",
          "Set the table that doubles width and leaves height alone.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "Warp B doubles x.",
        ),
        choice(
          "sees",
          "The second warp sees...",
          [
            ["a", "The first warp's output"],
            ["b", "Only the original point"],
          ],
          "a",
          "Stacking means the output of one becomes the input of the next.",
          "The second warp sees the first result.",
        ),
      ]),
      lesson("Two identities", "Two copies of the identity leave a point where it started.", [
        choice(
          "stay",
          "Two identity matrices in a row leave a point...",
          [
            ["a", "Where it started"],
            ["b", "At the origin"],
          ],
          "a",
          "Each identity keeps the point, so two of them still keep it.",
          "The point never moves.",
        ),
        matrix(
          "one",
          "Set the identity: 1, 0 / 0, 1.",
          [1, 0, 0, 1],
          "Diagonal cells are 1. The other two stay 0.",
          "The first identity is set.",
        ),
        matrix(
          "two",
          "Set the second identity: 1, 0 / 0, 1.",
          [1, 0, 0, 1],
          "Diagonal cells are 1 again. The other two stay 0.",
          "The second identity is set.",
        ),
        slider(
          "x",
          "Start x = 4. After both, x is...",
          0,
          10,
          4,
          "The identity keeps 4. Move higher.",
          "The identity does not grow 4. Move lower.",
          "x is still 4.",
        ),
        choice(
          "read",
          "A deep stack still applies the warps...",
          [
            ["a", "In order"],
            ["b", "With the order thrown away"],
          ],
          "a",
          "You can combine them later. The phone still applies them in order.",
          "Order stays, even in a stack.",
        ),
      ]),
    ],
  ),
  skill(
    "eigen-direction",
    "Eigen direction",
    "You can find a direction that only stretches.",
    "Pip can find a stretch direction.",
    "vectors",
    [
      lesson("A direction that stays", "Some directions only scale, and those directions structure a transformation.", [
        choice(
          "stay",
          "2, 0 / 0, 1 takes a rightward arrow to a longer rightward arrow. The direction...",
          [
            ["a", "Stays"],
            ["b", "Turns up"],
          ],
          "a",
          "x doubles and y stays 0, so a rightward arrow stays rightward.",
          "It stretches and does not turn.",
        ),
        drag(
          "draw",
          "Draw that stretch. Tail (2, 3), tip (6, 3). It stays horizontal.",
          [2, 3],
          [6, 3],
          "The stretch stays on the horizontal line.",
          "The aim is right. The stretched arrow is longer.",
          "Same direction, greater length.",
        ),
        matrix(
          "set",
          "Set 2, 0 / 0, 1.",
          [2, 0, 0, 1],
          "Top left is 2 and bottom right is 1. The other cells stay 0.",
          "That table stretches x.",
          true,
        ),
        choice(
          "name",
          "An arrow that only scales, and does not turn, lies on an...",
          [
            ["a", "Eigen direction"],
            ["b", "Unrelated heading"],
          ],
          "a",
          "The special name is the direction the matrix only scales.",
          "That direction is an eigen direction.",
        ),
        choice(
          "right",
          "An up arrow stays up but does not get longer. A right arrow...",
          [
            ["a", "Gets longer"],
            ["b", "Turns left"],
          ],
          "a",
          "x is doubled. A rightward arrow grows and stays right.",
          "The rightward direction stretches.",
        ),
      ]),
      lesson("Every direction scales", "Equal scales on both axes leave every aim in place.", [
        choice(
          "all",
          "2, 0 / 0, 2 scales every direction by 2. Arrows...",
          [
            ["a", "Stay aimed the same way"],
            ["b", "All turn"],
          ],
          "a",
          "Both coordinates double, so the aim of any arrow stays.",
          "Everything stretches, nothing turns.",
        ),
        matrix(
          "set",
          "Set 2, 0 / 0, 2.",
          [2, 0, 0, 2],
          "Both diagonal cells are 2. The other cells stay 0.",
          "Both axes scale by 2.",
        ),
        drag(
          "diag",
          "A diagonal that does not turn goes from (2, 2) to (4, 4).",
          [2, 2],
          [4, 4],
          "The diagonal stays on the line y = x.",
          "The aim matches. The tip is twice as far.",
          "The diagonal only got longer.",
        ),
        slider(
          "scale",
          "The scale on each axis is...",
          0,
          10,
          2,
          "Each diagonal cell is 2. Move higher.",
          "Each diagonal cell is less than that. Move lower.",
          "The scale is 2.",
        ),
        choice(
          "found",
          "You found a direction the matrix only scales. That direction...",
          [
            ["a", "Structures the warp"],
            ["b", "Is only decoration"],
          ],
          "a",
          "Those directions organize how the warp acts.",
          "Stretch directions structure the warp.",
        ),
      ]),
      lesson("One direction turns", "A sideways slide turns an upward arrow and leaves a horizontal arrow.", [
        choice(
          "up",
          "1, 1 / 0, 1 slides points sideways. A straight-up arrow...",
          [
            ["a", "Tilts"],
            ["b", "Only gets longer"],
          ],
          "a",
          "(0, 1) becomes (1, 1). It gains a sideways part, so it tilts.",
          "Up is not an eigen direction of this matrix.",
        ),
        drag(
          "flat",
          "The direction that does not turn is horizontal. Tail (2, 2), tip (6, 2).",
          [2, 2],
          [6, 2],
          "The stable direction is straight right.",
          "The aim is right. Stretch along the axis.",
          "Horizontal arrows stay horizontal.",
        ),
        choice(
          "tilt",
          "The upward arrow gains a sideways part. It...",
          [
            ["a", "Turns"],
            ["b", "Stays vertical"],
          ],
          "a",
          "A new horizontal part means it is no longer vertical.",
          "It turns.",
        ),
        matrix(
          "set",
          "Set the sideways slide: top row 1, 1 and bottom row 0, 1.",
          [1, 1, 0, 1],
          "Top row is 1, 1. Bottom row is 0, 1.",
          "That is the sideways slide.",
        ),
        choice(
          "organize",
          "Directions the matrix only stretches...",
          [
            ["a", "Organize the warp"],
            ["b", "Are decoration"],
          ],
          "a",
          "The warp is understood by the directions it only scales.",
          "Those directions organize the transformation.",
        ),
      ]),
    ],
  ),
  skill(
    "pip-capstone",
    "Teach Pip",
    "You can teach Pip to match patterns.",
    "Pip can match a pattern with a dot product.",
    "vectors",
    [
      lesson(
        "Match by agreement",
        "Matching by agreement is how a tiny network recognizes a pattern.",
        [
          drag(
            "same",
            "Match the gray arrow. It points right.",
            [2, 2],
            [7, 2],
            "The gray arrow points right. Aim the same way.",
            "The direction matches. Reach the mark.",
            "Same direction means the patterns agree.",
            right,
          ),
          choice(
            "agree",
            "That match means the patterns...",
            [
              ["a", "Agree"],
              ["b", "Point opposite ways"],
            ],
            "a",
            "Same direction is agreement, not opposition.",
            "The patterns agree.",
          ),
          drag(
            "opposite",
            "Now point the opposite way from the gray arrow.",
            [7, 3],
            [2, 3],
            "Opposite is left if the gray arrow points right.",
            "You are aimed the other way. Match the length.",
            "Opposite arrows get a negative score.",
            right,
          ),
          choice(
            "keep",
            "Pip keeps the pattern with...",
            [
              ["a", "The higher agreement"],
              ["b", "The first name in the list"],
            ],
            "a",
            "The name is not the score. The higher agreement wins.",
            "Higher agreement stays.",
          ),
          match(
            "scores",
            "Match each direction with its score.",
            [
              ["agree", "Agree"],
              ["oppose", "Oppose"],
              ["square", "Right angle"],
            ],
            [
              ["pos", "Positive"],
              ["neg", "Negative"],
              ["zero", "Zero"],
            ],
            [
              ["agree", "pos"],
              ["oppose", "neg"],
              ["square", "zero"],
            ],
            "Pair all three directions.",
            "Agree is positive, oppose is negative, and a right angle is zero.",
            "Each direction has a score.",
          ),
          slider(
            "high",
            "Set a high score for the matching pattern.",
            0,
            10,
            9,
            "The match scores high. Move up.",
            "9 is the high mark. Come down a little.",
            "The match scores high.",
          ),
          choice(
            "name",
            "A tiny layer scores that agreement with a...",
            [
              ["a", "Dot product"],
              ["b", "Stored photo"],
            ],
            "a",
            "The score is computed. It is not a saved picture.",
            "The score is a dot product.",
          ),
          choice(
            "taught",
            "You taught Pip to match. The math...",
            [
              ["a", "Scored which pattern agrees"],
              ["b", "Memorized the picture"],
            ],
            "a",
            "Matching here is a score, not a stored photo.",
            "Pip matches by agreement.",
          ),
        ],
        true,
      ),
    ],
  ),
];
